
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 24 2026 09:32:22 IST (Mar 24 2026 04:02:22 UTC)

// Verification Directory fv/serial 

module serial(clk, rst, A, B, C);
  input clk, rst;
  input [0:35] A, B;
  output [0:71] C;
  wire clk, rst;
  wire [0:35] A, B;
  wire [0:71] C;
  wire [2:0] gj;
  wire [2:0] gk;
  wire [2:0] gi;
  wire [9:0] acc;
  wire [1:0] PS;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_1,
       WALLACE_CSA_DUMMY_OP_groupi_n_2,
       WALLACE_CSA_DUMMY_OP_groupi_n_3,
       WALLACE_CSA_DUMMY_OP_groupi_n_4,
       WALLACE_CSA_DUMMY_OP_groupi_n_5,
       WALLACE_CSA_DUMMY_OP_groupi_n_6,
       WALLACE_CSA_DUMMY_OP_groupi_n_7, WALLACE_CSA_DUMMY_OP_groupi_n_8;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_9,
       WALLACE_CSA_DUMMY_OP_groupi_n_10,
       WALLACE_CSA_DUMMY_OP_groupi_n_11,
       WALLACE_CSA_DUMMY_OP_groupi_n_12,
       WALLACE_CSA_DUMMY_OP_groupi_n_13,
       WALLACE_CSA_DUMMY_OP_groupi_n_14,
       WALLACE_CSA_DUMMY_OP_groupi_n_15,
       WALLACE_CSA_DUMMY_OP_groupi_n_16;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_17,
       WALLACE_CSA_DUMMY_OP_groupi_n_18,
       WALLACE_CSA_DUMMY_OP_groupi_n_19,
       WALLACE_CSA_DUMMY_OP_groupi_n_20,
       WALLACE_CSA_DUMMY_OP_groupi_n_21,
       WALLACE_CSA_DUMMY_OP_groupi_n_22,
       WALLACE_CSA_DUMMY_OP_groupi_n_23,
       WALLACE_CSA_DUMMY_OP_groupi_n_24;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_25,
       WALLACE_CSA_DUMMY_OP_groupi_n_26,
       WALLACE_CSA_DUMMY_OP_groupi_n_27,
       WALLACE_CSA_DUMMY_OP_groupi_n_28,
       WALLACE_CSA_DUMMY_OP_groupi_n_29,
       WALLACE_CSA_DUMMY_OP_groupi_n_30,
       WALLACE_CSA_DUMMY_OP_groupi_n_32,
       WALLACE_CSA_DUMMY_OP_groupi_n_33;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_34,
       WALLACE_CSA_DUMMY_OP_groupi_n_35,
       WALLACE_CSA_DUMMY_OP_groupi_n_36,
       WALLACE_CSA_DUMMY_OP_groupi_n_37,
       WALLACE_CSA_DUMMY_OP_groupi_n_38,
       WALLACE_CSA_DUMMY_OP_groupi_n_39,
       WALLACE_CSA_DUMMY_OP_groupi_n_40,
       WALLACE_CSA_DUMMY_OP_groupi_n_41;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_42,
       WALLACE_CSA_DUMMY_OP_groupi_n_43,
       WALLACE_CSA_DUMMY_OP_groupi_n_44,
       WALLACE_CSA_DUMMY_OP_groupi_n_45,
       WALLACE_CSA_DUMMY_OP_groupi_n_46,
       WALLACE_CSA_DUMMY_OP_groupi_n_47,
       WALLACE_CSA_DUMMY_OP_groupi_n_49,
       WALLACE_CSA_DUMMY_OP_groupi_n_50;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_51,
       WALLACE_CSA_DUMMY_OP_groupi_n_52,
       WALLACE_CSA_DUMMY_OP_groupi_n_53,
       WALLACE_CSA_DUMMY_OP_groupi_n_54,
       WALLACE_CSA_DUMMY_OP_groupi_n_55,
       WALLACE_CSA_DUMMY_OP_groupi_n_56,
       WALLACE_CSA_DUMMY_OP_groupi_n_57,
       WALLACE_CSA_DUMMY_OP_groupi_n_58;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_59,
       WALLACE_CSA_DUMMY_OP_groupi_n_61,
       WALLACE_CSA_DUMMY_OP_groupi_n_62,
       WALLACE_CSA_DUMMY_OP_groupi_n_63,
       WALLACE_CSA_DUMMY_OP_groupi_n_64,
       WALLACE_CSA_DUMMY_OP_groupi_n_65,
       WALLACE_CSA_DUMMY_OP_groupi_n_66,
       WALLACE_CSA_DUMMY_OP_groupi_n_67;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_68,
       WALLACE_CSA_DUMMY_OP_groupi_n_70,
       WALLACE_CSA_DUMMY_OP_groupi_n_71,
       WALLACE_CSA_DUMMY_OP_groupi_n_73,
       WALLACE_CSA_DUMMY_OP_groupi_n_74,
       WALLACE_CSA_DUMMY_OP_groupi_n_75,
       WALLACE_CSA_DUMMY_OP_groupi_n_78,
       WALLACE_CSA_DUMMY_OP_groupi_n_79;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179;
  CLKINVX1 g4754(.A (rst), .Y (n_158));
  NAND3X1 g5499__2398(.A (n_133), .B (n_148), .C (n_138), .Y (n_174));
  NAND3X1 g5500__5107(.A (n_135), .B (n_150), .C (n_136), .Y (n_173));
  NAND3X1 g5501__6260(.A (n_128), .B (n_155), .C (n_154), .Y (n_177));
  OR2X1 g5502__4319(.A (n_152), .B (n_157), .Y (n_178));
  NAND3X1 g5503__8428(.A (n_129), .B (n_146), .C (n_153), .Y (n_175));
  OR2X1 g5504__5526(.A (n_147), .B (n_156), .Y (n_172));
  NAND3X1 g5505__6783(.A (n_134), .B (n_151), .C (n_139), .Y (n_179));
  NAND3X1 g5506__3680(.A (n_137), .B (n_149), .C (n_132), .Y (n_176));
  OAI211XL g5507__1617(.A0 (n_100), .A1 (n_84), .B0 (n_126), .C0
       (n_130), .Y (n_157));
  OAI211X1 g5508__2802(.A0 (n_82), .A1 (n_107), .B0 (n_131), .C0
       (n_127), .Y (n_156));
  AOI21X1 g5509__1705(.A0 (A[14]), .A1 (n_103), .B0 (n_141), .Y
       (n_155));
  AOI222XL g5510__5122(.A0 (A[6]), .A1 (n_106), .B0 (A[10]), .B1
       (n_98), .C0 (n_104), .C1 (A[26]), .Y (n_154));
  AOI222XL g5511__8246(.A0 (B[12]), .A1 (n_99), .B0 (B[24]), .B1
       (n_105), .C0 (n_109), .C1 (B[0]), .Y (n_153));
  OAI211X1 g5512__7098(.A0 (n_81), .A1 (n_102), .B0 (n_118), .C0
       (n_114), .Y (n_152));
  AOI21X1 g5513__6131(.A0 (A[12]), .A1 (n_103), .B0 (n_144), .Y
       (n_151));
  AOI21X1 g5514__1881(.A0 (B[10]), .A1 (n_97), .B0 (n_142), .Y (n_150));
  AOI21X1 g5515__5115(.A0 (A[15]), .A1 (n_103), .B0 (n_145), .Y
       (n_149));
  AOI21X1 g5516__7482(.A0 (B[9]), .A1 (n_97), .B0 (n_143), .Y (n_148));
  OAI211X1 g5517__4733(.A0 (n_83), .A1 (n_96), .B0 (n_112), .C0
       (n_111), .Y (n_147));
  AOI21X1 g5518__6161(.A0 (B[8]), .A1 (n_97), .B0 (n_140), .Y (n_146));
  NAND2XL g5519__9315(.A (n_117), .B (n_113), .Y (n_145));
  NAND2XL g5520__9945(.A (n_120), .B (n_124), .Y (n_144));
  NAND2XL g5521__2883(.A (n_121), .B (n_119), .Y (n_143));
  NAND2XL g5522__2346(.A (n_116), .B (n_115), .Y (n_142));
  NAND2XL g5523__1666(.A (n_123), .B (n_122), .Y (n_141));
  NAND2XL g5524__7410(.A (n_110), .B (n_125), .Y (n_140));
  AOI22X1 g5525__6417(.A0 (A[0]), .A1 (n_101), .B0 (A[24]), .B1
       (n_104), .Y (n_139));
  AOI22X1 g5526__5477(.A0 (B[1]), .A1 (n_109), .B0 (B[5]), .B1 (n_108),
       .Y (n_138));
  AOI22X1 g5527__2398(.A0 (A[7]), .A1 (n_106), .B0 (A[11]), .B1 (n_98),
       .Y (n_137));
  AOI22X1 g5528__5107(.A0 (B[2]), .A1 (n_109), .B0 (B[6]), .B1 (n_108),
       .Y (n_136));
  AOI22X1 g5529__6260(.A0 (B[14]), .A1 (n_99), .B0 (B[26]), .B1
       (n_105), .Y (n_135));
  AOI22X1 g5530__4319(.A0 (A[4]), .A1 (n_106), .B0 (A[8]), .B1 (n_98),
       .Y (n_134));
  AOI22X1 g5531__8428(.A0 (B[13]), .A1 (n_99), .B0 (B[25]), .B1
       (n_105), .Y (n_133));
  AOI22X1 g5532__5526(.A0 (A[3]), .A1 (n_101), .B0 (A[27]), .B1
       (n_104), .Y (n_132));
  AOI22X1 g5533__6783(.A0 (B[15]), .A1 (n_99), .B0 (B[27]), .B1
       (n_105), .Y (n_131));
  AOI22X1 g5534__3680(.A0 (A[5]), .A1 (n_106), .B0 (A[9]), .B1 (n_98),
       .Y (n_130));
  NAND2XL g5535__1617(.A (B[4]), .B (n_108), .Y (n_129));
  NAND2XL g5536__2802(.A (A[2]), .B (n_101), .Y (n_128));
  NAND2XL g5537__1705(.A (B[3]), .B (n_109), .Y (n_127));
  NAND2XL g5538__5122(.A (A[25]), .B (n_104), .Y (n_126));
  AOI22X1 g5539__8246(.A0 (B[16]), .A1 (n_92), .B0 (B[32]), .B1 (n_95),
       .Y (n_125));
  AOI22X1 g5540__7098(.A0 (A[16]), .A1 (n_89), .B0 (A[20]), .B1 (n_90),
       .Y (n_124));
  AOI22X1 g5541__6131(.A0 (A[22]), .A1 (n_90), .B0 (A[30]), .B1 (n_91),
       .Y (n_123));
  AOI22X1 g5542__1881(.A0 (A[18]), .A1 (n_89), .B0 (A[34]), .B1 (n_87),
       .Y (n_122));
  AOI22X1 g5543__5115(.A0 (B[29]), .A1 (n_93), .B0 (B[33]), .B1 (n_95),
       .Y (n_121));
  AOI22X1 g5544__7482(.A0 (A[28]), .A1 (n_91), .B0 (A[32]), .B1 (n_87),
       .Y (n_120));
  AOI22X1 g5545__4733(.A0 (B[17]), .A1 (n_92), .B0 (B[21]), .B1 (n_94),
       .Y (n_119));
  AOI22X1 g5546__6161(.A0 (A[21]), .A1 (n_90), .B0 (A[29]), .B1 (n_91),
       .Y (n_118));
  AOI22X1 g5547__9315(.A0 (A[23]), .A1 (n_90), .B0 (A[31]), .B1 (n_91),
       .Y (n_117));
  AOI22X1 g5548__9945(.A0 (B[30]), .A1 (n_93), .B0 (B[34]), .B1 (n_95),
       .Y (n_116));
  AOI22X1 g5549__2883(.A0 (B[18]), .A1 (n_92), .B0 (B[22]), .B1 (n_94),
       .Y (n_115));
  AOI22X1 g5550__2346(.A0 (A[17]), .A1 (n_89), .B0 (A[33]), .B1 (n_87),
       .Y (n_114));
  AOI22X1 g5551__1666(.A0 (A[19]), .A1 (n_89), .B0 (A[35]), .B1 (n_87),
       .Y (n_113));
  AOI22X1 g5552__7410(.A0 (B[31]), .A1 (n_93), .B0 (B[35]), .B1 (n_95),
       .Y (n_112));
  AOI22X1 g5553__6417(.A0 (B[19]), .A1 (n_92), .B0 (B[23]), .B1 (n_94),
       .Y (n_111));
  AOI22X1 g5554__5477(.A0 (B[20]), .A1 (n_94), .B0 (B[28]), .B1 (n_93),
       .Y (n_110));
  CLKINVX1 g5555(.A (n_107), .Y (n_108));
  AND2X1 g5556__2398(.A (n_86), .B (n_85), .Y (n_109));
  NAND2XL g5557__5107(.A (gj[0]), .B (n_85), .Y (n_107));
  AND2X1 g5558__6260(.A (gk[0]), .B (n_88), .Y (n_106));
  NOR2BX1 g5559__4319(.AN (gk[1]), .B (n_160), .Y (n_105));
  AND2X1 g5560__8428(.A (gi[1]), .B (n_85), .Y (n_104));
  CLKINVX1 g5561(.A (n_102), .Y (n_103));
  CLKINVX1 g5562(.A (n_100), .Y (n_101));
  CLKINVX1 g5563(.A (n_96), .Y (n_97));
  NAND2XL g5564__5526(.A (gi[0]), .B (n_85), .Y (n_102));
  NAND2XL g5565__6783(.A (n_88), .B (n_85), .Y (n_100));
  AND2X1 g5566__3680(.A (gk[0]), .B (n_86), .Y (n_99));
  AND2X1 g5567__1617(.A (gk[1]), .B (n_88), .Y (n_98));
  NAND2XL g5568__2802(.A (gj[1]), .B (n_85), .Y (n_96));
  AND2X1 g5569__1705(.A (gj[1]), .B (gk[1]), .Y (n_95));
  AND2X1 g5570__5122(.A (gj[1]), .B (gk[0]), .Y (n_94));
  AND2X1 g5571__8246(.A (gj[0]), .B (gk[1]), .Y (n_93));
  AND2X1 g5572__7098(.A (gj[0]), .B (gk[0]), .Y (n_92));
  AND2X1 g5573__6131(.A (gi[1]), .B (gk[0]), .Y (n_91));
  INVXL g5574(.A (n_88), .Y (n_161));
  CLKINVX1 g5575(.A (n_86), .Y (n_160));
  AND2X1 g5576__1881(.A (gi[0]), .B (gk[1]), .Y (n_90));
  AND2X1 g5577__5115(.A (gi[0]), .B (gk[0]), .Y (n_89));
  NOR2XL g5578__7482(.A (gi[1]), .B (gi[0]), .Y (n_88));
  AND2X1 g5579__4733(.A (gi[1]), .B (gk[1]), .Y (n_87));
  NOR2XL g5580__6161(.A (gj[1]), .B (gj[0]), .Y (n_86));
  NOR2XL g5581__9315(.A (gk[1]), .B (gk[0]), .Y (n_85));
  INVX1 g5582(.A (A[1]), .Y (n_84));
  INVX1 g5583(.A (B[11]), .Y (n_83));
  INVX1 g5584(.A (B[7]), .Y (n_82));
  INVX1 g5585(.A (A[13]), .Y (n_81));
  SDFFQX2 \C_reg[0] (.CK (clk), .D (C[0]), .SI (acc[7]), .SE (n_75), .Q
       (C[0]));
  SDFFQX2 \C_reg[1] (.CK (clk), .D (C[1]), .SI (acc[6]), .SE (n_75), .Q
       (C[1]));
  SDFFQX2 \C_reg[2] (.CK (clk), .D (C[2]), .SI (acc[5]), .SE (n_75), .Q
       (C[2]));
  SDFFQX2 \C_reg[3] (.CK (clk), .D (C[3]), .SI (acc[4]), .SE (n_75), .Q
       (C[3]));
  SDFFQX2 \C_reg[4] (.CK (clk), .D (C[4]), .SI (acc[3]), .SE (n_75), .Q
       (C[4]));
  SDFFQX2 \C_reg[5] (.CK (clk), .D (C[5]), .SI (acc[2]), .SE (n_75), .Q
       (C[5]));
  SDFFQX2 \C_reg[6] (.CK (clk), .D (C[6]), .SI (acc[1]), .SE (n_75), .Q
       (C[6]));
  SDFFQX2 \C_reg[7] (.CK (clk), .D (C[7]), .SI (acc[0]), .SE (n_75), .Q
       (C[7]));
  SDFFQX2 \C_reg[8] (.CK (clk), .D (acc[7]), .SI (C[8]), .SE (n_76), .Q
       (C[8]));
  SDFFQX2 \C_reg[9] (.CK (clk), .D (acc[6]), .SI (C[9]), .SE (n_76), .Q
       (C[9]));
  SDFFQX2 \C_reg[10] (.CK (clk), .D (acc[5]), .SI (C[10]), .SE (n_76),
       .Q (C[10]));
  SDFFQX2 \C_reg[11] (.CK (clk), .D (acc[4]), .SI (C[11]), .SE (n_76),
       .Q (C[11]));
  SDFFQX2 \C_reg[12] (.CK (clk), .D (acc[3]), .SI (C[12]), .SE (n_76),
       .Q (C[12]));
  SDFFQX2 \C_reg[13] (.CK (clk), .D (acc[2]), .SI (C[13]), .SE (n_76),
       .Q (C[13]));
  SDFFQX2 \C_reg[14] (.CK (clk), .D (acc[1]), .SI (C[14]), .SE (n_76),
       .Q (C[14]));
  SDFFQX2 \C_reg[15] (.CK (clk), .D (acc[0]), .SI (C[15]), .SE (n_76),
       .Q (C[15]));
  SDFFQX2 \C_reg[16] (.CK (clk), .D (acc[7]), .SI (C[16]), .SE (n_73),
       .Q (C[16]));
  SDFFQX2 \C_reg[17] (.CK (clk), .D (acc[6]), .SI (C[17]), .SE (n_73),
       .Q (C[17]));
  SDFFQX2 \C_reg[18] (.CK (clk), .D (acc[5]), .SI (C[18]), .SE (n_73),
       .Q (C[18]));
  SDFFQX2 \C_reg[19] (.CK (clk), .D (acc[4]), .SI (C[19]), .SE (n_73),
       .Q (C[19]));
  SDFFQX2 \C_reg[20] (.CK (clk), .D (acc[3]), .SI (C[20]), .SE (n_73),
       .Q (C[20]));
  SDFFQX2 \C_reg[21] (.CK (clk), .D (acc[2]), .SI (C[21]), .SE (n_73),
       .Q (C[21]));
  SDFFQX2 \C_reg[22] (.CK (clk), .D (acc[1]), .SI (C[22]), .SE (n_73),
       .Q (C[22]));
  SDFFQX2 \C_reg[23] (.CK (clk), .D (acc[0]), .SI (C[23]), .SE (n_73),
       .Q (C[23]));
  SDFFQX2 \C_reg[24] (.CK (clk), .D (acc[7]), .SI (C[24]), .SE (n_59),
       .Q (C[24]));
  SDFFQX2 \C_reg[25] (.CK (clk), .D (acc[6]), .SI (C[25]), .SE (n_59),
       .Q (C[25]));
  SDFFQX2 \C_reg[26] (.CK (clk), .D (acc[5]), .SI (C[26]), .SE (n_59),
       .Q (C[26]));
  SDFFQX2 \C_reg[27] (.CK (clk), .D (acc[4]), .SI (C[27]), .SE (n_59),
       .Q (C[27]));
  SDFFQX2 \C_reg[28] (.CK (clk), .D (acc[3]), .SI (C[28]), .SE (n_59),
       .Q (C[28]));
  SDFFQX2 \C_reg[29] (.CK (clk), .D (acc[2]), .SI (C[29]), .SE (n_59),
       .Q (C[29]));
  SDFFQX2 \C_reg[30] (.CK (clk), .D (acc[1]), .SI (C[30]), .SE (n_59),
       .Q (C[30]));
  SDFFQX2 \C_reg[31] (.CK (clk), .D (acc[0]), .SI (C[31]), .SE (n_59),
       .Q (C[31]));
  SDFFQX2 \C_reg[32] (.CK (clk), .D (acc[7]), .SI (C[32]), .SE (n_55),
       .Q (C[32]));
  SDFFQX2 \C_reg[33] (.CK (clk), .D (acc[6]), .SI (C[33]), .SE (n_55),
       .Q (C[33]));
  SDFFQX2 \C_reg[34] (.CK (clk), .D (acc[5]), .SI (C[34]), .SE (n_55),
       .Q (C[34]));
  SDFFQX2 \C_reg[35] (.CK (clk), .D (acc[4]), .SI (C[35]), .SE (n_55),
       .Q (C[35]));
  SDFFQX2 \C_reg[36] (.CK (clk), .D (acc[3]), .SI (C[36]), .SE (n_55),
       .Q (C[36]));
  SDFFQX2 \C_reg[37] (.CK (clk), .D (acc[2]), .SI (C[37]), .SE (n_55),
       .Q (C[37]));
  SDFFQX2 \C_reg[38] (.CK (clk), .D (acc[1]), .SI (C[38]), .SE (n_55),
       .Q (C[38]));
  SDFFQX2 \C_reg[39] (.CK (clk), .D (acc[0]), .SI (C[39]), .SE (n_55),
       .Q (C[39]));
  SDFFQX2 \C_reg[40] (.CK (clk), .D (acc[7]), .SI (C[40]), .SE (n_57),
       .Q (C[40]));
  SDFFQX2 \C_reg[41] (.CK (clk), .D (acc[6]), .SI (C[41]), .SE (n_57),
       .Q (C[41]));
  SDFFQX2 \C_reg[42] (.CK (clk), .D (acc[5]), .SI (C[42]), .SE (n_57),
       .Q (C[42]));
  SDFFQX2 \C_reg[43] (.CK (clk), .D (acc[4]), .SI (C[43]), .SE (n_57),
       .Q (C[43]));
  SDFFQX2 \C_reg[44] (.CK (clk), .D (acc[3]), .SI (C[44]), .SE (n_57),
       .Q (C[44]));
  SDFFQX2 \C_reg[45] (.CK (clk), .D (acc[2]), .SI (C[45]), .SE (n_57),
       .Q (C[45]));
  SDFFQX2 \C_reg[46] (.CK (clk), .D (acc[1]), .SI (C[46]), .SE (n_57),
       .Q (C[46]));
  SDFFQX2 \C_reg[47] (.CK (clk), .D (acc[0]), .SI (C[47]), .SE (n_57),
       .Q (C[47]));
  SDFFQX2 \C_reg[48] (.CK (clk), .D (C[48]), .SI (acc[7]), .SE (n_74),
       .Q (C[48]));
  SDFFQX2 \C_reg[49] (.CK (clk), .D (C[49]), .SI (acc[6]), .SE (n_74),
       .Q (C[49]));
  SDFFQX2 \C_reg[50] (.CK (clk), .D (C[50]), .SI (acc[5]), .SE (n_74),
       .Q (C[50]));
  SDFFQX2 \C_reg[51] (.CK (clk), .D (C[51]), .SI (acc[4]), .SE (n_74),
       .Q (C[51]));
  SDFFQX2 \C_reg[52] (.CK (clk), .D (C[52]), .SI (acc[3]), .SE (n_74),
       .Q (C[52]));
  SDFFQX2 \C_reg[53] (.CK (clk), .D (C[53]), .SI (acc[2]), .SE (n_74),
       .Q (C[53]));
  SDFFQX2 \C_reg[54] (.CK (clk), .D (C[54]), .SI (acc[1]), .SE (n_74),
       .Q (C[54]));
  SDFFQX2 \C_reg[55] (.CK (clk), .D (C[55]), .SI (acc[0]), .SE (n_74),
       .Q (C[55]));
  SDFFQX2 \C_reg[56] (.CK (clk), .D (acc[7]), .SI (C[56]), .SE (n_46),
       .Q (C[56]));
  SDFFQX2 \C_reg[57] (.CK (clk), .D (acc[6]), .SI (C[57]), .SE (n_46),
       .Q (C[57]));
  SDFFQX2 \C_reg[58] (.CK (clk), .D (acc[5]), .SI (C[58]), .SE (n_46),
       .Q (C[58]));
  SDFFQX2 \C_reg[59] (.CK (clk), .D (acc[4]), .SI (C[59]), .SE (n_46),
       .Q (C[59]));
  SDFFQX2 \C_reg[60] (.CK (clk), .D (acc[3]), .SI (C[60]), .SE (n_46),
       .Q (C[60]));
  SDFFQX2 \C_reg[61] (.CK (clk), .D (acc[2]), .SI (C[61]), .SE (n_46),
       .Q (C[61]));
  SDFFQX2 \C_reg[62] (.CK (clk), .D (acc[1]), .SI (C[62]), .SE (n_46),
       .Q (C[62]));
  SDFFQX2 \C_reg[63] (.CK (clk), .D (acc[0]), .SI (C[63]), .SE (n_46),
       .Q (C[63]));
  SDFFQX2 \C_reg[64] (.CK (clk), .D (acc[7]), .SI (C[64]), .SE (n_58),
       .Q (C[64]));
  SDFFQX2 \C_reg[65] (.CK (clk), .D (acc[6]), .SI (C[65]), .SE (n_58),
       .Q (C[65]));
  SDFFQX2 \C_reg[66] (.CK (clk), .D (acc[5]), .SI (C[66]), .SE (n_58),
       .Q (C[66]));
  SDFFQX2 \C_reg[67] (.CK (clk), .D (acc[4]), .SI (C[67]), .SE (n_58),
       .Q (C[67]));
  SDFFQX2 \C_reg[68] (.CK (clk), .D (acc[3]), .SI (C[68]), .SE (n_58),
       .Q (C[68]));
  SDFFQX2 \C_reg[69] (.CK (clk), .D (acc[2]), .SI (C[69]), .SE (n_58),
       .Q (C[69]));
  SDFFQX2 \C_reg[70] (.CK (clk), .D (acc[1]), .SI (C[70]), .SE (n_58),
       .Q (C[70]));
  SDFFQX2 \C_reg[71] (.CK (clk), .D (acc[0]), .SI (C[71]), .SE (n_58),
       .Q (C[71]));
  DFFRHQX1 \acc_reg[1] (.RN (n_158), .CK (clk), .D (n_69), .Q (acc[1]));
  DFFRHQX1 \acc_reg[2] (.RN (n_158), .CK (clk), .D (n_68), .Q (acc[2]));
  DFFRHQX1 \acc_reg[3] (.RN (n_158), .CK (clk), .D (n_64), .Q (acc[3]));
  DFFRHQX1 \acc_reg[4] (.RN (n_158), .CK (clk), .D (n_67), .Q (acc[4]));
  DFFRHQX1 \acc_reg[5] (.RN (n_158), .CK (clk), .D (n_65), .Q (acc[5]));
  DFFRHQX1 \acc_reg[6] (.RN (n_158), .CK (clk), .D (n_66), .Q (acc[6]));
  DFFRHQX1 \acc_reg[7] (.RN (n_158), .CK (clk), .D (n_63), .Q (acc[7]));
  SDFFRHQX1 \gi_reg[0] (.RN (n_158), .CK (clk), .D (n_3), .SI (n_37),
       .SE (n_42), .Q (gi[0]));
  SDFFRHQX1 \gk_reg[0] (.RN (n_158), .CK (clk), .D (gk[0]), .SI (n_38),
       .SE (n_56), .Q (gk[0]));
  AOI22X1 g7303__9945(.A0 (n_79), .A1 (n_78), .B0 (PS[0]), .B1 (n_16),
       .Y (n_80));
  NOR4BX1 g7364__2883(.AN (n_27), .B (n_26), .C (n_54), .D (n_52), .Y
       (n_79));
  NOR3BX1 g7365__2346(.AN (n_19), .B (n_51), .C (n_72), .Y (n_78));
  OAI21X1 g7366__1666(.A0 (n_6), .A1 (n_56), .B0 (n_34), .Y (n_77));
  NAND4XL g7375__7410(.A (n_35), .B (n_36), .C (n_25), .D (n_47), .Y
       (n_72));
  OAI22X1 g7376__6417(.A0 (n_2), .A1 (n_50), .B0 (n_160), .B1 (n_11),
       .Y (n_71));
  NAND2XL g7379__5477(.A (n_10), .B (n_61), .Y (n_76));
  NOR2XL g7380__2398(.A (n_160), .B (n_60), .Y (n_75));
  NOR3X1 g7381__5107(.A (n_44), .B (n_41), .C (n_40), .Y (n_74));
  NAND2XL g7382__6260(.A (n_14), .B (n_61), .Y (n_73));
  OAI22X1 g7383__4319(.A0 (n_4), .A1 (n_50), .B0 (n_9), .B1 (n_11), .Y
       (n_70));
  AO22XL g7384__8428(.A0 (acc[1]), .A1 (n_48), .B0 (n_8), .B1 (n_163),
       .Y (n_69));
  AO22XL g7385__5526(.A0 (acc[2]), .A1 (n_48), .B0 (n_8), .B1 (n_164),
       .Y (n_68));
  AO22XL g7386__6783(.A0 (acc[4]), .A1 (n_48), .B0 (n_8), .B1 (n_166),
       .Y (n_67));
  AO22XL g7387__3680(.A0 (acc[6]), .A1 (n_48), .B0 (n_8), .B1 (n_168),
       .Y (n_66));
  AO22XL g7388__1617(.A0 (acc[5]), .A1 (n_48), .B0 (n_8), .B1 (n_167),
       .Y (n_65));
  AO22XL g7389__2802(.A0 (acc[3]), .A1 (n_48), .B0 (n_8), .B1 (n_165),
       .Y (n_64));
  AO22XL g7390__1705(.A0 (acc[7]), .A1 (n_48), .B0 (n_8), .B1 (n_169),
       .Y (n_63));
  AO22XL g7391__5122(.A0 (acc[0]), .A1 (n_48), .B0 (n_8), .B1 (n_162),
       .Y (n_62));
  CLKINVX1 g7392(.A (n_60), .Y (n_61));
  NAND2XL g7393__8246(.A (n_3), .B (n_49), .Y (n_60));
  NAND2XL g7395__7098(.A (n_45), .B (n_49), .Y (n_59));
  NAND4BBX1 g7396__6131(.AN (n_41), .BN (n_40), .C (gi[1]), .D (n_14),
       .Y (n_58));
  NAND3X1 g7397__1881(.A (gi[0]), .B (n_14), .C (n_49), .Y (n_57));
  NAND4XL g7398__5115(.A (n_23), .B (n_30), .C (n_29), .D (n_28), .Y
       (n_54));
  OAI22X1 g7399__7482(.A0 (n_41), .A1 (n_42), .B0 (n_0), .B1 (n_19), .Y
       (n_53));
  NAND4XL g7400__4733(.A (n_15), .B (n_39), .C (n_31), .D (n_22), .Y
       (n_52));
  NAND4XL g7401__6161(.A (n_24), .B (n_21), .C (n_20), .D (n_32), .Y
       (n_51));
  AOI21X1 g7402__9315(.A0 (gk[1]), .A1 (PS[0]), .B0 (n_48), .Y (n_56));
  NAND3X1 g7403__9945(.A (gi[0]), .B (n_10), .C (n_49), .Y (n_55));
  NOR4BX1 g7404__2883(.AN (n_33), .B (A[34]), .C (B[3]), .D (B[7]), .Y
       (n_47));
  AOI21X1 g7405__2346(.A0 (n_17), .A1 (PS[1]), .B0 (PS[0]), .Y (n_50));
  NOR2XL g7406__1666(.A (gi[1]), .B (n_40), .Y (n_49));
  AOI21X1 g7407__7410(.A0 (n_18), .A1 (n_1), .B0 (n_5), .Y (n_48));
  AOI221X1 g7408__6417(.A0 (n_2), .A1 (n_3), .B0 (gj[1]), .B1 (gi[0]),
       .C0 (n_10), .Y (n_45));
  OAI221X1 g7409__5477(.A0 (gi[1]), .A1 (gj[1]), .B0 (n_2), .B1 (n_0),
       .C0 (n_13), .Y (n_44));
  OAI22X1 g7410__2398(.A0 (n_18), .A1 (n_11), .B0 (n_6), .B1 (n_7), .Y
       (n_43));
  OR4X1 g7411__5107(.A (gi[0]), .B (n_0), .C (n_9), .D (n_40), .Y
       (n_46));
  NOR3X1 g7412__6260(.A (A[0]), .B (A[2]), .C (B[31]), .Y (n_39));
  NOR2XL g7413__4319(.A (gk[0]), .B (n_7), .Y (n_38));
  NOR2XL g7414__8428(.A (n_3), .B (n_19), .Y (n_37));
  NOR4X1 g7415__5526(.A (B[19]), .B (B[27]), .C (A[5]), .D (B[30]), .Y
       (n_36));
  NOR4X1 g7416__6783(.A (A[14]), .B (A[30]), .C (A[7]), .D (B[23]), .Y
       (n_35));
  NAND2XL g7417__3680(.A (gk[0]), .B (n_8), .Y (n_34));
  NOR4X1 g7418__1617(.A (A[3]), .B (A[11]), .C (A[18]), .D (A[26]), .Y
       (n_33));
  NOR4X1 g7419__2802(.A (B[21]), .B (B[25]), .C (B[28]), .D (B[32]), .Y
       (n_32));
  NAND3X1 g7420__1705(.A (gj[1]), .B (n_0), .C (n_12), .Y (n_42));
  OAI21X1 g7421__5122(.A0 (n_0), .A1 (n_3), .B0 (n_161), .Y (n_41));
  NAND2XL g7422__8246(.A (n_158), .B (n_12), .Y (n_40));
  NOR4X1 g7423__7098(.A (A[4]), .B (A[6]), .C (A[8]), .D (A[9]), .Y
       (n_31));
  NOR4X1 g7424__6131(.A (A[35]), .B (B[0]), .C (B[2]), .D (B[4]), .Y
       (n_30));
  NOR4X1 g7425__1881(.A (A[27]), .B (A[29]), .C (A[31]), .D (A[33]), .Y
       (n_29));
  NOR4X1 g7426__5115(.A (B[6]), .B (B[8]), .C (B[10]), .D (B[12]), .Y
       (n_28));
  NOR4X1 g7427__7482(.A (B[14]), .B (B[16]), .C (B[18]), .D (B[20]), .Y
       (n_27));
  OR4XL g7428__4733(.A (B[22]), .B (B[24]), .C (B[26]), .D (B[29]), .Y
       (n_26));
  NOR4X1 g7429__6161(.A (A[22]), .B (B[11]), .C (B[15]), .D (B[34]), .Y
       (n_25));
  NOR4X1 g7430__9315(.A (A[1]), .B (A[12]), .C (A[16]), .D (A[20]), .Y
       (n_24));
  NOR4X1 g7431__9945(.A (A[19]), .B (A[21]), .C (A[23]), .D (A[25]), .Y
       (n_23));
  NOR4X1 g7432__2883(.A (A[10]), .B (A[13]), .C (A[15]), .D (A[17]), .Y
       (n_22));
  NOR4X1 g7433__2346(.A (A[24]), .B (A[28]), .C (A[32]), .D (B[1]), .Y
       (n_21));
  NOR4X1 g7434__1666(.A (B[5]), .B (B[9]), .C (B[13]), .D (B[17]), .Y
       (n_20));
  INVXL g7435(.A (n_18), .Y (n_17));
  NAND2XL g7436__7410(.A (n_6), .B (n_5), .Y (n_16));
  NOR2XL g7437__6417(.A (B[33]), .B (B[35]), .Y (n_15));
  NOR2XL g7438__5477(.A (PS[0]), .B (PS[1]), .Y (n_19));
  NAND2XL g7439__2398(.A (gj[1]), .B (gi[1]), .Y (n_18));
  INVXL g7440(.A (n_14), .Y (n_13));
  CLKINVX1 g7441(.A (n_12), .Y (n_11));
  CLKINVX1 g7442(.A (n_10), .Y (n_9));
  INVX1 g7443(.A (n_8), .Y (n_7));
  NOR2XL g7444__5107(.A (gj[0]), .B (n_4), .Y (n_14));
  NOR2XL g7445__6260(.A (PS[0]), .B (n_5), .Y (n_12));
  NOR2XL g7446__4319(.A (gj[1]), .B (n_2), .Y (n_10));
  NOR2XL g7447__8428(.A (PS[1]), .B (n_1), .Y (n_8));
  CLKINVX1 g7451(.A (gi[0]), .Y (n_3));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g841__5526(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_79), .Y (n_169));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g842__6783(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_79));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g843__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_63), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_75), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .S (n_168));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_g844(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_74), .Y (n_167));
  INVX1 WALLACE_CSA_DUMMY_OP_groupi_g845(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_75));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g846__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_62), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_74));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_g847(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_71), .Y (n_166));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g848__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_58), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_67), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_71));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_g849(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .Y (n_165));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g850__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_59), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_61), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_67), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_68));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g851__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_66));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g852__8246(.A0 (acc[7]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_57), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_64));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g853__7098(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_63));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g854__6131(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_62));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g855__1881(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_55), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_61));
  MXI2XL WALLACE_CSA_DUMMY_OP_groupi_g856__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_55), .S0
       (WALLACE_CSA_DUMMY_OP_groupi_n_52), .Y (n_164));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g857__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_58), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_59));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g858__4733(.A (acc[7]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_57));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g859__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_56));
  CLKINVX1 WALLACE_CSA_DUMMY_OP_groupi_g860(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_55));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g861__9315(.A (acc[6]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_11), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_53));
  NOR2BX1 WALLACE_CSA_DUMMY_OP_groupi_g862__9945(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_52));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g863__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_51));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g864__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_50));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g865__1666(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_49));
  OAI21XL WALLACE_CSA_DUMMY_OP_groupi_g866__7410(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .Y (n_163));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g867__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_10), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_3), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_47));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g868__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_44));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g869__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_43));
  NOR2BX1 WALLACE_CSA_DUMMY_OP_groupi_g870__5107(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_42));
  NAND2BXL WALLACE_CSA_DUMMY_OP_groupi_g871__6260(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_41));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g872__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_40));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g873__8428(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_39));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g874__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_4), .B (acc[5]), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_38));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g875__6783(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_2), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_36));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g876__3680(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_34));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g877__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_33));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g878__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_32));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g879__1705(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .Y (n_162));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g880__5122(.A0 (acc[4]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_30));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g881__8246(.A0 (acc[1]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_29));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g882__7098(.A0 (acc[3]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_28));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g883__6131(.A0 (acc[2]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_27));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g884__1881(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .B (acc[2]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_26));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g885__5115(.A (acc[4]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_25));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g886__7482(.A (acc[2]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_24));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g887__4733(.A (acc[1]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_23));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g888__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_22));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g889__9315(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .B (acc[1]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_21));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g890__9945(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .B (acc[4]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_20));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g891__2883(.A (acc[3]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_19));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g892__2346(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .B (acc[3]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_18));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g893__1666(.A (n_176), .B
       (n_173), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_17));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g894__7410(.A (n_179), .B
       (n_172), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_16));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g895__6417(.A (n_177), .B
       (n_172), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_15));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g896__5477(.A (n_178), .B
       (n_173), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_14));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g897__2398(.A (n_174), .B (n_179),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_13));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g898__5107(.A (n_175), .B
       (n_177), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_12));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g899__6260(.A (n_175), .B (n_179),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_11));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g900__4319(.A (n_174), .B
       (n_176), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_10));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g901__8428(.A (n_176), .B
       (n_172), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_9));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g902__5526(.A (n_179), .B
       (n_173), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_8));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g903__6783(.A (n_178), .B
       (n_172), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_7));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g904__3680(.A (n_174), .B
       (n_177), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_6));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g905__1617(.A (n_174), .B
       (n_178), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_5));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g906__2802(.A (n_175), .B (n_178),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_4));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g907__1705(.A (n_177), .B
       (n_173), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_3));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g908__5122(.A (n_175), .B
       (n_176), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_2));
  DFFRX1 \gk_reg[1] (.RN (n_158), .CK (clk), .D (n_77), .Q (gk[1]), .QN
       (n_6));
  DFFRX1 \PS_reg[1] (.RN (n_158), .CK (clk), .D (n_43), .Q (PS[1]), .QN
       (n_5));
  DFFRX1 \gj_reg[1] (.RN (n_158), .CK (clk), .D (n_70), .Q (gj[1]), .QN
       (n_4));
  DFFRX1 \gj_reg[0] (.RN (n_158), .CK (clk), .D (n_71), .Q (gj[0]), .QN
       (n_2));
  DFFRX1 \PS_reg[0] (.RN (n_158), .CK (clk), .D (n_80), .Q (PS[0]), .QN
       (n_1));
  DFFRX1 \gi_reg[1] (.RN (n_158), .CK (clk), .D (n_53), .Q (gi[1]), .QN
       (n_0));
  DFFRX1 \acc_reg[0] (.RN (n_158), .CK (clk), .D (n_62), .Q (acc[0]),
       .QN (WALLACE_CSA_DUMMY_OP_groupi_n_1));
endmodule

