
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 24 2026 08:28:46 IST (Mar 24 2026 02:58:46 UTC)

// Verification Directory fv/parallel 

module parallel(clk, rst, A, B, C);
  input clk, rst;
  input [0:15] A, B;
  output [0:31] C;
  wire clk, rst;
  wire [0:15] A, B;
  wire [0:31] C;
  wire [8:0] \acc[0][1][1] ;
  wire [8:0] \acc[1][0][1] ;
  wire [8:0] \acc[0][0][1] ;
  wire [8:0] \acc[1][1][1] ;
  wire WALLACE_CSA_DUMMY_OP1_groupi_n_0,
       WALLACE_CSA_DUMMY_OP1_groupi_n_1,
       WALLACE_CSA_DUMMY_OP1_groupi_n_2,
       WALLACE_CSA_DUMMY_OP1_groupi_n_3,
       WALLACE_CSA_DUMMY_OP1_groupi_n_4,
       WALLACE_CSA_DUMMY_OP1_groupi_n_5,
       WALLACE_CSA_DUMMY_OP1_groupi_n_6,
       WALLACE_CSA_DUMMY_OP1_groupi_n_7;
  wire WALLACE_CSA_DUMMY_OP1_groupi_n_8,
       WALLACE_CSA_DUMMY_OP1_groupi_n_9,
       WALLACE_CSA_DUMMY_OP1_groupi_n_10,
       WALLACE_CSA_DUMMY_OP1_groupi_n_11,
       WALLACE_CSA_DUMMY_OP1_groupi_n_12,
       WALLACE_CSA_DUMMY_OP1_groupi_n_13,
       WALLACE_CSA_DUMMY_OP1_groupi_n_14,
       WALLACE_CSA_DUMMY_OP1_groupi_n_15;
  wire WALLACE_CSA_DUMMY_OP1_groupi_n_16,
       WALLACE_CSA_DUMMY_OP1_groupi_n_17,
       WALLACE_CSA_DUMMY_OP1_groupi_n_18,
       WALLACE_CSA_DUMMY_OP1_groupi_n_19,
       WALLACE_CSA_DUMMY_OP1_groupi_n_20,
       WALLACE_CSA_DUMMY_OP1_groupi_n_21,
       WALLACE_CSA_DUMMY_OP1_groupi_n_22,
       WALLACE_CSA_DUMMY_OP1_groupi_n_23;
  wire WALLACE_CSA_DUMMY_OP1_groupi_n_24,
       WALLACE_CSA_DUMMY_OP1_groupi_n_25,
       WALLACE_CSA_DUMMY_OP1_groupi_n_26,
       WALLACE_CSA_DUMMY_OP1_groupi_n_27,
       WALLACE_CSA_DUMMY_OP1_groupi_n_28,
       WALLACE_CSA_DUMMY_OP1_groupi_n_29,
       WALLACE_CSA_DUMMY_OP1_groupi_n_30,
       WALLACE_CSA_DUMMY_OP1_groupi_n_31;
  wire WALLACE_CSA_DUMMY_OP1_groupi_n_32,
       WALLACE_CSA_DUMMY_OP1_groupi_n_33,
       WALLACE_CSA_DUMMY_OP1_groupi_n_34,
       WALLACE_CSA_DUMMY_OP1_groupi_n_35,
       WALLACE_CSA_DUMMY_OP1_groupi_n_36,
       WALLACE_CSA_DUMMY_OP1_groupi_n_37,
       WALLACE_CSA_DUMMY_OP1_groupi_n_38,
       WALLACE_CSA_DUMMY_OP1_groupi_n_39;
  wire WALLACE_CSA_DUMMY_OP1_groupi_n_40,
       WALLACE_CSA_DUMMY_OP1_groupi_n_42,
       WALLACE_CSA_DUMMY_OP1_groupi_n_43,
       WALLACE_CSA_DUMMY_OP1_groupi_n_44,
       WALLACE_CSA_DUMMY_OP1_groupi_n_45,
       WALLACE_CSA_DUMMY_OP1_groupi_n_46,
       WALLACE_CSA_DUMMY_OP1_groupi_n_47,
       WALLACE_CSA_DUMMY_OP1_groupi_n_48;
  wire WALLACE_CSA_DUMMY_OP1_groupi_n_49,
       WALLACE_CSA_DUMMY_OP1_groupi_n_50,
       WALLACE_CSA_DUMMY_OP1_groupi_n_51,
       WALLACE_CSA_DUMMY_OP1_groupi_n_52,
       WALLACE_CSA_DUMMY_OP1_groupi_n_53,
       WALLACE_CSA_DUMMY_OP1_groupi_n_54,
       WALLACE_CSA_DUMMY_OP1_groupi_n_55,
       WALLACE_CSA_DUMMY_OP1_groupi_n_56;
  wire WALLACE_CSA_DUMMY_OP1_groupi_n_57,
       WALLACE_CSA_DUMMY_OP1_groupi_n_58,
       WALLACE_CSA_DUMMY_OP1_groupi_n_59,
       WALLACE_CSA_DUMMY_OP1_groupi_n_60,
       WALLACE_CSA_DUMMY_OP1_groupi_n_61,
       WALLACE_CSA_DUMMY_OP1_groupi_n_62,
       WALLACE_CSA_DUMMY_OP1_groupi_n_63,
       WALLACE_CSA_DUMMY_OP1_groupi_n_64;
  wire WALLACE_CSA_DUMMY_OP1_groupi_n_66,
       WALLACE_CSA_DUMMY_OP1_groupi_n_67,
       WALLACE_CSA_DUMMY_OP1_groupi_n_68,
       WALLACE_CSA_DUMMY_OP1_groupi_n_69,
       WALLACE_CSA_DUMMY_OP1_groupi_n_70,
       WALLACE_CSA_DUMMY_OP1_groupi_n_71,
       WALLACE_CSA_DUMMY_OP1_groupi_n_72,
       WALLACE_CSA_DUMMY_OP1_groupi_n_73;
  wire WALLACE_CSA_DUMMY_OP1_groupi_n_74,
       WALLACE_CSA_DUMMY_OP1_groupi_n_75,
       WALLACE_CSA_DUMMY_OP1_groupi_n_76,
       WALLACE_CSA_DUMMY_OP1_groupi_n_77,
       WALLACE_CSA_DUMMY_OP1_groupi_n_79,
       WALLACE_CSA_DUMMY_OP1_groupi_n_80,
       WALLACE_CSA_DUMMY_OP1_groupi_n_81,
       WALLACE_CSA_DUMMY_OP1_groupi_n_82;
  wire WALLACE_CSA_DUMMY_OP1_groupi_n_83,
       WALLACE_CSA_DUMMY_OP1_groupi_n_84,
       WALLACE_CSA_DUMMY_OP1_groupi_n_85,
       WALLACE_CSA_DUMMY_OP1_groupi_n_86,
       WALLACE_CSA_DUMMY_OP1_groupi_n_87,
       WALLACE_CSA_DUMMY_OP1_groupi_n_88,
       WALLACE_CSA_DUMMY_OP1_groupi_n_90,
       WALLACE_CSA_DUMMY_OP1_groupi_n_91;
  wire WALLACE_CSA_DUMMY_OP1_groupi_n_93,
       WALLACE_CSA_DUMMY_OP1_groupi_n_94,
       WALLACE_CSA_DUMMY_OP1_groupi_n_96,
       WALLACE_CSA_DUMMY_OP1_groupi_n_97,
       WALLACE_CSA_DUMMY_OP1_groupi_n_99,
       WALLACE_CSA_DUMMY_OP3_groupi_n_0,
       WALLACE_CSA_DUMMY_OP3_groupi_n_1,
       WALLACE_CSA_DUMMY_OP3_groupi_n_2;
  wire WALLACE_CSA_DUMMY_OP3_groupi_n_3,
       WALLACE_CSA_DUMMY_OP3_groupi_n_4,
       WALLACE_CSA_DUMMY_OP3_groupi_n_5,
       WALLACE_CSA_DUMMY_OP3_groupi_n_6,
       WALLACE_CSA_DUMMY_OP3_groupi_n_7,
       WALLACE_CSA_DUMMY_OP3_groupi_n_8,
       WALLACE_CSA_DUMMY_OP3_groupi_n_9,
       WALLACE_CSA_DUMMY_OP3_groupi_n_10;
  wire WALLACE_CSA_DUMMY_OP3_groupi_n_11,
       WALLACE_CSA_DUMMY_OP3_groupi_n_12,
       WALLACE_CSA_DUMMY_OP3_groupi_n_13,
       WALLACE_CSA_DUMMY_OP3_groupi_n_14,
       WALLACE_CSA_DUMMY_OP3_groupi_n_15,
       WALLACE_CSA_DUMMY_OP3_groupi_n_16,
       WALLACE_CSA_DUMMY_OP3_groupi_n_17,
       WALLACE_CSA_DUMMY_OP3_groupi_n_18;
  wire WALLACE_CSA_DUMMY_OP3_groupi_n_19,
       WALLACE_CSA_DUMMY_OP3_groupi_n_20,
       WALLACE_CSA_DUMMY_OP3_groupi_n_21,
       WALLACE_CSA_DUMMY_OP3_groupi_n_22,
       WALLACE_CSA_DUMMY_OP3_groupi_n_23,
       WALLACE_CSA_DUMMY_OP3_groupi_n_24,
       WALLACE_CSA_DUMMY_OP3_groupi_n_25,
       WALLACE_CSA_DUMMY_OP3_groupi_n_26;
  wire WALLACE_CSA_DUMMY_OP3_groupi_n_27,
       WALLACE_CSA_DUMMY_OP3_groupi_n_28,
       WALLACE_CSA_DUMMY_OP3_groupi_n_29,
       WALLACE_CSA_DUMMY_OP3_groupi_n_30,
       WALLACE_CSA_DUMMY_OP3_groupi_n_31,
       WALLACE_CSA_DUMMY_OP3_groupi_n_32,
       WALLACE_CSA_DUMMY_OP3_groupi_n_33,
       WALLACE_CSA_DUMMY_OP3_groupi_n_34;
  wire WALLACE_CSA_DUMMY_OP3_groupi_n_35,
       WALLACE_CSA_DUMMY_OP3_groupi_n_36,
       WALLACE_CSA_DUMMY_OP3_groupi_n_37,
       WALLACE_CSA_DUMMY_OP3_groupi_n_38,
       WALLACE_CSA_DUMMY_OP3_groupi_n_39,
       WALLACE_CSA_DUMMY_OP3_groupi_n_40,
       WALLACE_CSA_DUMMY_OP3_groupi_n_42,
       WALLACE_CSA_DUMMY_OP3_groupi_n_43;
  wire WALLACE_CSA_DUMMY_OP3_groupi_n_44,
       WALLACE_CSA_DUMMY_OP3_groupi_n_45,
       WALLACE_CSA_DUMMY_OP3_groupi_n_46,
       WALLACE_CSA_DUMMY_OP3_groupi_n_47,
       WALLACE_CSA_DUMMY_OP3_groupi_n_48,
       WALLACE_CSA_DUMMY_OP3_groupi_n_49,
       WALLACE_CSA_DUMMY_OP3_groupi_n_50,
       WALLACE_CSA_DUMMY_OP3_groupi_n_51;
  wire WALLACE_CSA_DUMMY_OP3_groupi_n_52,
       WALLACE_CSA_DUMMY_OP3_groupi_n_53,
       WALLACE_CSA_DUMMY_OP3_groupi_n_54,
       WALLACE_CSA_DUMMY_OP3_groupi_n_55,
       WALLACE_CSA_DUMMY_OP3_groupi_n_56,
       WALLACE_CSA_DUMMY_OP3_groupi_n_57,
       WALLACE_CSA_DUMMY_OP3_groupi_n_58,
       WALLACE_CSA_DUMMY_OP3_groupi_n_59;
  wire WALLACE_CSA_DUMMY_OP3_groupi_n_60,
       WALLACE_CSA_DUMMY_OP3_groupi_n_61,
       WALLACE_CSA_DUMMY_OP3_groupi_n_62,
       WALLACE_CSA_DUMMY_OP3_groupi_n_63,
       WALLACE_CSA_DUMMY_OP3_groupi_n_64,
       WALLACE_CSA_DUMMY_OP3_groupi_n_66,
       WALLACE_CSA_DUMMY_OP3_groupi_n_67,
       WALLACE_CSA_DUMMY_OP3_groupi_n_68;
  wire WALLACE_CSA_DUMMY_OP3_groupi_n_69,
       WALLACE_CSA_DUMMY_OP3_groupi_n_70,
       WALLACE_CSA_DUMMY_OP3_groupi_n_71,
       WALLACE_CSA_DUMMY_OP3_groupi_n_72,
       WALLACE_CSA_DUMMY_OP3_groupi_n_73,
       WALLACE_CSA_DUMMY_OP3_groupi_n_74,
       WALLACE_CSA_DUMMY_OP3_groupi_n_75,
       WALLACE_CSA_DUMMY_OP3_groupi_n_76;
  wire WALLACE_CSA_DUMMY_OP3_groupi_n_77,
       WALLACE_CSA_DUMMY_OP3_groupi_n_79,
       WALLACE_CSA_DUMMY_OP3_groupi_n_80,
       WALLACE_CSA_DUMMY_OP3_groupi_n_81,
       WALLACE_CSA_DUMMY_OP3_groupi_n_82,
       WALLACE_CSA_DUMMY_OP3_groupi_n_83,
       WALLACE_CSA_DUMMY_OP3_groupi_n_84,
       WALLACE_CSA_DUMMY_OP3_groupi_n_85;
  wire WALLACE_CSA_DUMMY_OP3_groupi_n_86,
       WALLACE_CSA_DUMMY_OP3_groupi_n_87,
       WALLACE_CSA_DUMMY_OP3_groupi_n_88,
       WALLACE_CSA_DUMMY_OP3_groupi_n_90,
       WALLACE_CSA_DUMMY_OP3_groupi_n_91,
       WALLACE_CSA_DUMMY_OP3_groupi_n_93,
       WALLACE_CSA_DUMMY_OP3_groupi_n_94,
       WALLACE_CSA_DUMMY_OP3_groupi_n_96;
  wire WALLACE_CSA_DUMMY_OP3_groupi_n_97,
       WALLACE_CSA_DUMMY_OP3_groupi_n_99,
       WALLACE_CSA_DUMMY_OP5_groupi_n_0,
       WALLACE_CSA_DUMMY_OP5_groupi_n_1,
       WALLACE_CSA_DUMMY_OP5_groupi_n_2,
       WALLACE_CSA_DUMMY_OP5_groupi_n_3,
       WALLACE_CSA_DUMMY_OP5_groupi_n_4,
       WALLACE_CSA_DUMMY_OP5_groupi_n_5;
  wire WALLACE_CSA_DUMMY_OP5_groupi_n_6,
       WALLACE_CSA_DUMMY_OP5_groupi_n_7,
       WALLACE_CSA_DUMMY_OP5_groupi_n_8,
       WALLACE_CSA_DUMMY_OP5_groupi_n_9,
       WALLACE_CSA_DUMMY_OP5_groupi_n_10,
       WALLACE_CSA_DUMMY_OP5_groupi_n_11,
       WALLACE_CSA_DUMMY_OP5_groupi_n_12,
       WALLACE_CSA_DUMMY_OP5_groupi_n_13;
  wire WALLACE_CSA_DUMMY_OP5_groupi_n_14,
       WALLACE_CSA_DUMMY_OP5_groupi_n_15,
       WALLACE_CSA_DUMMY_OP5_groupi_n_16,
       WALLACE_CSA_DUMMY_OP5_groupi_n_17,
       WALLACE_CSA_DUMMY_OP5_groupi_n_18,
       WALLACE_CSA_DUMMY_OP5_groupi_n_19,
       WALLACE_CSA_DUMMY_OP5_groupi_n_20,
       WALLACE_CSA_DUMMY_OP5_groupi_n_21;
  wire WALLACE_CSA_DUMMY_OP5_groupi_n_22,
       WALLACE_CSA_DUMMY_OP5_groupi_n_23,
       WALLACE_CSA_DUMMY_OP5_groupi_n_24,
       WALLACE_CSA_DUMMY_OP5_groupi_n_25,
       WALLACE_CSA_DUMMY_OP5_groupi_n_26,
       WALLACE_CSA_DUMMY_OP5_groupi_n_27,
       WALLACE_CSA_DUMMY_OP5_groupi_n_28,
       WALLACE_CSA_DUMMY_OP5_groupi_n_29;
  wire WALLACE_CSA_DUMMY_OP5_groupi_n_30,
       WALLACE_CSA_DUMMY_OP5_groupi_n_31,
       WALLACE_CSA_DUMMY_OP5_groupi_n_32,
       WALLACE_CSA_DUMMY_OP5_groupi_n_33,
       WALLACE_CSA_DUMMY_OP5_groupi_n_34,
       WALLACE_CSA_DUMMY_OP5_groupi_n_35,
       WALLACE_CSA_DUMMY_OP5_groupi_n_36,
       WALLACE_CSA_DUMMY_OP5_groupi_n_37;
  wire WALLACE_CSA_DUMMY_OP5_groupi_n_38,
       WALLACE_CSA_DUMMY_OP5_groupi_n_39,
       WALLACE_CSA_DUMMY_OP5_groupi_n_40,
       WALLACE_CSA_DUMMY_OP5_groupi_n_42,
       WALLACE_CSA_DUMMY_OP5_groupi_n_43,
       WALLACE_CSA_DUMMY_OP5_groupi_n_44,
       WALLACE_CSA_DUMMY_OP5_groupi_n_45,
       WALLACE_CSA_DUMMY_OP5_groupi_n_46;
  wire WALLACE_CSA_DUMMY_OP5_groupi_n_47,
       WALLACE_CSA_DUMMY_OP5_groupi_n_48,
       WALLACE_CSA_DUMMY_OP5_groupi_n_49,
       WALLACE_CSA_DUMMY_OP5_groupi_n_50,
       WALLACE_CSA_DUMMY_OP5_groupi_n_51,
       WALLACE_CSA_DUMMY_OP5_groupi_n_52,
       WALLACE_CSA_DUMMY_OP5_groupi_n_53,
       WALLACE_CSA_DUMMY_OP5_groupi_n_54;
  wire WALLACE_CSA_DUMMY_OP5_groupi_n_55,
       WALLACE_CSA_DUMMY_OP5_groupi_n_56,
       WALLACE_CSA_DUMMY_OP5_groupi_n_57,
       WALLACE_CSA_DUMMY_OP5_groupi_n_58,
       WALLACE_CSA_DUMMY_OP5_groupi_n_59,
       WALLACE_CSA_DUMMY_OP5_groupi_n_60,
       WALLACE_CSA_DUMMY_OP5_groupi_n_61,
       WALLACE_CSA_DUMMY_OP5_groupi_n_62;
  wire WALLACE_CSA_DUMMY_OP5_groupi_n_63,
       WALLACE_CSA_DUMMY_OP5_groupi_n_64,
       WALLACE_CSA_DUMMY_OP5_groupi_n_66,
       WALLACE_CSA_DUMMY_OP5_groupi_n_67,
       WALLACE_CSA_DUMMY_OP5_groupi_n_68,
       WALLACE_CSA_DUMMY_OP5_groupi_n_69,
       WALLACE_CSA_DUMMY_OP5_groupi_n_70,
       WALLACE_CSA_DUMMY_OP5_groupi_n_71;
  wire WALLACE_CSA_DUMMY_OP5_groupi_n_72,
       WALLACE_CSA_DUMMY_OP5_groupi_n_73,
       WALLACE_CSA_DUMMY_OP5_groupi_n_74,
       WALLACE_CSA_DUMMY_OP5_groupi_n_75,
       WALLACE_CSA_DUMMY_OP5_groupi_n_76,
       WALLACE_CSA_DUMMY_OP5_groupi_n_77,
       WALLACE_CSA_DUMMY_OP5_groupi_n_79,
       WALLACE_CSA_DUMMY_OP5_groupi_n_80;
  wire WALLACE_CSA_DUMMY_OP5_groupi_n_81,
       WALLACE_CSA_DUMMY_OP5_groupi_n_82,
       WALLACE_CSA_DUMMY_OP5_groupi_n_83,
       WALLACE_CSA_DUMMY_OP5_groupi_n_84,
       WALLACE_CSA_DUMMY_OP5_groupi_n_85,
       WALLACE_CSA_DUMMY_OP5_groupi_n_86,
       WALLACE_CSA_DUMMY_OP5_groupi_n_87,
       WALLACE_CSA_DUMMY_OP5_groupi_n_88;
  wire WALLACE_CSA_DUMMY_OP5_groupi_n_90,
       WALLACE_CSA_DUMMY_OP5_groupi_n_91,
       WALLACE_CSA_DUMMY_OP5_groupi_n_93,
       WALLACE_CSA_DUMMY_OP5_groupi_n_94,
       WALLACE_CSA_DUMMY_OP5_groupi_n_96,
       WALLACE_CSA_DUMMY_OP5_groupi_n_97,
       WALLACE_CSA_DUMMY_OP5_groupi_n_99,
       WALLACE_CSA_DUMMY_OP_groupi_n_0;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_1,
       WALLACE_CSA_DUMMY_OP_groupi_n_2,
       WALLACE_CSA_DUMMY_OP_groupi_n_3,
       WALLACE_CSA_DUMMY_OP_groupi_n_4,
       WALLACE_CSA_DUMMY_OP_groupi_n_5,
       WALLACE_CSA_DUMMY_OP_groupi_n_6,
       WALLACE_CSA_DUMMY_OP_groupi_n_7, WALLACE_CSA_DUMMY_OP_groupi_n_8;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_9,
       WALLACE_CSA_DUMMY_OP_groupi_n_10,
       WALLACE_CSA_DUMMY_OP_groupi_n_11,
       WALLACE_CSA_DUMMY_OP_groupi_n_12,
       WALLACE_CSA_DUMMY_OP_groupi_n_13,
       WALLACE_CSA_DUMMY_OP_groupi_n_14,
       WALLACE_CSA_DUMMY_OP_groupi_n_15,
       WALLACE_CSA_DUMMY_OP_groupi_n_16;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_17,
       WALLACE_CSA_DUMMY_OP_groupi_n_18,
       WALLACE_CSA_DUMMY_OP_groupi_n_19,
       WALLACE_CSA_DUMMY_OP_groupi_n_20,
       WALLACE_CSA_DUMMY_OP_groupi_n_21,
       WALLACE_CSA_DUMMY_OP_groupi_n_22,
       WALLACE_CSA_DUMMY_OP_groupi_n_23,
       WALLACE_CSA_DUMMY_OP_groupi_n_24;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_25,
       WALLACE_CSA_DUMMY_OP_groupi_n_26,
       WALLACE_CSA_DUMMY_OP_groupi_n_27,
       WALLACE_CSA_DUMMY_OP_groupi_n_28,
       WALLACE_CSA_DUMMY_OP_groupi_n_29,
       WALLACE_CSA_DUMMY_OP_groupi_n_30,
       WALLACE_CSA_DUMMY_OP_groupi_n_31,
       WALLACE_CSA_DUMMY_OP_groupi_n_32;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_33,
       WALLACE_CSA_DUMMY_OP_groupi_n_34,
       WALLACE_CSA_DUMMY_OP_groupi_n_35,
       WALLACE_CSA_DUMMY_OP_groupi_n_36,
       WALLACE_CSA_DUMMY_OP_groupi_n_37,
       WALLACE_CSA_DUMMY_OP_groupi_n_38,
       WALLACE_CSA_DUMMY_OP_groupi_n_39,
       WALLACE_CSA_DUMMY_OP_groupi_n_40;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_42,
       WALLACE_CSA_DUMMY_OP_groupi_n_43,
       WALLACE_CSA_DUMMY_OP_groupi_n_44,
       WALLACE_CSA_DUMMY_OP_groupi_n_45,
       WALLACE_CSA_DUMMY_OP_groupi_n_46,
       WALLACE_CSA_DUMMY_OP_groupi_n_47,
       WALLACE_CSA_DUMMY_OP_groupi_n_48,
       WALLACE_CSA_DUMMY_OP_groupi_n_49;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_50,
       WALLACE_CSA_DUMMY_OP_groupi_n_51,
       WALLACE_CSA_DUMMY_OP_groupi_n_52,
       WALLACE_CSA_DUMMY_OP_groupi_n_53,
       WALLACE_CSA_DUMMY_OP_groupi_n_54,
       WALLACE_CSA_DUMMY_OP_groupi_n_55,
       WALLACE_CSA_DUMMY_OP_groupi_n_56,
       WALLACE_CSA_DUMMY_OP_groupi_n_57;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_58,
       WALLACE_CSA_DUMMY_OP_groupi_n_59,
       WALLACE_CSA_DUMMY_OP_groupi_n_60,
       WALLACE_CSA_DUMMY_OP_groupi_n_61,
       WALLACE_CSA_DUMMY_OP_groupi_n_62,
       WALLACE_CSA_DUMMY_OP_groupi_n_63,
       WALLACE_CSA_DUMMY_OP_groupi_n_64,
       WALLACE_CSA_DUMMY_OP_groupi_n_66;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_67,
       WALLACE_CSA_DUMMY_OP_groupi_n_68,
       WALLACE_CSA_DUMMY_OP_groupi_n_69,
       WALLACE_CSA_DUMMY_OP_groupi_n_70,
       WALLACE_CSA_DUMMY_OP_groupi_n_71,
       WALLACE_CSA_DUMMY_OP_groupi_n_72,
       WALLACE_CSA_DUMMY_OP_groupi_n_73,
       WALLACE_CSA_DUMMY_OP_groupi_n_74;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_75,
       WALLACE_CSA_DUMMY_OP_groupi_n_76,
       WALLACE_CSA_DUMMY_OP_groupi_n_77,
       WALLACE_CSA_DUMMY_OP_groupi_n_79,
       WALLACE_CSA_DUMMY_OP_groupi_n_80,
       WALLACE_CSA_DUMMY_OP_groupi_n_81,
       WALLACE_CSA_DUMMY_OP_groupi_n_82,
       WALLACE_CSA_DUMMY_OP_groupi_n_83;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_84,
       WALLACE_CSA_DUMMY_OP_groupi_n_85,
       WALLACE_CSA_DUMMY_OP_groupi_n_86,
       WALLACE_CSA_DUMMY_OP_groupi_n_87,
       WALLACE_CSA_DUMMY_OP_groupi_n_88,
       WALLACE_CSA_DUMMY_OP_groupi_n_90,
       WALLACE_CSA_DUMMY_OP_groupi_n_91,
       WALLACE_CSA_DUMMY_OP_groupi_n_93;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_94,
       WALLACE_CSA_DUMMY_OP_groupi_n_96,
       WALLACE_CSA_DUMMY_OP_groupi_n_97,
       WALLACE_CSA_DUMMY_OP_groupi_n_99, n_2, n_5, n_10, n_12;
  wire n_24, n_26, n_27, n_31, n_141, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166;
  DFFQX2 \C_reg[0] (.CK (clk), .D (n_26), .Q (C[0]));
  DFFQX2 \C_reg[1] (.CK (clk), .D (n_158), .Q (C[1]));
  DFFQX2 \C_reg[3] (.CK (clk), .D (n_160), .Q (C[3]));
  DFFQX2 \C_reg[7] (.CK (clk), .D (n_165), .Q (C[7]));
  DFFQX2 \C_reg[15] (.CK (clk), .D (n_166), .Q (C[15]));
  DFFQX2 \C_reg[31] (.CK (clk), .D (n_163), .Q (C[31]));
  DFFQX2 \C_reg[16] (.CK (clk), .D (n_2), .Q (C[16]));
  DFFQX2 \C_reg[8] (.CK (clk), .D (n_10), .Q (C[8]));
  DFFQX2 \C_reg[17] (.CK (clk), .D (n_148), .Q (C[17]));
  DFFQX2 \C_reg[18] (.CK (clk), .D (n_149), .Q (C[18]));
  DFFQX2 \C_reg[4] (.CK (clk), .D (n_161), .Q (C[4]));
  DFFQX2 \C_reg[9] (.CK (clk), .D (n_143), .Q (C[9]));
  DFFQX2 \C_reg[19] (.CK (clk), .D (n_150), .Q (C[19]));
  DFFQX2 \C_reg[20] (.CK (clk), .D (n_151), .Q (C[20]));
  DFFQX2 \C_reg[10] (.CK (clk), .D (n_144), .Q (C[10]));
  DFFQX2 \C_reg[21] (.CK (clk), .D (n_152), .Q (C[21]));
  DFFQX2 \C_reg[22] (.CK (clk), .D (n_27), .Q (C[22]));
  DFFQX2 \C_reg[2] (.CK (clk), .D (n_159), .Q (C[2]));
  DFFQX2 \C_reg[5] (.CK (clk), .D (n_162), .Q (C[5]));
  DFFQX2 \C_reg[11] (.CK (clk), .D (n_145), .Q (C[11]));
  DFFQX2 \C_reg[23] (.CK (clk), .D (n_164), .Q (C[23]));
  DFFQX2 \C_reg[24] (.CK (clk), .D (n_24), .Q (C[24]));
  DFFQX2 \C_reg[12] (.CK (clk), .D (n_146), .Q (C[12]));
  DFFQX2 \C_reg[25] (.CK (clk), .D (n_153), .Q (C[25]));
  DFFQX2 \C_reg[26] (.CK (clk), .D (n_154), .Q (C[26]));
  DFFQX2 \C_reg[6] (.CK (clk), .D (n_12), .Q (C[6]));
  DFFQX2 \C_reg[13] (.CK (clk), .D (n_147), .Q (C[13]));
  DFFQX2 \C_reg[27] (.CK (clk), .D (n_155), .Q (C[27]));
  DFFQX2 \C_reg[28] (.CK (clk), .D (n_156), .Q (C[28]));
  DFFQX2 \C_reg[14] (.CK (clk), .D (n_31), .Q (C[14]));
  DFFQX2 \C_reg[29] (.CK (clk), .D (n_157), .Q (C[29]));
  DFFQX2 \C_reg[30] (.CK (clk), .D (n_5), .Q (C[30]));
  NOR2BXL g106__2398(.AN (\acc[0][1][1] [1]), .B (n_141), .Y (n_31));
  NOR2BXL g99__8428(.AN (\acc[1][0][1] [1]), .B (n_141), .Y (n_27));
  NOR2BXL g77__5526(.AN (\acc[0][0][1] [7]), .B (rst), .Y (n_26));
  NOR2BXL g101__3680(.AN (\acc[1][1][1] [7]), .B (n_141), .Y (n_24));
  NOR2BXL g83__6161(.AN (\acc[0][0][1] [1]), .B (rst), .Y (n_12));
  NOR2BXL g85__9945(.AN (\acc[0][1][1] [7]), .B (rst), .Y (n_10));
  NOR2BXL g90__6417(.AN (\acc[1][1][1] [1]), .B (n_141), .Y (n_5));
  NOR2BXL g93__5107(.AN (\acc[1][0][1] [7]), .B (rst), .Y (n_2));
  OAI21X1 WALLACE_CSA_DUMMY_OP1_groupi_g698__8428(.A0
       (WALLACE_CSA_DUMMY_OP1_groupi_n_84), .A1
       (WALLACE_CSA_DUMMY_OP1_groupi_n_97), .B0
       (WALLACE_CSA_DUMMY_OP1_groupi_n_99), .Y (\acc[0][1][1] [7]));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g699__5526(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_84), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_97), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_99));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g701__6783(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_79), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_85), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_93), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_97), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_96));
  ADDFX1 WALLACE_CSA_DUMMY_OP1_groupi_g703__3680(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_86), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_82), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_90), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_93), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_94));
  ADDFX1 WALLACE_CSA_DUMMY_OP1_groupi_g705__1617(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_83), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_74), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_87), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_90), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_91));
  ADDFX1 WALLACE_CSA_DUMMY_OP1_groupi_g707__2802(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_75), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_68), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_76), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_87), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_88));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g708__1705(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_57), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_71), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_72), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_85), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_86));
  AOI21X1 WALLACE_CSA_DUMMY_OP1_groupi_g709__5122(.A0
       (WALLACE_CSA_DUMMY_OP1_groupi_n_53), .A1
       (WALLACE_CSA_DUMMY_OP1_groupi_n_80), .B0
       (WALLACE_CSA_DUMMY_OP1_groupi_n_81), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_84));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g710__8246(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_64), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_66), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_73), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_82), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_83));
  NOR2XL WALLACE_CSA_DUMMY_OP1_groupi_g711__7098(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_53), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_80), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_81));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g712__6131(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_56), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_52), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_70), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_80), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_79));
  ADDFX1 WALLACE_CSA_DUMMY_OP1_groupi_g714__1881(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_59), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_47), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_69), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_76), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_77));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g715__5115(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_43), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_55), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_67), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_74), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_75));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g716__7482(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_42), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_54), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_45), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_72), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_73));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g717__4733(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_38), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_44), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_63), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_70), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_71));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g718__6161(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_37), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_48), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_68), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_69));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g719__9315(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_36), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_39), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_46), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_66), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_67));
  OAI21XL WALLACE_CSA_DUMMY_OP1_groupi_g720__9945(.A0
       (WALLACE_CSA_DUMMY_OP1_groupi_n_58), .A1
       (WALLACE_CSA_DUMMY_OP1_groupi_n_33), .B0
       (WALLACE_CSA_DUMMY_OP1_groupi_n_60), .Y (\acc[0][1][1] [1]));
  INVX1 WALLACE_CSA_DUMMY_OP1_groupi_g721(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_62), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_64));
  INVX1 WALLACE_CSA_DUMMY_OP1_groupi_g722(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_61), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_63));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g723__2883(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_16), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_32), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_40), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_61), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_62));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g724__2346(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_33), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_58), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_60));
  AOI21X1 WALLACE_CSA_DUMMY_OP1_groupi_g725__1666(.A0
       (WALLACE_CSA_DUMMY_OP1_groupi_n_33), .A1
       (WALLACE_CSA_DUMMY_OP1_groupi_n_50), .B0
       (WALLACE_CSA_DUMMY_OP1_groupi_n_51), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_59));
  NAND2BX1 WALLACE_CSA_DUMMY_OP1_groupi_g726__7410(.AN
       (WALLACE_CSA_DUMMY_OP1_groupi_n_51), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_50), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_58));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g727__6417(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_8), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_17), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_34), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_56), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_57));
  ADDFX1 WALLACE_CSA_DUMMY_OP1_groupi_g728__5477(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_5), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_4), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_23), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_54), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_55));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g729__2398(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_2), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_19), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_35), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_53), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_52));
  NOR2XL WALLACE_CSA_DUMMY_OP1_groupi_g730__5107(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_31), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_49), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_51));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g731__6260(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_31), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_49), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_50));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g732__4319(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_7), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_1), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_9), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_48), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_49));
  ADDFX1 WALLACE_CSA_DUMMY_OP1_groupi_g733__8428(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_21), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_6), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_10), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_46), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_47));
  ADDFXL WALLACE_CSA_DUMMY_OP1_groupi_g734__5526(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_22), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_0), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_11), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_44), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_45));
  ADDFX1 WALLACE_CSA_DUMMY_OP1_groupi_g735__6783(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_3), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_18), .CI
       (WALLACE_CSA_DUMMY_OP1_groupi_n_24), .CO
       (WALLACE_CSA_DUMMY_OP1_groupi_n_42), .S
       (WALLACE_CSA_DUMMY_OP1_groupi_n_43));
  CLKXOR2X1 WALLACE_CSA_DUMMY_OP1_groupi_g737__1617(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_40));
  XNOR2X1 WALLACE_CSA_DUMMY_OP1_groupi_g738__2802(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_27), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_12), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_39));
  XNOR2X1 WALLACE_CSA_DUMMY_OP1_groupi_g739__1705(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_26), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_25), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_38));
  XNOR2X1 WALLACE_CSA_DUMMY_OP1_groupi_g740__5122(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_28), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_13), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_37));
  OR2X1 WALLACE_CSA_DUMMY_OP1_groupi_g741__8246(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_28), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_13), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_36));
  OR2X1 WALLACE_CSA_DUMMY_OP1_groupi_g742__7098(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_26), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_25), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_35));
  OR2X1 WALLACE_CSA_DUMMY_OP1_groupi_g743__6131(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_34));
  NOR2XL WALLACE_CSA_DUMMY_OP1_groupi_g744__1881(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_15), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_30), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_33));
  NOR2XL WALLACE_CSA_DUMMY_OP1_groupi_g745__5115(.A
       (WALLACE_CSA_DUMMY_OP1_groupi_n_27), .B
       (WALLACE_CSA_DUMMY_OP1_groupi_n_12), .Y
       (WALLACE_CSA_DUMMY_OP1_groupi_n_32));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g746__7482(.A (B[6]), .B (A[3]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_31));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g747__4733(.A (B[15]), .B
       (A[7]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_30));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g748__6161(.A (B[6]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_29));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g749__9315(.A (B[6]), .B (A[2]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_28));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g750__9945(.A (B[12]), .B
       (A[7]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_24));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g751__2883(.A (B[6]), .B (A[1]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_27));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g752__2346(.A (B[4]), .B (A[1]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_26));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g753__1666(.A (B[5]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_25));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g754__7410(.A (B[13]), .B
       (A[6]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_23));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g755__6417(.A (B[4]), .B (A[2]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_22));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g756__5477(.A (B[15]), .B
       (A[5]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_21));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g757__2398(.A (B[5]), .B (A[3]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_20));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g758__5107(.A (B[12]), .B
       (A[4]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_19));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g759__6260(.A (B[4]), .B (A[3]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_18));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g760__4319(.A (B[13]), .B
       (A[4]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_17));
  AND2X1 WALLACE_CSA_DUMMY_OP1_groupi_g761__8428(.A (B[12]), .B (A[6]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_16));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g762__5526(.A (B[7]), .B (A[3]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_15));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g763__6783(.A (B[13]), .B
       (A[5]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_11));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g764__3680(.A (B[13]), .B
       (A[7]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_10));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g765__1617(.A (B[5]), .B (A[1]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_14));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g766__2802(.A (B[7]), .B (A[1]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_13));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g767__1705(.A (B[14]), .B
       (A[7]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_9));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g768__5122(.A (B[7]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_12));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g769__8246(.A (B[12]), .B
       (A[5]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_8));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g770__7098(.A (B[7]), .B (A[2]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_7));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g771__6131(.A (B[14]), .B
       (A[6]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_6));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g772__1881(.A (B[14]), .B
       (A[5]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_5));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g773__5115(.A (B[5]), .B (A[2]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_4));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g774__7482(.A (B[15]), .B
       (A[4]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_3));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g775__4733(.A (B[4]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_2));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g776__6161(.A (B[15]), .B
       (A[6]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_1));
  NAND2XL WALLACE_CSA_DUMMY_OP1_groupi_g777__9315(.A (B[14]), .B
       (A[4]), .Y (WALLACE_CSA_DUMMY_OP1_groupi_n_0));
  OAI21X1 WALLACE_CSA_DUMMY_OP3_groupi_g698__9945(.A0
       (WALLACE_CSA_DUMMY_OP3_groupi_n_84), .A1
       (WALLACE_CSA_DUMMY_OP3_groupi_n_97), .B0
       (WALLACE_CSA_DUMMY_OP3_groupi_n_99), .Y (\acc[1][0][1] [7]));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g699__2883(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_84), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_97), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_99));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g701__2346(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_79), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_85), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_93), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_97), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_96));
  ADDFX1 WALLACE_CSA_DUMMY_OP3_groupi_g703__1666(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_86), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_82), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_90), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_93), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_94));
  ADDFX1 WALLACE_CSA_DUMMY_OP3_groupi_g705__7410(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_83), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_74), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_87), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_90), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_91));
  ADDFX1 WALLACE_CSA_DUMMY_OP3_groupi_g707__6417(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_75), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_68), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_76), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_87), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_88));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g708__5477(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_57), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_71), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_72), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_85), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_86));
  AOI21X1 WALLACE_CSA_DUMMY_OP3_groupi_g709__2398(.A0
       (WALLACE_CSA_DUMMY_OP3_groupi_n_53), .A1
       (WALLACE_CSA_DUMMY_OP3_groupi_n_80), .B0
       (WALLACE_CSA_DUMMY_OP3_groupi_n_81), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_84));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g710__5107(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_64), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_66), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_73), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_82), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_83));
  NOR2XL WALLACE_CSA_DUMMY_OP3_groupi_g711__6260(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_53), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_80), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_81));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g712__4319(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_56), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_52), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_70), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_80), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_79));
  ADDFX1 WALLACE_CSA_DUMMY_OP3_groupi_g714__8428(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_59), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_47), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_69), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_76), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_77));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g715__5526(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_43), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_55), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_67), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_74), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_75));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g716__6783(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_42), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_54), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_45), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_72), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_73));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g717__3680(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_38), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_44), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_63), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_70), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_71));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g718__1617(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_37), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_48), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_68), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_69));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g719__2802(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_36), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_39), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_46), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_66), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_67));
  OAI21XL WALLACE_CSA_DUMMY_OP3_groupi_g720__1705(.A0
       (WALLACE_CSA_DUMMY_OP3_groupi_n_58), .A1
       (WALLACE_CSA_DUMMY_OP3_groupi_n_33), .B0
       (WALLACE_CSA_DUMMY_OP3_groupi_n_60), .Y (\acc[1][0][1] [1]));
  INVX1 WALLACE_CSA_DUMMY_OP3_groupi_g721(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_62), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_64));
  INVX1 WALLACE_CSA_DUMMY_OP3_groupi_g722(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_61), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_63));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g723__5122(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_16), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_32), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_40), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_61), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_62));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g724__8246(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_33), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_58), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_60));
  AOI21X1 WALLACE_CSA_DUMMY_OP3_groupi_g725__7098(.A0
       (WALLACE_CSA_DUMMY_OP3_groupi_n_33), .A1
       (WALLACE_CSA_DUMMY_OP3_groupi_n_50), .B0
       (WALLACE_CSA_DUMMY_OP3_groupi_n_51), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_59));
  NAND2BX1 WALLACE_CSA_DUMMY_OP3_groupi_g726__6131(.AN
       (WALLACE_CSA_DUMMY_OP3_groupi_n_51), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_50), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_58));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g727__1881(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_8), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_17), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_34), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_56), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_57));
  ADDFX1 WALLACE_CSA_DUMMY_OP3_groupi_g728__5115(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_5), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_4), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_23), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_54), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_55));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g729__7482(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_2), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_19), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_35), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_53), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_52));
  NOR2XL WALLACE_CSA_DUMMY_OP3_groupi_g730__4733(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_31), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_49), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_51));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g731__6161(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_31), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_49), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_50));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g732__9315(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_7), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_1), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_9), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_48), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_49));
  ADDFX1 WALLACE_CSA_DUMMY_OP3_groupi_g733__9945(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_21), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_6), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_10), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_46), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_47));
  ADDFXL WALLACE_CSA_DUMMY_OP3_groupi_g734__2883(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_22), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_0), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_11), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_44), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_45));
  ADDFX1 WALLACE_CSA_DUMMY_OP3_groupi_g735__2346(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_3), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_18), .CI
       (WALLACE_CSA_DUMMY_OP3_groupi_n_24), .CO
       (WALLACE_CSA_DUMMY_OP3_groupi_n_42), .S
       (WALLACE_CSA_DUMMY_OP3_groupi_n_43));
  CLKXOR2X1 WALLACE_CSA_DUMMY_OP3_groupi_g737__7410(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_40));
  XNOR2X1 WALLACE_CSA_DUMMY_OP3_groupi_g738__6417(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_27), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_12), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_39));
  XNOR2X1 WALLACE_CSA_DUMMY_OP3_groupi_g739__5477(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_26), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_25), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_38));
  XNOR2X1 WALLACE_CSA_DUMMY_OP3_groupi_g740__2398(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_28), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_13), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_37));
  OR2X1 WALLACE_CSA_DUMMY_OP3_groupi_g741__5107(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_28), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_13), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_36));
  OR2X1 WALLACE_CSA_DUMMY_OP3_groupi_g742__6260(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_26), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_25), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_35));
  OR2X1 WALLACE_CSA_DUMMY_OP3_groupi_g743__4319(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_34));
  NOR2XL WALLACE_CSA_DUMMY_OP3_groupi_g744__8428(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_15), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_30), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_33));
  NOR2XL WALLACE_CSA_DUMMY_OP3_groupi_g745__5526(.A
       (WALLACE_CSA_DUMMY_OP3_groupi_n_27), .B
       (WALLACE_CSA_DUMMY_OP3_groupi_n_12), .Y
       (WALLACE_CSA_DUMMY_OP3_groupi_n_32));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g746__6783(.A (B[2]), .B
       (A[11]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_31));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g747__3680(.A (B[11]), .B
       (A[15]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_30));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g748__1617(.A (B[2]), .B (A[8]),
       .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_29));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g749__2802(.A (B[2]), .B
       (A[10]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_28));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g750__1705(.A (B[8]), .B
       (A[15]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_24));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g751__5122(.A (B[2]), .B (A[9]),
       .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_27));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g752__8246(.A (B[0]), .B (A[9]),
       .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_26));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g753__7098(.A (B[1]), .B (A[8]),
       .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_25));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g754__6131(.A (B[9]), .B
       (A[14]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_23));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g755__1881(.A (B[0]), .B
       (A[10]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_22));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g756__5115(.A (B[11]), .B
       (A[13]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_21));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g757__7482(.A (B[1]), .B
       (A[11]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_20));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g758__4733(.A (B[8]), .B
       (A[12]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_19));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g759__6161(.A (B[0]), .B
       (A[11]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_18));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g760__9315(.A (B[9]), .B
       (A[12]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_17));
  AND2X1 WALLACE_CSA_DUMMY_OP3_groupi_g761__9945(.A (B[8]), .B (A[14]),
       .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_16));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g762__2883(.A (B[3]), .B
       (A[11]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_15));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g763__2346(.A (B[9]), .B
       (A[13]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_11));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g764__1666(.A (B[9]), .B
       (A[15]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_10));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g765__7410(.A (B[1]), .B (A[9]),
       .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_14));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g766__6417(.A (B[3]), .B (A[9]),
       .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_13));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g767__5477(.A (B[10]), .B
       (A[15]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_9));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g768__2398(.A (B[3]), .B (A[8]),
       .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_12));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g769__5107(.A (B[8]), .B
       (A[13]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_8));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g770__6260(.A (B[3]), .B
       (A[10]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_7));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g771__4319(.A (B[10]), .B
       (A[14]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_6));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g772__8428(.A (B[10]), .B
       (A[13]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_5));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g773__5526(.A (B[1]), .B
       (A[10]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_4));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g774__6783(.A (B[11]), .B
       (A[12]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_3));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g775__3680(.A (B[0]), .B (A[8]),
       .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_2));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g776__1617(.A (B[11]), .B
       (A[14]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_1));
  NAND2XL WALLACE_CSA_DUMMY_OP3_groupi_g777__2802(.A (B[10]), .B
       (A[12]), .Y (WALLACE_CSA_DUMMY_OP3_groupi_n_0));
  OAI21X1 WALLACE_CSA_DUMMY_OP5_groupi_g698__1705(.A0
       (WALLACE_CSA_DUMMY_OP5_groupi_n_84), .A1
       (WALLACE_CSA_DUMMY_OP5_groupi_n_97), .B0
       (WALLACE_CSA_DUMMY_OP5_groupi_n_99), .Y (\acc[1][1][1] [7]));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g699__5122(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_84), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_97), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_99));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g701__8246(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_79), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_85), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_93), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_97), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_96));
  ADDFX1 WALLACE_CSA_DUMMY_OP5_groupi_g703__7098(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_86), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_82), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_90), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_93), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_94));
  ADDFX1 WALLACE_CSA_DUMMY_OP5_groupi_g705__6131(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_83), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_74), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_87), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_90), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_91));
  ADDFX1 WALLACE_CSA_DUMMY_OP5_groupi_g707__1881(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_75), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_68), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_76), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_87), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_88));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g708__5115(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_57), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_71), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_72), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_85), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_86));
  AOI21X1 WALLACE_CSA_DUMMY_OP5_groupi_g709__7482(.A0
       (WALLACE_CSA_DUMMY_OP5_groupi_n_53), .A1
       (WALLACE_CSA_DUMMY_OP5_groupi_n_80), .B0
       (WALLACE_CSA_DUMMY_OP5_groupi_n_81), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_84));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g710__4733(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_64), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_66), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_73), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_82), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_83));
  NOR2XL WALLACE_CSA_DUMMY_OP5_groupi_g711__6161(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_53), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_80), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_81));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g712__9315(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_56), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_52), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_70), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_80), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_79));
  ADDFX1 WALLACE_CSA_DUMMY_OP5_groupi_g714__9945(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_59), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_47), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_69), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_76), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_77));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g715__2883(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_43), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_55), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_67), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_74), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_75));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g716__2346(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_42), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_54), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_45), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_72), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_73));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g717__1666(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_38), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_44), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_63), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_70), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_71));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g718__7410(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_37), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_48), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_68), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_69));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g719__6417(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_36), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_39), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_46), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_66), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_67));
  OAI21XL WALLACE_CSA_DUMMY_OP5_groupi_g720__5477(.A0
       (WALLACE_CSA_DUMMY_OP5_groupi_n_58), .A1
       (WALLACE_CSA_DUMMY_OP5_groupi_n_33), .B0
       (WALLACE_CSA_DUMMY_OP5_groupi_n_60), .Y (\acc[1][1][1] [1]));
  INVX1 WALLACE_CSA_DUMMY_OP5_groupi_g721(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_62), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_64));
  INVX1 WALLACE_CSA_DUMMY_OP5_groupi_g722(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_61), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_63));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g723__2398(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_16), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_32), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_40), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_61), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_62));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g724__5107(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_33), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_58), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_60));
  AOI21X1 WALLACE_CSA_DUMMY_OP5_groupi_g725__6260(.A0
       (WALLACE_CSA_DUMMY_OP5_groupi_n_33), .A1
       (WALLACE_CSA_DUMMY_OP5_groupi_n_50), .B0
       (WALLACE_CSA_DUMMY_OP5_groupi_n_51), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_59));
  NAND2BX1 WALLACE_CSA_DUMMY_OP5_groupi_g726__4319(.AN
       (WALLACE_CSA_DUMMY_OP5_groupi_n_51), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_50), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_58));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g727__8428(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_8), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_17), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_34), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_56), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_57));
  ADDFX1 WALLACE_CSA_DUMMY_OP5_groupi_g728__5526(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_5), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_4), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_23), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_54), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_55));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g729__6783(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_2), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_19), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_35), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_53), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_52));
  NOR2XL WALLACE_CSA_DUMMY_OP5_groupi_g730__3680(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_31), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_49), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_51));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g731__1617(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_31), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_49), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_50));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g732__2802(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_7), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_1), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_9), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_48), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_49));
  ADDFX1 WALLACE_CSA_DUMMY_OP5_groupi_g733__1705(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_21), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_6), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_10), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_46), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_47));
  ADDFXL WALLACE_CSA_DUMMY_OP5_groupi_g734__5122(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_22), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_0), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_11), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_44), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_45));
  ADDFX1 WALLACE_CSA_DUMMY_OP5_groupi_g735__8246(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_3), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_18), .CI
       (WALLACE_CSA_DUMMY_OP5_groupi_n_24), .CO
       (WALLACE_CSA_DUMMY_OP5_groupi_n_42), .S
       (WALLACE_CSA_DUMMY_OP5_groupi_n_43));
  CLKXOR2X1 WALLACE_CSA_DUMMY_OP5_groupi_g737__6131(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_40));
  XNOR2X1 WALLACE_CSA_DUMMY_OP5_groupi_g738__1881(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_27), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_12), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_39));
  XNOR2X1 WALLACE_CSA_DUMMY_OP5_groupi_g739__5115(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_26), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_25), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_38));
  XNOR2X1 WALLACE_CSA_DUMMY_OP5_groupi_g740__7482(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_28), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_13), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_37));
  OR2X1 WALLACE_CSA_DUMMY_OP5_groupi_g741__4733(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_28), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_13), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_36));
  OR2X1 WALLACE_CSA_DUMMY_OP5_groupi_g742__6161(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_26), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_25), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_35));
  OR2X1 WALLACE_CSA_DUMMY_OP5_groupi_g743__9315(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_34));
  NOR2XL WALLACE_CSA_DUMMY_OP5_groupi_g744__9945(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_15), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_30), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_33));
  NOR2XL WALLACE_CSA_DUMMY_OP5_groupi_g745__2883(.A
       (WALLACE_CSA_DUMMY_OP5_groupi_n_27), .B
       (WALLACE_CSA_DUMMY_OP5_groupi_n_12), .Y
       (WALLACE_CSA_DUMMY_OP5_groupi_n_32));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g746__2346(.A (B[6]), .B
       (A[11]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_31));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g747__1666(.A (B[15]), .B
       (A[15]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_30));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g748__7410(.A (B[6]), .B (A[8]),
       .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_29));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g749__6417(.A (B[6]), .B
       (A[10]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_28));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g750__5477(.A (B[12]), .B
       (A[15]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_24));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g751__2398(.A (B[6]), .B (A[9]),
       .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_27));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g752__5107(.A (B[4]), .B (A[9]),
       .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_26));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g753__6260(.A (B[5]), .B (A[8]),
       .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_25));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g754__4319(.A (B[13]), .B
       (A[14]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_23));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g755__8428(.A (B[4]), .B
       (A[10]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_22));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g756__5526(.A (B[15]), .B
       (A[13]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_21));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g757__6783(.A (B[5]), .B
       (A[11]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_20));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g758__3680(.A (B[12]), .B
       (A[12]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_19));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g759__1617(.A (B[4]), .B
       (A[11]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_18));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g760__2802(.A (B[13]), .B
       (A[12]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_17));
  AND2X1 WALLACE_CSA_DUMMY_OP5_groupi_g761__1705(.A (B[12]), .B
       (A[14]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_16));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g762__5122(.A (B[7]), .B
       (A[11]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_15));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g763__8246(.A (B[13]), .B
       (A[13]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_11));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g764__7098(.A (B[13]), .B
       (A[15]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_10));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g765__6131(.A (B[5]), .B (A[9]),
       .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_14));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g766__1881(.A (B[7]), .B (A[9]),
       .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_13));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g767__5115(.A (B[14]), .B
       (A[15]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_9));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g768__7482(.A (B[7]), .B (A[8]),
       .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_12));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g769__4733(.A (B[12]), .B
       (A[13]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_8));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g770__6161(.A (B[7]), .B
       (A[10]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_7));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g771__9315(.A (B[14]), .B
       (A[14]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_6));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g772__9945(.A (B[14]), .B
       (A[13]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_5));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g773__2883(.A (B[5]), .B
       (A[10]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_4));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g774__2346(.A (B[15]), .B
       (A[12]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_3));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g775__1666(.A (B[4]), .B (A[8]),
       .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_2));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g776__7410(.A (B[15]), .B
       (A[14]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_1));
  NAND2XL WALLACE_CSA_DUMMY_OP5_groupi_g777__6417(.A (B[14]), .B
       (A[12]), .Y (WALLACE_CSA_DUMMY_OP5_groupi_n_0));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g698__5477(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_84), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_97), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_99), .Y (\acc[0][0][1] [7]));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g699__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_84), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_97), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_99));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g701__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_79), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_85), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_93), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_97), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_96));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g703__6260(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_86), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_82), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_90), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_93), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_94));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g705__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_83), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_74), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_87), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_90), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_91));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g707__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_75), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_76), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_87), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_88));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g708__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_57), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_71), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_85), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_86));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g709__6783(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_80), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_81), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_84));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g710__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_82), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_83));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g711__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_80), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_81));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g712__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_52), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_80), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_79));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g714__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_59), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_69), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_76), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_77));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g715__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_55), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_67), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_74), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_75));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g716__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_73));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g717__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_63), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_71));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g718__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_48), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_69));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g719__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_67));
  OAI21XL WALLACE_CSA_DUMMY_OP_groupi_g720__5115(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_58), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_60), .Y (\acc[0][0][1] [1]));
  INVX1 WALLACE_CSA_DUMMY_OP_groupi_g721(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_62), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_64));
  INVX1 WALLACE_CSA_DUMMY_OP_groupi_g722(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_61), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_63));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g723__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_61), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_62));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g724__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_58), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_60));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g725__6161(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_59));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g726__9315(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_58));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g727__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_57));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g728__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_4), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_55));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g729__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_2), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_52));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g730__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_51));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g731__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_50));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g732__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_48), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_49));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g733__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_10), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_47));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g734__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_0), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_11), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_45));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g735__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_3), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_43));
  CLKXOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g737__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_40));
  XNOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g738__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_39));
  XNOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g739__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_38));
  XNOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g740__6783(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_37));
  OR2X1 WALLACE_CSA_DUMMY_OP_groupi_g741__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_36));
  OR2X1 WALLACE_CSA_DUMMY_OP_groupi_g742__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_35));
  OR2X1 WALLACE_CSA_DUMMY_OP_groupi_g743__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_34));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g744__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_33));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g745__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_32));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g746__8246(.A (B[2]), .B (A[3]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_31));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g747__7098(.A (B[11]), .B (A[7]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_30));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g748__6131(.A (B[2]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_29));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g749__1881(.A (B[2]), .B (A[2]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_28));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g750__5115(.A (B[8]), .B (A[7]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_24));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g751__7482(.A (B[2]), .B (A[1]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_27));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g752__4733(.A (B[0]), .B (A[1]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_26));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g753__6161(.A (B[1]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_25));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g754__9315(.A (B[9]), .B (A[6]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_23));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g755__9945(.A (B[0]), .B (A[2]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_22));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g756__2883(.A (B[11]), .B (A[5]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_21));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g757__2346(.A (B[1]), .B (A[3]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_20));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g758__1666(.A (B[8]), .B (A[4]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_19));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g759__7410(.A (B[0]), .B (A[3]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_18));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g760__6417(.A (B[9]), .B (A[4]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_17));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g761__5477(.A (B[8]), .B (A[6]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_16));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g762__2398(.A (B[3]), .B (A[3]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_15));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g763__5107(.A (B[9]), .B (A[5]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_11));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g764__6260(.A (B[9]), .B (A[7]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_10));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g765__4319(.A (B[1]), .B (A[1]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_14));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g766__8428(.A (B[3]), .B (A[1]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_13));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g767__5526(.A (B[10]), .B (A[7]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_9));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g768__6783(.A (B[3]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_12));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g769__3680(.A (B[8]), .B (A[5]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_8));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g770__1617(.A (B[3]), .B (A[2]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_7));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g771__2802(.A (B[10]), .B (A[6]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_6));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g772__1705(.A (B[10]), .B (A[5]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_5));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g773__5122(.A (B[1]), .B (A[2]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_4));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g774__8246(.A (B[11]), .B (A[4]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_3));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g775__7098(.A (B[0]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_2));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g776__6131(.A (B[11]), .B (A[6]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_1));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g777__1881(.A (B[10]), .B (A[4]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_0));
  BUFX2 drc_buf_sp801(.A (rst), .Y (n_141));
  NOR2XL g2(.A (WALLACE_CSA_DUMMY_OP1_groupi_n_96), .B (n_141), .Y
       (n_143));
  NOR2XL g803(.A (WALLACE_CSA_DUMMY_OP1_groupi_n_94), .B (n_141), .Y
       (n_144));
  NOR2XL g804(.A (WALLACE_CSA_DUMMY_OP1_groupi_n_91), .B (rst), .Y
       (n_145));
  NOR2XL g805(.A (WALLACE_CSA_DUMMY_OP1_groupi_n_88), .B (n_141), .Y
       (n_146));
  NOR2XL g806(.A (WALLACE_CSA_DUMMY_OP1_groupi_n_77), .B (rst), .Y
       (n_147));
  NOR2XL g807(.A (WALLACE_CSA_DUMMY_OP3_groupi_n_96), .B (rst), .Y
       (n_148));
  NOR2XL g808(.A (WALLACE_CSA_DUMMY_OP3_groupi_n_94), .B (rst), .Y
       (n_149));
  NOR2XL g809(.A (WALLACE_CSA_DUMMY_OP3_groupi_n_91), .B (n_141), .Y
       (n_150));
  NOR2XL g810(.A (WALLACE_CSA_DUMMY_OP3_groupi_n_88), .B (rst), .Y
       (n_151));
  NOR2XL g811(.A (WALLACE_CSA_DUMMY_OP3_groupi_n_77), .B (n_141), .Y
       (n_152));
  NOR2XL g812(.A (WALLACE_CSA_DUMMY_OP5_groupi_n_96), .B (n_141), .Y
       (n_153));
  NOR2XL g813(.A (WALLACE_CSA_DUMMY_OP5_groupi_n_94), .B (rst), .Y
       (n_154));
  NOR2XL g814(.A (WALLACE_CSA_DUMMY_OP5_groupi_n_91), .B (n_141), .Y
       (n_155));
  NOR2XL g815(.A (WALLACE_CSA_DUMMY_OP5_groupi_n_88), .B (n_141), .Y
       (n_156));
  NOR2XL g816(.A (WALLACE_CSA_DUMMY_OP5_groupi_n_77), .B (rst), .Y
       (n_157));
  NOR2XL g817(.A (WALLACE_CSA_DUMMY_OP_groupi_n_96), .B (rst), .Y
       (n_158));
  NOR2XL g818(.A (WALLACE_CSA_DUMMY_OP_groupi_n_94), .B (rst), .Y
       (n_159));
  NOR2XL g819(.A (WALLACE_CSA_DUMMY_OP_groupi_n_91), .B (n_141), .Y
       (n_160));
  NOR2XL g820(.A (WALLACE_CSA_DUMMY_OP_groupi_n_88), .B (n_141), .Y
       (n_161));
  NOR2XL g821(.A (WALLACE_CSA_DUMMY_OP_groupi_n_77), .B (rst), .Y
       (n_162));
  AOI211X1 g822(.A0 (WALLACE_CSA_DUMMY_OP5_groupi_n_15), .A1
       (WALLACE_CSA_DUMMY_OP5_groupi_n_30), .B0
       (WALLACE_CSA_DUMMY_OP5_groupi_n_33), .C0 (rst), .Y (n_163));
  AOI211X1 g823(.A0 (WALLACE_CSA_DUMMY_OP3_groupi_n_15), .A1
       (WALLACE_CSA_DUMMY_OP3_groupi_n_30), .B0
       (WALLACE_CSA_DUMMY_OP3_groupi_n_33), .C0 (rst), .Y (n_164));
  AOI211X1 g824(.A0 (WALLACE_CSA_DUMMY_OP_groupi_n_15), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .C0 (n_141), .Y (n_165));
  AOI211X1 g825(.A0 (WALLACE_CSA_DUMMY_OP1_groupi_n_15), .A1
       (WALLACE_CSA_DUMMY_OP1_groupi_n_30), .B0
       (WALLACE_CSA_DUMMY_OP1_groupi_n_33), .C0 (n_141), .Y (n_166));
endmodule

