
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 24 2026 09:28:29 IST (Mar 24 2026 03:58:29 UTC)

// Verification Directory fv/serial 

module serial(clk, rst, A, B, C);
  input clk, rst;
  input [0:15] A, B;
  output [0:31] C;
  wire clk, rst;
  wire [0:15] A, B;
  wire [0:31] C;
  wire [1:0] gj;
  wire [1:0] gk;
  wire [1:0] gi;
  wire [8:0] acc;
  wire [1:0] PS;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_0,
       WALLACE_CSA_DUMMY_OP_groupi_n_1,
       WALLACE_CSA_DUMMY_OP_groupi_n_2,
       WALLACE_CSA_DUMMY_OP_groupi_n_3,
       WALLACE_CSA_DUMMY_OP_groupi_n_4,
       WALLACE_CSA_DUMMY_OP_groupi_n_5,
       WALLACE_CSA_DUMMY_OP_groupi_n_6, WALLACE_CSA_DUMMY_OP_groupi_n_7;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_8,
       WALLACE_CSA_DUMMY_OP_groupi_n_9,
       WALLACE_CSA_DUMMY_OP_groupi_n_10,
       WALLACE_CSA_DUMMY_OP_groupi_n_11,
       WALLACE_CSA_DUMMY_OP_groupi_n_12,
       WALLACE_CSA_DUMMY_OP_groupi_n_13,
       WALLACE_CSA_DUMMY_OP_groupi_n_14,
       WALLACE_CSA_DUMMY_OP_groupi_n_15;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_16,
       WALLACE_CSA_DUMMY_OP_groupi_n_17,
       WALLACE_CSA_DUMMY_OP_groupi_n_18,
       WALLACE_CSA_DUMMY_OP_groupi_n_19,
       WALLACE_CSA_DUMMY_OP_groupi_n_20,
       WALLACE_CSA_DUMMY_OP_groupi_n_21,
       WALLACE_CSA_DUMMY_OP_groupi_n_22,
       WALLACE_CSA_DUMMY_OP_groupi_n_23;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_24,
       WALLACE_CSA_DUMMY_OP_groupi_n_25,
       WALLACE_CSA_DUMMY_OP_groupi_n_26,
       WALLACE_CSA_DUMMY_OP_groupi_n_27,
       WALLACE_CSA_DUMMY_OP_groupi_n_28,
       WALLACE_CSA_DUMMY_OP_groupi_n_29,
       WALLACE_CSA_DUMMY_OP_groupi_n_31,
       WALLACE_CSA_DUMMY_OP_groupi_n_32;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_33,
       WALLACE_CSA_DUMMY_OP_groupi_n_34,
       WALLACE_CSA_DUMMY_OP_groupi_n_35,
       WALLACE_CSA_DUMMY_OP_groupi_n_36,
       WALLACE_CSA_DUMMY_OP_groupi_n_37,
       WALLACE_CSA_DUMMY_OP_groupi_n_38,
       WALLACE_CSA_DUMMY_OP_groupi_n_39,
       WALLACE_CSA_DUMMY_OP_groupi_n_40;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_41,
       WALLACE_CSA_DUMMY_OP_groupi_n_42,
       WALLACE_CSA_DUMMY_OP_groupi_n_43,
       WALLACE_CSA_DUMMY_OP_groupi_n_45,
       WALLACE_CSA_DUMMY_OP_groupi_n_46,
       WALLACE_CSA_DUMMY_OP_groupi_n_47,
       WALLACE_CSA_DUMMY_OP_groupi_n_48,
       WALLACE_CSA_DUMMY_OP_groupi_n_49;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_50,
       WALLACE_CSA_DUMMY_OP_groupi_n_51,
       WALLACE_CSA_DUMMY_OP_groupi_n_52,
       WALLACE_CSA_DUMMY_OP_groupi_n_53,
       WALLACE_CSA_DUMMY_OP_groupi_n_54,
       WALLACE_CSA_DUMMY_OP_groupi_n_55,
       WALLACE_CSA_DUMMY_OP_groupi_n_56,
       WALLACE_CSA_DUMMY_OP_groupi_n_58;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_59,
       WALLACE_CSA_DUMMY_OP_groupi_n_60,
       WALLACE_CSA_DUMMY_OP_groupi_n_61,
       WALLACE_CSA_DUMMY_OP_groupi_n_62,
       WALLACE_CSA_DUMMY_OP_groupi_n_63,
       WALLACE_CSA_DUMMY_OP_groupi_n_64,
       WALLACE_CSA_DUMMY_OP_groupi_n_65,
       WALLACE_CSA_DUMMY_OP_groupi_n_66;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_67,
       WALLACE_CSA_DUMMY_OP_groupi_n_69,
       WALLACE_CSA_DUMMY_OP_groupi_n_70,
       WALLACE_CSA_DUMMY_OP_groupi_n_72,
       WALLACE_CSA_DUMMY_OP_groupi_n_73,
       WALLACE_CSA_DUMMY_OP_groupi_n_74,
       WALLACE_CSA_DUMMY_OP_groupi_n_77,
       WALLACE_CSA_DUMMY_OP_groupi_n_78;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_31, n_32;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_97, n_98, n_99;
  NAND2XL g2550__2398(.A (n_74), .B (n_75), .Y (n_91));
  NAND3X1 g2551__5107(.A (n_57), .B (n_56), .C (n_72), .Y (n_87));
  NAND3X1 g2552__6260(.A (n_58), .B (n_55), .C (n_73), .Y (n_88));
  NAND3X1 g2553__4319(.A (n_62), .B (n_61), .C (n_71), .Y (n_90));
  NAND3X1 g2554__8428(.A (n_64), .B (n_63), .C (n_66), .Y (n_86));
  NAND3X1 g2555__5526(.A (n_60), .B (n_59), .C (n_70), .Y (n_89));
  NAND2XL g2556__6783(.A (n_68), .B (n_69), .Y (n_85));
  NAND3X1 g2557__3680(.A (n_54), .B (n_65), .C (n_67), .Y (n_92));
  AOI22X1 g2558__1617(.A0 (A[1]), .A1 (n_52), .B0 (A[5]), .B1 (n_47),
       .Y (n_75));
  AOI22X1 g2559__2802(.A0 (A[9]), .A1 (n_49), .B0 (A[13]), .B1 (n_48),
       .Y (n_74));
  AOI22X1 g2560__1705(.A0 (B[4]), .A1 (n_50), .B0 (B[12]), .B1 (n_53),
       .Y (n_73));
  AOI22X1 g2561__5122(.A0 (B[5]), .A1 (n_50), .B0 (B[13]), .B1 (n_53),
       .Y (n_72));
  AOI22X1 g2562__8246(.A0 (A[10]), .A1 (n_49), .B0 (A[14]), .B1 (n_48),
       .Y (n_71));
  AOI22X1 g2563__7098(.A0 (A[11]), .A1 (n_49), .B0 (A[15]), .B1 (n_48),
       .Y (n_70));
  AOI22X1 g2564__6131(.A0 (B[3]), .A1 (n_51), .B0 (B[11]), .B1 (n_46),
       .Y (n_69));
  AOI22X1 g2565__1881(.A0 (B[7]), .A1 (n_50), .B0 (B[15]), .B1 (n_53),
       .Y (n_68));
  AOI22X1 g2566__5115(.A0 (A[8]), .A1 (n_49), .B0 (A[12]), .B1 (n_48),
       .Y (n_67));
  AOI22X1 g2567__7482(.A0 (B[6]), .A1 (n_50), .B0 (B[14]), .B1 (n_53),
       .Y (n_66));
  NAND2XL g2568__4733(.A (A[0]), .B (n_52), .Y (n_65));
  NAND2XL g2569__6161(.A (B[10]), .B (n_46), .Y (n_64));
  NAND2XL g2570__9315(.A (B[2]), .B (n_51), .Y (n_63));
  NAND2XL g2571__9945(.A (A[6]), .B (n_47), .Y (n_62));
  NAND2XL g2572__2883(.A (A[2]), .B (n_52), .Y (n_61));
  NAND2XL g2573__2346(.A (A[7]), .B (n_47), .Y (n_60));
  NAND2XL g2574__1666(.A (A[3]), .B (n_52), .Y (n_59));
  NAND2XL g2575__7410(.A (B[8]), .B (n_46), .Y (n_58));
  NAND2XL g2576__6417(.A (B[9]), .B (n_46), .Y (n_57));
  NAND2XL g2577__5477(.A (B[1]), .B (n_51), .Y (n_56));
  NAND2XL g2578__2398(.A (B[0]), .B (n_51), .Y (n_55));
  NAND2XL g2579__5107(.A (A[4]), .B (n_47), .Y (n_54));
  AND2X1 g2580__6260(.A (gj[0]), .B (gk[0]), .Y (n_53));
  NOR2XL g2581__4319(.A (gk[0]), .B (gi[0]), .Y (n_52));
  NOR2XL g2582__8428(.A (gk[0]), .B (gj[0]), .Y (n_51));
  NOR2BX1 g2583__5526(.AN (gj[0]), .B (gk[0]), .Y (n_50));
  NOR2BX1 g2584__6783(.AN (gi[0]), .B (gk[0]), .Y (n_49));
  AND2X1 g2585__3680(.A (gi[0]), .B (gk[0]), .Y (n_48));
  NOR2BX1 g2586__1617(.AN (gk[0]), .B (gi[0]), .Y (n_47));
  NOR2BX1 g2587__2802(.AN (gk[0]), .B (gj[0]), .Y (n_46));
  SDFFQX2 \C_reg[0] (.CK (clk), .D (C[0]), .SI (acc[7]), .SE (n_29), .Q
       (C[0]));
  SDFFQX2 \C_reg[1] (.CK (clk), .D (C[1]), .SI (acc[6]), .SE (n_29), .Q
       (C[1]));
  SDFFQX2 \C_reg[2] (.CK (clk), .D (C[2]), .SI (acc[5]), .SE (n_29), .Q
       (C[2]));
  SDFFQX2 \C_reg[3] (.CK (clk), .D (C[3]), .SI (acc[4]), .SE (n_29), .Q
       (C[3]));
  SDFFQX2 \C_reg[4] (.CK (clk), .D (C[4]), .SI (acc[3]), .SE (n_29), .Q
       (C[4]));
  SDFFQX2 \C_reg[5] (.CK (clk), .D (C[5]), .SI (acc[2]), .SE (n_29), .Q
       (C[5]));
  SDFFQX2 \C_reg[6] (.CK (clk), .D (C[6]), .SI (acc[1]), .SE (n_29), .Q
       (C[6]));
  SDFFQX2 \C_reg[7] (.CK (clk), .D (C[7]), .SI (acc[0]), .SE (n_29), .Q
       (C[7]));
  SDFFQX2 \C_reg[8] (.CK (clk), .D (acc[7]), .SI (C[8]), .SE (n_25), .Q
       (C[8]));
  SDFFQX2 \C_reg[9] (.CK (clk), .D (acc[6]), .SI (C[9]), .SE (n_25), .Q
       (C[9]));
  SDFFQX2 \C_reg[10] (.CK (clk), .D (acc[5]), .SI (C[10]), .SE (n_25),
       .Q (C[10]));
  SDFFQX2 \C_reg[11] (.CK (clk), .D (acc[4]), .SI (C[11]), .SE (n_25),
       .Q (C[11]));
  SDFFQX2 \C_reg[12] (.CK (clk), .D (acc[3]), .SI (C[12]), .SE (n_25),
       .Q (C[12]));
  SDFFQX2 \C_reg[13] (.CK (clk), .D (acc[2]), .SI (C[13]), .SE (n_25),
       .Q (C[13]));
  SDFFQX2 \C_reg[14] (.CK (clk), .D (acc[1]), .SI (C[14]), .SE (n_25),
       .Q (C[14]));
  SDFFQX2 \C_reg[15] (.CK (clk), .D (acc[0]), .SI (C[15]), .SE (n_25),
       .Q (C[15]));
  SDFFQX2 \C_reg[16] (.CK (clk), .D (acc[7]), .SI (C[16]), .SE (n_24),
       .Q (C[16]));
  SDFFQX2 \C_reg[17] (.CK (clk), .D (acc[6]), .SI (C[17]), .SE (n_24),
       .Q (C[17]));
  SDFFQX2 \C_reg[18] (.CK (clk), .D (acc[5]), .SI (C[18]), .SE (n_24),
       .Q (C[18]));
  SDFFQX2 \C_reg[19] (.CK (clk), .D (acc[4]), .SI (C[19]), .SE (n_24),
       .Q (C[19]));
  SDFFQX2 \C_reg[20] (.CK (clk), .D (acc[3]), .SI (C[20]), .SE (n_24),
       .Q (C[20]));
  SDFFQX2 \C_reg[21] (.CK (clk), .D (acc[2]), .SI (C[21]), .SE (n_24),
       .Q (C[21]));
  SDFFQX2 \C_reg[22] (.CK (clk), .D (acc[1]), .SI (C[22]), .SE (n_24),
       .Q (C[22]));
  SDFFQX2 \C_reg[23] (.CK (clk), .D (acc[0]), .SI (C[23]), .SE (n_24),
       .Q (C[23]));
  SDFFQX2 \C_reg[24] (.CK (clk), .D (C[24]), .SI (acc[7]), .SE (n_28),
       .Q (C[24]));
  SDFFQX2 \C_reg[25] (.CK (clk), .D (C[25]), .SI (acc[6]), .SE (n_28),
       .Q (C[25]));
  SDFFQX2 \C_reg[26] (.CK (clk), .D (C[26]), .SI (acc[5]), .SE (n_28),
       .Q (C[26]));
  SDFFQX2 \C_reg[27] (.CK (clk), .D (C[27]), .SI (acc[4]), .SE (n_28),
       .Q (C[27]));
  SDFFQX2 \C_reg[28] (.CK (clk), .D (C[28]), .SI (acc[3]), .SE (n_28),
       .Q (C[28]));
  SDFFQX2 \C_reg[29] (.CK (clk), .D (C[29]), .SI (acc[2]), .SE (n_28),
       .Q (C[29]));
  SDFFQX2 \C_reg[30] (.CK (clk), .D (C[30]), .SI (acc[1]), .SE (n_28),
       .Q (C[30]));
  SDFFQX2 \C_reg[31] (.CK (clk), .D (C[31]), .SI (acc[0]), .SE (n_28),
       .Q (C[31]));
  DFFRHQX1 \acc_reg[1] (.RN (n_2), .CK (clk), .D (n_42), .Q (acc[1]));
  DFFRHQX1 \acc_reg[2] (.RN (n_2), .CK (clk), .D (n_40), .Q (acc[2]));
  DFFRHQX1 \acc_reg[3] (.RN (n_2), .CK (clk), .D (n_39), .Q (acc[3]));
  DFFRHQX1 \acc_reg[4] (.RN (n_2), .CK (clk), .D (n_38), .Q (acc[4]));
  DFFRHQX1 \acc_reg[5] (.RN (n_2), .CK (clk), .D (n_37), .Q (acc[5]));
  DFFRHQX1 \acc_reg[6] (.RN (n_2), .CK (clk), .D (n_36), .Q (acc[6]));
  DFFRHQX1 \acc_reg[7] (.RN (n_2), .CK (clk), .D (n_35), .Q (acc[7]));
  DFFRHQX1 \gi_reg[0] (.RN (n_2), .CK (clk), .D (n_27), .Q (gi[0]));
  DFFRHQX1 \gk_reg[0] (.RN (n_2), .CK (clk), .D (n_43), .Q (gk[0]));
  OR4XL g3457__1705(.A (n_99), .B (n_98), .C (n_97), .D (n_32), .Y
       (n_45));
  NAND2XL g3500__8246(.A (n_4), .B (n_34), .Y (n_43));
  AO22XL g3501__7098(.A0 (acc[1]), .A1 (n_26), .B0 (n_5), .B1 (n_77),
       .Y (n_42));
  AO22XL g3502__6131(.A0 (acc[0]), .A1 (n_26), .B0 (n_5), .B1 (n_76),
       .Y (n_41));
  AO22XL g3504__1881(.A0 (acc[2]), .A1 (n_26), .B0 (n_5), .B1 (n_78),
       .Y (n_40));
  AO22XL g3505__5115(.A0 (acc[3]), .A1 (n_26), .B0 (n_5), .B1 (n_79),
       .Y (n_39));
  AO22XL g3506__7482(.A0 (acc[4]), .A1 (n_26), .B0 (n_5), .B1 (n_80),
       .Y (n_38));
  AO22XL g3507__4733(.A0 (acc[5]), .A1 (n_26), .B0 (n_5), .B1 (n_81),
       .Y (n_37));
  AO22XL g3508__6161(.A0 (acc[6]), .A1 (n_26), .B0 (n_5), .B1 (n_82),
       .Y (n_36));
  AO22XL g3509__9315(.A0 (acc[7]), .A1 (n_26), .B0 (n_5), .B1 (n_83),
       .Y (n_35));
  OAI21X1 g3510__9945(.A0 (PS[0]), .A1 (n_21), .B0 (gk[0]), .Y (n_34));
  OAI221X1 g3514__2346(.A0 (n_12), .A1 (PS[0]), .B0 (gk[0]), .B1 (n_4),
       .C0 (n_6), .Y (n_32));
  OAI211X1 g3515__1666(.A0 (gj[0]), .A1 (n_6), .B0 (n_22), .C0 (n_7),
       .Y (n_31));
  OAI21X1 g3517__6417(.A0 (n_0), .A1 (n_6), .B0 (n_15), .Y (n_27));
  NOR3X1 g3518__5477(.A (gi[0]), .B (gj[0]), .C (n_20), .Y (n_29));
  NOR2XL g3519__2398(.A (n_8), .B (n_20), .Y (n_28));
  OAI21X1 g3520__5107(.A0 (n_8), .A1 (n_6), .B0 (n_18), .Y (n_23));
  AOI21X1 g3521__6260(.A0 (n_8), .A1 (n_3), .B0 (n_1), .Y (n_26));
  OR3X1 g3522__4319(.A (gi[0]), .B (n_0), .C (n_20), .Y (n_25));
  NAND3X1 g3523__8428(.A (gi[0]), .B (n_0), .C (n_19), .Y (n_24));
  INVXL g3524(.A (n_21), .Y (n_22));
  INVX1 g3525(.A (n_19), .Y (n_20));
  NAND2XL g3526__5526(.A (gk[0]), .B (n_5), .Y (n_18));
  NOR4X1 g3527__6783(.A (A[2]), .B (A[12]), .C (A[15]), .D (B[6]), .Y
       (n_17));
  NOR4X1 g3528__3680(.A (A[3]), .B (B[0]), .C (B[7]), .D (B[8]), .Y
       (n_16));
  OAI21X1 g3529__1617(.A0 (PS[1]), .A1 (PS[0]), .B0 (gi[0]), .Y (n_15));
  NOR2XL g3530__2802(.A (n_8), .B (n_1), .Y (n_21));
  NOR2XL g3531__1705(.A (rst), .B (n_6), .Y (n_19));
  NOR4X1 g3532__5122(.A (A[4]), .B (A[8]), .C (B[4]), .D (B[12]), .Y
       (n_14));
  NOR4X1 g3533__8246(.A (A[0]), .B (A[10]), .C (B[2]), .D (B[9]), .Y
       (n_13));
  NOR4X1 g3534__7098(.A (A[1]), .B (A[7]), .C (A[11]), .D (B[15]), .Y
       (n_12));
  NOR4X1 g3535__6131(.A (A[5]), .B (A[9]), .C (B[1]), .D (B[13]), .Y
       (n_11));
  NOR4X1 g3536__1881(.A (A[13]), .B (B[3]), .C (B[5]), .D (B[11]), .Y
       (n_10));
  NOR4X1 g3537__5115(.A (A[6]), .B (A[14]), .C (B[10]), .D (B[14]), .Y
       (n_9));
  NAND2XL g3538__7482(.A (gj[0]), .B (PS[0]), .Y (n_7));
  NAND2XL g3539__4733(.A (gi[0]), .B (gj[0]), .Y (n_8));
  CLKINVX1 g3540(.A (n_5), .Y (n_4));
  NAND2XL g3541__6161(.A (PS[1]), .B (n_3), .Y (n_6));
  NOR2XL g3542__9315(.A (PS[1]), .B (n_3), .Y (n_5));
  INVXL g3556(.A (rst), .Y (n_2));
  OAI21XL WALLACE_CSA_DUMMY_OP_groupi_g463__9945(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_77), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .Y (n_83));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g464__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_77), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_78));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g465__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_55), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_74), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_77), .S (n_82));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_g466(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .Y (n_81));
  INVX1 WALLACE_CSA_DUMMY_OP_groupi_g467(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_74));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g468__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_63), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_61), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_69), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_73));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_g469(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .Y (n_80));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g470__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_62), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_69), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_70));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_g471(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_67), .Y (n_79));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g472__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_58), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_67));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g473__5477(.A0 (acc[7]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_60), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_65));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g474__2398(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_64));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g475__5107(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_59), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_63));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g476__6260(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_61), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_62));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g477__4319(.A (acc[7]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_60));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g478__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_59));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g479__5526(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_52), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_48), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_58));
  MXI2XL WALLACE_CSA_DUMMY_OP_groupi_g480__6783(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_52), .S0
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .Y (n_78));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g481__3680(.A (acc[6]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_55));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g482__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_54));
  CLKINVX1 WALLACE_CSA_DUMMY_OP_groupi_g483(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_52));
  NOR2BX1 WALLACE_CSA_DUMMY_OP_groupi_g484__2802(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_48), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_51));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g485__1705(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_50));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g486__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_49));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g487__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_48));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g488__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_47));
  NOR2BXL WALLACE_CSA_DUMMY_OP_groupi_g489__6131(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_46));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g490__1881(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_45));
  OAI21XL WALLACE_CSA_DUMMY_OP_groupi_g491__5115(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .Y (n_77));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g492__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_11), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_43));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g493__4733(.A (acc[5]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_4), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_41));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g494__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_2), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_38));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g495__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_37));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g496__9945(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_36));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g497__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_10), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_3), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_35));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g498__2346(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_33));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g499__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_32));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g500__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_31));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g501__6417(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_0), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .Y (n_76));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g502__5477(.A0 (acc[4]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_29));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g503__2398(.A0 (acc[1]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_28));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g504__5107(.A0 (acc[3]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_27));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g505__6260(.A0 (acc[2]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_26));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g506__4319(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .B (acc[2]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_25));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g507__8428(.A (acc[2]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_24));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g508__5526(.A (acc[1]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_23));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g509__6783(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_0), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_22));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g510__3680(.A (acc[4]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_21));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g511__1617(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .B (acc[4]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_20));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g512__2802(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .B (acc[3]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_19));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g513__1705(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .B (acc[1]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_18));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g514__5122(.A (acc[3]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_17));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g515__8246(.A (n_85), .B (n_91),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_16));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g516__7098(.A (n_90), .B (n_85),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_15));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g517__6131(.A (n_92), .B (n_88),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_14));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g518__1881(.A (n_88), .B (n_90),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_13));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g519__5115(.A (n_90), .B (n_86),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_12));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g520__7482(.A (n_87), .B (n_89),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_11));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g521__4733(.A (n_87), .B (n_90),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_10));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g522__6161(.A (n_91), .B (n_86),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_9));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g523__9315(.A (n_85), .B (n_89),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_8));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g524__9945(.A (n_89), .B (n_86),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_7));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g525__2883(.A (n_88), .B (n_91),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_4));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g526__2346(.A (n_92), .B (n_86),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_6));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g527__1666(.A (n_88), .B (n_89),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_3));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g528__7410(.A (n_92), .B (n_85),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_5));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g529__6417(.A (n_87), .B (n_91),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_2));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g530__5477(.A (n_92), .B (n_87),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_1));
  AOI31X1 g2(.A0 (n_16), .A1 (n_17), .A2 (n_14), .B0 (PS[0]), .Y
       (n_97));
  AOI21X1 g3571(.A0 (n_13), .A1 (n_11), .B0 (PS[0]), .Y (n_98));
  AOI21X1 g3572(.A0 (n_10), .A1 (n_9), .B0 (PS[0]), .Y (n_99));
  DFFRX1 \PS_reg[0] (.RN (n_2), .CK (clk), .D (n_45), .Q (PS[0]), .QN
       (n_3));
  DFFRX1 \PS_reg[1] (.RN (n_2), .CK (clk), .D (n_23), .Q (PS[1]), .QN
       (n_1));
  DFFRX1 \gj_reg[0] (.RN (n_2), .CK (clk), .D (n_31), .Q (gj[0]), .QN
       (n_0));
  DFFRX1 \acc_reg[0] (.RN (n_2), .CK (clk), .D (n_41), .Q (acc[0]), .QN
       (WALLACE_CSA_DUMMY_OP_groupi_n_0));
endmodule

