
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point A[0] A[0] -type PI PI
add mapped point A[1] A[1] -type PI PI
add mapped point A[2] A[2] -type PI PI
add mapped point A[3] A[3] -type PI PI
add mapped point A[4] A[4] -type PI PI
add mapped point A[5] A[5] -type PI PI
add mapped point A[6] A[6] -type PI PI
add mapped point A[7] A[7] -type PI PI
add mapped point A[8] A[8] -type PI PI
add mapped point A[9] A[9] -type PI PI
add mapped point A[10] A[10] -type PI PI
add mapped point A[11] A[11] -type PI PI
add mapped point A[12] A[12] -type PI PI
add mapped point A[13] A[13] -type PI PI
add mapped point A[14] A[14] -type PI PI
add mapped point A[15] A[15] -type PI PI
add mapped point A[16] A[16] -type PI PI
add mapped point A[17] A[17] -type PI PI
add mapped point A[18] A[18] -type PI PI
add mapped point A[19] A[19] -type PI PI
add mapped point A[20] A[20] -type PI PI
add mapped point A[21] A[21] -type PI PI
add mapped point A[22] A[22] -type PI PI
add mapped point A[23] A[23] -type PI PI
add mapped point A[24] A[24] -type PI PI
add mapped point A[25] A[25] -type PI PI
add mapped point A[26] A[26] -type PI PI
add mapped point A[27] A[27] -type PI PI
add mapped point A[28] A[28] -type PI PI
add mapped point A[29] A[29] -type PI PI
add mapped point A[30] A[30] -type PI PI
add mapped point A[31] A[31] -type PI PI
add mapped point A[32] A[32] -type PI PI
add mapped point A[33] A[33] -type PI PI
add mapped point A[34] A[34] -type PI PI
add mapped point A[35] A[35] -type PI PI
add mapped point B[0] B[0] -type PI PI
add mapped point B[1] B[1] -type PI PI
add mapped point B[2] B[2] -type PI PI
add mapped point B[3] B[3] -type PI PI
add mapped point B[4] B[4] -type PI PI
add mapped point B[5] B[5] -type PI PI
add mapped point B[6] B[6] -type PI PI
add mapped point B[7] B[7] -type PI PI
add mapped point B[8] B[8] -type PI PI
add mapped point B[9] B[9] -type PI PI
add mapped point B[10] B[10] -type PI PI
add mapped point B[11] B[11] -type PI PI
add mapped point B[12] B[12] -type PI PI
add mapped point B[13] B[13] -type PI PI
add mapped point B[14] B[14] -type PI PI
add mapped point B[15] B[15] -type PI PI
add mapped point B[16] B[16] -type PI PI
add mapped point B[17] B[17] -type PI PI
add mapped point B[18] B[18] -type PI PI
add mapped point B[19] B[19] -type PI PI
add mapped point B[20] B[20] -type PI PI
add mapped point B[21] B[21] -type PI PI
add mapped point B[22] B[22] -type PI PI
add mapped point B[23] B[23] -type PI PI
add mapped point B[24] B[24] -type PI PI
add mapped point B[25] B[25] -type PI PI
add mapped point B[26] B[26] -type PI PI
add mapped point B[27] B[27] -type PI PI
add mapped point B[28] B[28] -type PI PI
add mapped point B[29] B[29] -type PI PI
add mapped point B[30] B[30] -type PI PI
add mapped point B[31] B[31] -type PI PI
add mapped point B[32] B[32] -type PI PI
add mapped point B[33] B[33] -type PI PI
add mapped point B[34] B[34] -type PI PI
add mapped point B[35] B[35] -type PI PI

//output ports
add mapped point C[0] C[0] -type PO PO
add mapped point C[1] C[1] -type PO PO
add mapped point C[2] C[2] -type PO PO
add mapped point C[3] C[3] -type PO PO
add mapped point C[4] C[4] -type PO PO
add mapped point C[5] C[5] -type PO PO
add mapped point C[6] C[6] -type PO PO
add mapped point C[7] C[7] -type PO PO
add mapped point C[8] C[8] -type PO PO
add mapped point C[9] C[9] -type PO PO
add mapped point C[10] C[10] -type PO PO
add mapped point C[11] C[11] -type PO PO
add mapped point C[12] C[12] -type PO PO
add mapped point C[13] C[13] -type PO PO
add mapped point C[14] C[14] -type PO PO
add mapped point C[15] C[15] -type PO PO
add mapped point C[16] C[16] -type PO PO
add mapped point C[17] C[17] -type PO PO
add mapped point C[18] C[18] -type PO PO
add mapped point C[19] C[19] -type PO PO
add mapped point C[20] C[20] -type PO PO
add mapped point C[21] C[21] -type PO PO
add mapped point C[22] C[22] -type PO PO
add mapped point C[23] C[23] -type PO PO
add mapped point C[24] C[24] -type PO PO
add mapped point C[25] C[25] -type PO PO
add mapped point C[26] C[26] -type PO PO
add mapped point C[27] C[27] -type PO PO
add mapped point C[28] C[28] -type PO PO
add mapped point C[29] C[29] -type PO PO
add mapped point C[30] C[30] -type PO PO
add mapped point C[31] C[31] -type PO PO
add mapped point C[32] C[32] -type PO PO
add mapped point C[33] C[33] -type PO PO
add mapped point C[34] C[34] -type PO PO
add mapped point C[35] C[35] -type PO PO
add mapped point C[36] C[36] -type PO PO
add mapped point C[37] C[37] -type PO PO
add mapped point C[38] C[38] -type PO PO
add mapped point C[39] C[39] -type PO PO
add mapped point C[40] C[40] -type PO PO
add mapped point C[41] C[41] -type PO PO
add mapped point C[42] C[42] -type PO PO
add mapped point C[43] C[43] -type PO PO
add mapped point C[44] C[44] -type PO PO
add mapped point C[45] C[45] -type PO PO
add mapped point C[46] C[46] -type PO PO
add mapped point C[47] C[47] -type PO PO
add mapped point C[48] C[48] -type PO PO
add mapped point C[49] C[49] -type PO PO
add mapped point C[50] C[50] -type PO PO
add mapped point C[51] C[51] -type PO PO
add mapped point C[52] C[52] -type PO PO
add mapped point C[53] C[53] -type PO PO
add mapped point C[54] C[54] -type PO PO
add mapped point C[55] C[55] -type PO PO
add mapped point C[56] C[56] -type PO PO
add mapped point C[57] C[57] -type PO PO
add mapped point C[58] C[58] -type PO PO
add mapped point C[59] C[59] -type PO PO
add mapped point C[60] C[60] -type PO PO
add mapped point C[61] C[61] -type PO PO
add mapped point C[62] C[62] -type PO PO
add mapped point C[63] C[63] -type PO PO
add mapped point C[64] C[64] -type PO PO
add mapped point C[65] C[65] -type PO PO
add mapped point C[66] C[66] -type PO PO
add mapped point C[67] C[67] -type PO PO
add mapped point C[68] C[68] -type PO PO
add mapped point C[69] C[69] -type PO PO
add mapped point C[70] C[70] -type PO PO
add mapped point C[71] C[71] -type PO PO

//inout ports




//Sequential Pins
add mapped point C[0]/q C_reg[0]/Q -type DFF DFF
add mapped point C[8]/q C_reg[8]/Q -type DFF DFF
add mapped point C[24]/q C_reg[24]/Q -type DFF DFF
add mapped point C[64]/q C_reg[64]/Q -type DFF DFF
add mapped point C[32]/q C_reg[32]/Q -type DFF DFF
add mapped point C[16]/q C_reg[16]/Q -type DFF DFF
add mapped point C[40]/q C_reg[40]/Q -type DFF DFF
add mapped point C[48]/q C_reg[48]/Q -type DFF DFF
add mapped point C[56]/q C_reg[56]/Q -type DFF DFF
add mapped point acc[2][2][7]/q acc_reg[2][2][7]/Q -type DFF DFF
add mapped point acc[0][1][7]/q acc_reg[0][1][7]/Q -type DFF DFF
add mapped point acc[0][2][7]/q acc_reg[0][2][7]/Q -type DFF DFF
add mapped point acc[1][0][7]/q acc_reg[1][0][7]/Q -type DFF DFF
add mapped point acc[1][1][7]/q acc_reg[1][1][7]/Q -type DFF DFF
add mapped point acc[1][2][7]/q acc_reg[1][2][7]/Q -type DFF DFF
add mapped point acc[2][1][7]/q acc_reg[2][1][7]/Q -type DFF DFF
add mapped point acc[0][0][7]/q acc_reg[0][0][7]/Q -type DFF DFF
add mapped point acc[2][0][7]/q acc_reg[2][0][7]/Q -type DFF DFF
add mapped point C[17]/q C_reg[17]/Q -type DFF DFF
add mapped point C[49]/q C_reg[49]/Q -type DFF DFF
add mapped point C[1]/q C_reg[1]/Q -type DFF DFF
add mapped point C[57]/q C_reg[57]/Q -type DFF DFF
add mapped point C[25]/q C_reg[25]/Q -type DFF DFF
add mapped point C[41]/q C_reg[41]/Q -type DFF DFF
add mapped point C[9]/q C_reg[9]/Q -type DFF DFF
add mapped point C[65]/q C_reg[65]/Q -type DFF DFF
add mapped point C[33]/q C_reg[33]/Q -type DFF DFF
add mapped point acc[1][2][6]/q acc_reg[1][2][6]/Q -type DFF DFF
add mapped point acc[2][2][6]/q acc_reg[2][2][6]/Q -type DFF DFF
add mapped point acc[0][1][6]/q acc_reg[0][1][6]/Q -type DFF DFF
add mapped point acc[0][2][6]/q acc_reg[0][2][6]/Q -type DFF DFF
add mapped point acc[1][0][6]/q acc_reg[1][0][6]/Q -type DFF DFF
add mapped point acc[1][1][6]/q acc_reg[1][1][6]/Q -type DFF DFF
add mapped point acc[2][1][6]/q acc_reg[2][1][6]/Q -type DFF DFF
add mapped point acc[0][0][6]/q acc_reg[0][0][6]/Q -type DFF DFF
add mapped point acc[2][0][6]/q acc_reg[2][0][6]/Q -type DFF DFF
add mapped point C[10]/q C_reg[10]/Q -type DFF DFF
add mapped point C[58]/q C_reg[58]/Q -type DFF DFF
add mapped point C[66]/q C_reg[66]/Q -type DFF DFF
add mapped point C[34]/q C_reg[34]/Q -type DFF DFF
add mapped point C[50]/q C_reg[50]/Q -type DFF DFF
add mapped point C[2]/q C_reg[2]/Q -type DFF DFF
add mapped point C[42]/q C_reg[42]/Q -type DFF DFF
add mapped point C[18]/q C_reg[18]/Q -type DFF DFF
add mapped point C[26]/q C_reg[26]/Q -type DFF DFF
add mapped point acc[2][2][5]/q acc_reg[2][2][5]/Q -type DFF DFF
add mapped point acc[0][1][5]/q acc_reg[0][1][5]/Q -type DFF DFF
add mapped point acc[0][2][5]/q acc_reg[0][2][5]/Q -type DFF DFF
add mapped point acc[1][0][5]/q acc_reg[1][0][5]/Q -type DFF DFF
add mapped point acc[1][2][5]/q acc_reg[1][2][5]/Q -type DFF DFF
add mapped point acc[2][0][5]/q acc_reg[2][0][5]/Q -type DFF DFF
add mapped point acc[2][1][5]/q acc_reg[2][1][5]/Q -type DFF DFF
add mapped point acc[1][1][5]/q acc_reg[1][1][5]/Q -type DFF DFF
add mapped point acc[0][0][5]/q acc_reg[0][0][5]/Q -type DFF DFF
add mapped point C[27]/q C_reg[27]/Q -type DFF DFF
add mapped point C[11]/q C_reg[11]/Q -type DFF DFF
add mapped point C[51]/q C_reg[51]/Q -type DFF DFF
add mapped point C[67]/q C_reg[67]/Q -type DFF DFF
add mapped point C[43]/q C_reg[43]/Q -type DFF DFF
add mapped point C[3]/q C_reg[3]/Q -type DFF DFF
add mapped point C[19]/q C_reg[19]/Q -type DFF DFF
add mapped point C[59]/q C_reg[59]/Q -type DFF DFF
add mapped point C[35]/q C_reg[35]/Q -type DFF DFF
add mapped point acc[2][0][4]/q acc_reg[2][0][4]/Q -type DFF DFF
add mapped point acc[2][2][4]/q acc_reg[2][2][4]/Q -type DFF DFF
add mapped point acc[0][1][4]/q acc_reg[0][1][4]/Q -type DFF DFF
add mapped point acc[1][0][4]/q acc_reg[1][0][4]/Q -type DFF DFF
add mapped point acc[1][1][4]/q acc_reg[1][1][4]/Q -type DFF DFF
add mapped point acc[1][2][4]/q acc_reg[1][2][4]/Q -type DFF DFF
add mapped point acc[2][1][4]/q acc_reg[2][1][4]/Q -type DFF DFF
add mapped point acc[0][0][4]/q acc_reg[0][0][4]/Q -type DFF DFF
add mapped point acc[0][2][4]/q acc_reg[0][2][4]/Q -type DFF DFF
add mapped point C[36]/q C_reg[36]/Q -type DFF DFF
add mapped point C[60]/q C_reg[60]/Q -type DFF DFF
add mapped point C[28]/q C_reg[28]/Q -type DFF DFF
add mapped point C[52]/q C_reg[52]/Q -type DFF DFF
add mapped point C[4]/q C_reg[4]/Q -type DFF DFF
add mapped point C[20]/q C_reg[20]/Q -type DFF DFF
add mapped point C[12]/q C_reg[12]/Q -type DFF DFF
add mapped point C[44]/q C_reg[44]/Q -type DFF DFF
add mapped point C[68]/q C_reg[68]/Q -type DFF DFF
add mapped point acc[2][2][3]/q acc_reg[2][2][3]/Q -type DFF DFF
add mapped point acc[1][1][3]/q acc_reg[1][1][3]/Q -type DFF DFF
add mapped point acc[0][1][3]/q acc_reg[0][1][3]/Q -type DFF DFF
add mapped point acc[0][2][3]/q acc_reg[0][2][3]/Q -type DFF DFF
add mapped point acc[1][0][3]/q acc_reg[1][0][3]/Q -type DFF DFF
add mapped point acc[1][2][3]/q acc_reg[1][2][3]/Q -type DFF DFF
add mapped point acc[2][0][3]/q acc_reg[2][0][3]/Q -type DFF DFF
add mapped point acc[2][1][3]/q acc_reg[2][1][3]/Q -type DFF DFF
add mapped point acc[0][0][3]/q acc_reg[0][0][3]/Q -type DFF DFF
add mapped point C[69]/q C_reg[69]/Q -type DFF DFF
add mapped point C[29]/q C_reg[29]/Q -type DFF DFF
add mapped point C[37]/q C_reg[37]/Q -type DFF DFF
add mapped point C[61]/q C_reg[61]/Q -type DFF DFF
add mapped point C[13]/q C_reg[13]/Q -type DFF DFF
add mapped point C[45]/q C_reg[45]/Q -type DFF DFF
add mapped point C[53]/q C_reg[53]/Q -type DFF DFF
add mapped point C[5]/q C_reg[5]/Q -type DFF DFF
add mapped point C[21]/q C_reg[21]/Q -type DFF DFF
add mapped point acc[0][1][2]/q acc_reg[0][1][2]/Q -type DFF DFF
add mapped point acc[1][0][2]/q acc_reg[1][0][2]/Q -type DFF DFF
add mapped point acc[1][1][2]/q acc_reg[1][1][2]/Q -type DFF DFF
add mapped point acc[1][2][2]/q acc_reg[1][2][2]/Q -type DFF DFF
add mapped point acc[2][1][2]/q acc_reg[2][1][2]/Q -type DFF DFF
add mapped point acc[0][0][2]/q acc_reg[0][0][2]/Q -type DFF DFF
add mapped point acc[2][0][2]/q acc_reg[2][0][2]/Q -type DFF DFF
add mapped point acc[2][2][2]/q acc_reg[2][2][2]/Q -type DFF DFF
add mapped point acc[0][2][2]/q acc_reg[0][2][2]/Q -type DFF DFF
add mapped point mul_reg[1][0][5]/q mul_reg_reg[1][0][5]/Q -type DFF DFF
add mapped point mul_reg[0][2][5]/q mul_reg_reg[0][2][5]/Q -type DFF DFF
add mapped point mul_reg[2][0][5]/q mul_reg_reg[2][0][5]/Q -type DFF DFF
add mapped point mul_reg[2][1][5]/q mul_reg_reg[2][1][5]/Q -type DFF DFF
add mapped point mul_reg[2][2][5]/q mul_reg_reg[2][2][5]/Q -type DFF DFF
add mapped point mul_reg[0][1][5]/q mul_reg_reg[0][1][5]/Q -type DFF DFF
add mapped point mul_reg[1][1][5]/q mul_reg_reg[1][1][5]/Q -type DFF DFF
add mapped point mul_reg[0][0][5]/q mul_reg_reg[0][0][5]/Q -type DFF DFF
add mapped point mul_reg[1][2][5]/q mul_reg_reg[1][2][5]/Q -type DFF DFF
add mapped point mul_reg[0][1][6]/q mul_reg_reg[0][1][6]/Q -type DFF DFF
add mapped point mul_reg[0][0][6]/q mul_reg_reg[0][0][6]/Q -type DFF DFF
add mapped point mul_reg[1][2][6]/q mul_reg_reg[1][2][6]/Q -type DFF DFF
add mapped point mul_reg[2][0][6]/q mul_reg_reg[2][0][6]/Q -type DFF DFF
add mapped point mul_reg[2][1][6]/q mul_reg_reg[2][1][6]/Q -type DFF DFF
add mapped point mul_reg[1][0][6]/q mul_reg_reg[1][0][6]/Q -type DFF DFF
add mapped point mul_reg[0][2][6]/q mul_reg_reg[0][2][6]/Q -type DFF DFF
add mapped point mul_reg[2][2][6]/q mul_reg_reg[2][2][6]/Q -type DFF DFF
add mapped point mul_reg[1][1][6]/q mul_reg_reg[1][1][6]/Q -type DFF DFF
add mapped point mul_reg[1][0][4]/q mul_reg_reg[1][0][4]/Q -type DFF DFF
add mapped point mul_reg[1][1][7]/q mul_reg_reg[1][1][7]/Q -type DFF DFF
add mapped point mul_reg[0][1][7]/q mul_reg_reg[0][1][7]/Q -type DFF DFF
add mapped point mul_reg[0][0][7]/q mul_reg_reg[0][0][7]/Q -type DFF DFF
add mapped point mul_reg[2][1][4]/q mul_reg_reg[2][1][4]/Q -type DFF DFF
add mapped point mul_reg[2][0][4]/q mul_reg_reg[2][0][4]/Q -type DFF DFF
add mapped point mul_reg[0][2][4]/q mul_reg_reg[0][2][4]/Q -type DFF DFF
add mapped point mul_reg[1][2][4]/q mul_reg_reg[1][2][4]/Q -type DFF DFF
add mapped point mul_reg[0][0][4]/q mul_reg_reg[0][0][4]/Q -type DFF DFF
add mapped point mul_reg[0][1][4]/q mul_reg_reg[0][1][4]/Q -type DFF DFF
add mapped point mul_reg[1][1][4]/q mul_reg_reg[1][1][4]/Q -type DFF DFF
add mapped point mul_reg[2][2][4]/q mul_reg_reg[2][2][4]/Q -type DFF DFF
add mapped point mul_reg[2][2][7]/q mul_reg_reg[2][2][7]/Q -type DFF DFF
add mapped point mul_reg[1][0][7]/q mul_reg_reg[1][0][7]/Q -type DFF DFF
add mapped point mul_reg[2][1][7]/q mul_reg_reg[2][1][7]/Q -type DFF DFF
add mapped point mul_reg[2][0][7]/q mul_reg_reg[2][0][7]/Q -type DFF DFF
add mapped point mul_reg[1][2][7]/q mul_reg_reg[1][2][7]/Q -type DFF DFF
add mapped point mul_reg[0][2][7]/q mul_reg_reg[0][2][7]/Q -type DFF DFF
add mapped point C[46]/q C_reg[46]/Q -type DFF DFF
add mapped point C[6]/q C_reg[6]/Q -type DFF DFF
add mapped point C[30]/q C_reg[30]/Q -type DFF DFF
add mapped point C[38]/q C_reg[38]/Q -type DFF DFF
add mapped point C[14]/q C_reg[14]/Q -type DFF DFF
add mapped point C[54]/q C_reg[54]/Q -type DFF DFF
add mapped point C[22]/q C_reg[22]/Q -type DFF DFF
add mapped point C[62]/q C_reg[62]/Q -type DFF DFF
add mapped point C[70]/q C_reg[70]/Q -type DFF DFF
add mapped point acc[1][2][1]/q acc_reg[1][2][1]/Q -type DFF DFF
add mapped point acc[0][0][1]/q acc_reg[0][0][1]/Q -type DFF DFF
add mapped point acc[2][2][1]/q acc_reg[2][2][1]/Q -type DFF DFF
add mapped point acc[2][1][1]/q acc_reg[2][1][1]/Q -type DFF DFF
add mapped point acc[1][0][1]/q acc_reg[1][0][1]/Q -type DFF DFF
add mapped point acc[1][1][1]/q acc_reg[1][1][1]/Q -type DFF DFF
add mapped point acc[0][2][1]/q acc_reg[0][2][1]/Q -type DFF DFF
add mapped point acc[0][1][1]/q acc_reg[0][1][1]/Q -type DFF DFF
add mapped point acc[2][0][1]/q acc_reg[2][0][1]/Q -type DFF DFF
add mapped point mul_reg[1][1][3]/q mul_reg_reg[1][1][3]/Q -type DFF DFF
add mapped point mul_reg[1][2][3]/q mul_reg_reg[1][2][3]/Q -type DFF DFF
add mapped point mul_reg[0][2][3]/q mul_reg_reg[0][2][3]/Q -type DFF DFF
add mapped point mul_reg[2][0][3]/q mul_reg_reg[2][0][3]/Q -type DFF DFF
add mapped point mul_reg[2][1][3]/q mul_reg_reg[2][1][3]/Q -type DFF DFF
add mapped point mul_reg[1][0][3]/q mul_reg_reg[1][0][3]/Q -type DFF DFF
add mapped point mul_reg[2][2][3]/q mul_reg_reg[2][2][3]/Q -type DFF DFF
add mapped point mul_reg[0][1][3]/q mul_reg_reg[0][1][3]/Q -type DFF DFF
add mapped point mul_reg[0][0][3]/q mul_reg_reg[0][0][3]/Q -type DFF DFF
add mapped point C[31]/q C_reg[31]/Q -type DFF DFF
add mapped point C[63]/q C_reg[63]/Q -type DFF DFF
add mapped point C[71]/q C_reg[71]/Q -type DFF DFF
add mapped point C[39]/q C_reg[39]/Q -type DFF DFF
add mapped point C[47]/q C_reg[47]/Q -type DFF DFF
add mapped point C[23]/q C_reg[23]/Q -type DFF DFF
add mapped point C[15]/q C_reg[15]/Q -type DFF DFF
add mapped point C[55]/q C_reg[55]/Q -type DFF DFF
add mapped point C[7]/q C_reg[7]/Q -type DFF DFF
add mapped point mul_reg[2][2][2]/q mul_reg_reg[2][2][2]/Q -type DFF DFF
add mapped point mul_reg[0][0][2]/q mul_reg_reg[0][0][2]/Q -type DFF DFF
add mapped point mul_reg[0][1][2]/q mul_reg_reg[0][1][2]/Q -type DFF DFF
add mapped point mul_reg[1][1][2]/q mul_reg_reg[1][1][2]/Q -type DFF DFF
add mapped point mul_reg[1][2][2]/q mul_reg_reg[1][2][2]/Q -type DFF DFF
add mapped point mul_reg[0][2][2]/q mul_reg_reg[0][2][2]/Q -type DFF DFF
add mapped point mul_reg[2][1][2]/q mul_reg_reg[2][1][2]/Q -type DFF DFF
add mapped point mul_reg[1][0][2]/q mul_reg_reg[1][0][2]/Q -type DFF DFF
add mapped point mul_reg[2][0][2]/q mul_reg_reg[2][0][2]/Q -type DFF DFF
add mapped point acc[1][0][0]/q acc_reg[1][0][0]/Q -type DFF DFF
add mapped point acc[0][0][0]/q acc_reg[0][0][0]/Q -type DFF DFF
add mapped point acc[0][2][0]/q acc_reg[0][2][0]/Q -type DFF DFF
add mapped point acc[1][1][0]/q acc_reg[1][1][0]/Q -type DFF DFF
add mapped point acc[1][2][0]/q acc_reg[1][2][0]/Q -type DFF DFF
add mapped point acc[2][0][0]/q acc_reg[2][0][0]/Q -type DFF DFF
add mapped point acc[2][1][0]/q acc_reg[2][1][0]/Q -type DFF DFF
add mapped point acc[0][1][0]/q acc_reg[0][1][0]/Q -type DFF DFF
add mapped point acc[2][2][0]/q acc_reg[2][2][0]/Q -type DFF DFF
add mapped point mul_reg[2][0][1]/q mul_reg_reg[2][0][1]/Q -type DFF DFF
add mapped point mul_reg[1][0][1]/q mul_reg_reg[1][0][1]/Q -type DFF DFF
add mapped point mul_reg[2][2][1]/q mul_reg_reg[2][2][1]/Q -type DFF DFF
add mapped point mul_reg[0][2][1]/q mul_reg_reg[0][2][1]/Q -type DFF DFF
add mapped point mul_reg[2][1][1]/q mul_reg_reg[2][1][1]/Q -type DFF DFF
add mapped point mul_reg[0][0][1]/q mul_reg_reg[0][0][1]/Q -type DFF DFF
add mapped point mul_reg[1][2][1]/q mul_reg_reg[1][2][1]/Q -type DFF DFF
add mapped point mul_reg[1][1][1]/q mul_reg_reg[1][1][1]/Q -type DFF DFF
add mapped point mul_reg[0][1][1]/q mul_reg_reg[0][1][1]/Q -type DFF DFF
add mapped point mul_reg[0][2][0]/q mul_reg_reg[0][2][0]/Q -type DFF DFF
add mapped point mul_reg[2][2][0]/q mul_reg_reg[2][2][0]/Q -type DFF DFF
add mapped point mul_reg[0][1][0]/q mul_reg_reg[0][1][0]/Q -type DFF DFF
add mapped point mul_reg[0][0][0]/q mul_reg_reg[0][0][0]/Q -type DFF DFF
add mapped point mul_reg[2][0][0]/q mul_reg_reg[2][0][0]/Q -type DFF DFF
add mapped point mul_reg[1][2][0]/q mul_reg_reg[1][2][0]/Q -type DFF DFF
add mapped point mul_reg[1][0][0]/q mul_reg_reg[1][0][0]/Q -type DFF DFF
add mapped point mul_reg[2][1][0]/q mul_reg_reg[2][1][0]/Q -type DFF DFF
add mapped point mul_reg[1][1][0]/q mul_reg_reg[1][1][0]/Q -type DFF DFF
add mapped point k[2]/q k_reg[2]/Q -type DFF DFF
add mapped point k[1]/q k_reg[1]/Q -type DFF DFF
add mapped point k[0]/q k_reg[0]/Q -type DFF DFF
add mapped point k_reg[2]/q k_reg_reg[2]/Q -type DFF DFF
add mapped point k_reg[0]/q k_reg_reg[0]/Q -type DFF DFF
add mapped point k_reg[1]/q k_reg_reg[1]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
