
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 24 2026 09:34:37 IST (Mar 24 2026 04:04:37 UTC)

// Verification Directory fv/serial 

module serial(clk, rst, A, B, C);
  input clk, rst;
  input [0:63] A, B;
  output [0:127] C;
  wire clk, rst;
  wire [0:63] A, B;
  wire [0:127] C;
  wire [2:0] gi;
  wire [2:0] gk;
  wire [2:0] gj;
  wire [9:0] acc;
  wire [1:0] PS;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_1,
       WALLACE_CSA_DUMMY_OP_groupi_n_2,
       WALLACE_CSA_DUMMY_OP_groupi_n_3,
       WALLACE_CSA_DUMMY_OP_groupi_n_4,
       WALLACE_CSA_DUMMY_OP_groupi_n_5,
       WALLACE_CSA_DUMMY_OP_groupi_n_6,
       WALLACE_CSA_DUMMY_OP_groupi_n_7, WALLACE_CSA_DUMMY_OP_groupi_n_8;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_9,
       WALLACE_CSA_DUMMY_OP_groupi_n_10,
       WALLACE_CSA_DUMMY_OP_groupi_n_11,
       WALLACE_CSA_DUMMY_OP_groupi_n_12,
       WALLACE_CSA_DUMMY_OP_groupi_n_13,
       WALLACE_CSA_DUMMY_OP_groupi_n_14,
       WALLACE_CSA_DUMMY_OP_groupi_n_15,
       WALLACE_CSA_DUMMY_OP_groupi_n_16;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_17,
       WALLACE_CSA_DUMMY_OP_groupi_n_18,
       WALLACE_CSA_DUMMY_OP_groupi_n_19,
       WALLACE_CSA_DUMMY_OP_groupi_n_20,
       WALLACE_CSA_DUMMY_OP_groupi_n_21,
       WALLACE_CSA_DUMMY_OP_groupi_n_22,
       WALLACE_CSA_DUMMY_OP_groupi_n_23,
       WALLACE_CSA_DUMMY_OP_groupi_n_24;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_25,
       WALLACE_CSA_DUMMY_OP_groupi_n_26,
       WALLACE_CSA_DUMMY_OP_groupi_n_27,
       WALLACE_CSA_DUMMY_OP_groupi_n_28,
       WALLACE_CSA_DUMMY_OP_groupi_n_29,
       WALLACE_CSA_DUMMY_OP_groupi_n_30,
       WALLACE_CSA_DUMMY_OP_groupi_n_32,
       WALLACE_CSA_DUMMY_OP_groupi_n_33;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_34,
       WALLACE_CSA_DUMMY_OP_groupi_n_35,
       WALLACE_CSA_DUMMY_OP_groupi_n_36,
       WALLACE_CSA_DUMMY_OP_groupi_n_37,
       WALLACE_CSA_DUMMY_OP_groupi_n_38,
       WALLACE_CSA_DUMMY_OP_groupi_n_39,
       WALLACE_CSA_DUMMY_OP_groupi_n_40,
       WALLACE_CSA_DUMMY_OP_groupi_n_41;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_42,
       WALLACE_CSA_DUMMY_OP_groupi_n_43,
       WALLACE_CSA_DUMMY_OP_groupi_n_44,
       WALLACE_CSA_DUMMY_OP_groupi_n_46,
       WALLACE_CSA_DUMMY_OP_groupi_n_47,
       WALLACE_CSA_DUMMY_OP_groupi_n_48,
       WALLACE_CSA_DUMMY_OP_groupi_n_49,
       WALLACE_CSA_DUMMY_OP_groupi_n_50;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_51,
       WALLACE_CSA_DUMMY_OP_groupi_n_52,
       WALLACE_CSA_DUMMY_OP_groupi_n_53,
       WALLACE_CSA_DUMMY_OP_groupi_n_54,
       WALLACE_CSA_DUMMY_OP_groupi_n_55,
       WALLACE_CSA_DUMMY_OP_groupi_n_56,
       WALLACE_CSA_DUMMY_OP_groupi_n_57,
       WALLACE_CSA_DUMMY_OP_groupi_n_59;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_60,
       WALLACE_CSA_DUMMY_OP_groupi_n_61,
       WALLACE_CSA_DUMMY_OP_groupi_n_62,
       WALLACE_CSA_DUMMY_OP_groupi_n_63,
       WALLACE_CSA_DUMMY_OP_groupi_n_64,
       WALLACE_CSA_DUMMY_OP_groupi_n_65,
       WALLACE_CSA_DUMMY_OP_groupi_n_66,
       WALLACE_CSA_DUMMY_OP_groupi_n_67;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_68,
       WALLACE_CSA_DUMMY_OP_groupi_n_70,
       WALLACE_CSA_DUMMY_OP_groupi_n_71,
       WALLACE_CSA_DUMMY_OP_groupi_n_73,
       WALLACE_CSA_DUMMY_OP_groupi_n_74,
       WALLACE_CSA_DUMMY_OP_groupi_n_75,
       WALLACE_CSA_DUMMY_OP_groupi_n_78,
       WALLACE_CSA_DUMMY_OP_groupi_n_79;
  wire n_0, n_3, n_4, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_21, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_125, n_127;
  wire n_129, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_175, n_178, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_200, n_201, n_202;
  wire n_205, n_206, n_207, n_208, n_209, n_210, n_211, n_212;
  wire n_213, n_214, n_216, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_241, n_242, n_243, n_244, n_245, n_246;
  wire n_247, n_249, n_252, n_253, n_254, n_255, n_256, n_257;
  wire n_258, n_261, n_262, n_263, n_264, n_265, n_266, n_268;
  wire n_269, n_270, n_271, n_272, n_273, n_274, n_275, n_279;
  wire n_280, n_281, n_282, n_283, n_285, n_288, n_289, n_290;
  wire n_291, n_292, n_293, n_294, n_295, n_296, n_297;
  OR2X1 g9425__2398(.A (n_261), .B (n_263), .Y (n_280));
  NAND3X1 g9427__6260(.A (n_246), .B (n_247), .C (n_255), .Y (n_285));
  OR2X1 g9428__4319(.A (n_265), .B (n_254), .Y (n_282));
  OR2X1 g9429__8428(.A (n_264), .B (n_262), .Y (n_283));
  OR2X1 g9431__6783(.A (n_258), .B (n_266), .Y (n_279));
  OR2X1 g9432__3680(.A (n_252), .B (n_256), .Y (n_281));
  NAND4XL g9433__1617(.A (n_224), .B (n_225), .C (n_222), .D (n_221),
       .Y (n_266));
  NAND4XL g9434__2802(.A (n_214), .B (n_220), .C (n_223), .D (n_211),
       .Y (n_265));
  NAND4XL g9435__1705(.A (n_239), .B (n_240), .C (n_188), .D (n_243),
       .Y (n_264));
  NAND4XL g9436__5122(.A (n_237), .B (n_238), .C (n_235), .D (n_234),
       .Y (n_263));
  NAND4XL g9437__8246(.A (n_186), .B (n_236), .C (n_228), .D (n_233),
       .Y (n_262));
  NAND4XL g9438__7098(.A (n_226), .B (n_230), .C (n_232), .D (n_227),
       .Y (n_261));
  NAND4XL g9441__5115(.A (n_212), .B (n_245), .C (n_218), .D (n_213),
       .Y (n_258));
  NAND4XL g9442__7482(.A (n_209), .B (n_210), .C (n_207), .D (n_206),
       .Y (n_257));
  NAND4XL g9443__4733(.A (n_193), .B (n_195), .C (n_190), .D (n_189),
       .Y (n_256));
  AND4XL g9444__6161(.A (n_187), .B (n_191), .C (n_219), .D (n_200), .Y
       (n_255));
  NAND4XL g9445__9315(.A (n_208), .B (n_185), .C (n_205), .D (n_201),
       .Y (n_254));
  NAND4XL g9446__9945(.A (n_192), .B (n_202), .C (n_194), .D (n_197),
       .Y (n_253));
  NAND4XL g9447__2883(.A (n_241), .B (n_242), .C (n_216), .D (n_244),
       .Y (n_252));
  AOI211X1 g9450__7410(.A0 (A[49]), .A1 (n_169), .B0 (n_184), .C0
       (n_229), .Y (n_249));
  AOI221X1 g9452__5477(.A0 (A[32]), .A1 (n_153), .B0 (A[40]), .B1
       (n_121), .C0 (n_196), .Y (n_247));
  AOI221X1 g9453__2398(.A0 (A[36]), .A1 (n_119), .B0 (A[52]), .B1
       (n_162), .C0 (n_231), .Y (n_246));
  AOI22XL g9454__5107(.A0 (n_155), .A1 (B[10]), .B0 (n_156), .B1
       (B[14]), .Y (n_245));
  AOI22XL g9455__6260(.A0 (n_170), .A1 (B[32]), .B0 (n_148), .B1
       (B[36]), .Y (n_244));
  AOI22XL g9456__4319(.A0 (n_121), .A1 (A[42]), .B0 (n_162), .B1
       (A[54]), .Y (n_243));
  AOI22XL g9457__8428(.A0 (n_147), .A1 (B[40]), .B0 (n_168), .B1
       (B[44]), .Y (n_242));
  AOI22XL g9458__5526(.A0 (n_163), .A1 (B[0]), .B0 (n_154), .B1 (B[4]),
       .Y (n_241));
  AOI22XL g9459__6783(.A0 (n_169), .A1 (A[50]), .B0 (n_173), .B1
       (A[58]), .Y (n_240));
  AOI22XL g9460__3680(.A0 (n_153), .A1 (A[34]), .B0 (n_122), .B1
       (A[62]), .Y (n_239));
  AOI22XL g9461__1617(.A0 (n_152), .A1 (B[57]), .B0 (n_157), .B1
       (B[61]), .Y (n_238));
  AOI22XL g9462__2802(.A0 (n_158), .A1 (B[49]), .B0 (n_149), .B1
       (B[53]), .Y (n_237));
  AOI22XL g9463__1705(.A0 (n_120), .A1 (A[22]), .B0 (n_151), .B1
       (A[30]), .Y (n_236));
  AOI22XL g9464__5122(.A0 (n_145), .A1 (B[25]), .B0 (n_159), .B1
       (B[29]), .Y (n_235));
  AOI22XL g9465__8246(.A0 (n_160), .A1 (B[17]), .B0 (n_146), .B1
       (B[21]), .Y (n_234));
  AOI22XL g9466__7098(.A0 (n_150), .A1 (A[18]), .B0 (n_144), .B1
       (A[26]), .Y (n_233));
  AOI22XL g9467__6131(.A0 (n_147), .A1 (B[41]), .B0 (n_168), .B1
       (B[45]), .Y (n_232));
  AO22X1 g9468__1881(.A0 (A[44]), .A1 (n_143), .B0 (A[60]), .B1
       (n_122), .Y (n_231));
  AOI22XL g9469__5115(.A0 (n_155), .A1 (B[9]), .B0 (n_156), .B1
       (B[13]), .Y (n_230));
  OAI21X1 g9470__7482(.A0 (n_127), .A1 (n_161), .B0 (n_183), .Y
       (n_229));
  AOI22XL g9471__4733(.A0 (n_167), .A1 (A[6]), .B0 (n_171), .B1
       (A[14]), .Y (n_228));
  AOI22XL g9472__6161(.A0 (n_170), .A1 (B[33]), .B0 (n_148), .B1
       (B[37]), .Y (n_227));
  AOI22XL g9473__9315(.A0 (n_163), .A1 (B[1]), .B0 (n_154), .B1 (B[5]),
       .Y (n_226));
  AOI22XL g9474__9945(.A0 (n_152), .A1 (B[58]), .B0 (n_157), .B1
       (B[62]), .Y (n_225));
  AOI22XL g9475__2883(.A0 (n_158), .A1 (B[50]), .B0 (n_149), .B1
       (B[54]), .Y (n_224));
  AOI22XL g9476__2346(.A0 (n_119), .A1 (A[39]), .B0 (n_173), .B1
       (A[59]), .Y (n_223));
  AOI22XL g9477__1666(.A0 (n_145), .A1 (B[26]), .B0 (n_159), .B1
       (B[30]), .Y (n_222));
  AOI22XL g9478__7410(.A0 (n_160), .A1 (B[18]), .B0 (n_146), .B1
       (B[22]), .Y (n_221));
  AOI22XL g9479__6417(.A0 (n_169), .A1 (A[51]), .B0 (n_143), .B1
       (A[47]), .Y (n_220));
  AOI22XL g9480__5477(.A0 (n_120), .A1 (A[20]), .B0 (n_151), .B1
       (A[28]), .Y (n_219));
  AOI22XL g9481__2398(.A0 (n_147), .A1 (B[42]), .B0 (n_168), .B1
       (B[46]), .Y (n_218));
  AOI22XL g9483__6260(.A0 (n_155), .A1 (B[8]), .B0 (n_156), .B1
       (B[12]), .Y (n_216));
  AOI22XL g9485__8428(.A0 (n_162), .A1 (A[55]), .B0 (n_122), .B1
       (A[63]), .Y (n_214));
  AOI22XL g9486__5526(.A0 (n_170), .A1 (B[34]), .B0 (n_148), .B1
       (B[38]), .Y (n_213));
  AOI22XL g9487__6783(.A0 (n_163), .A1 (B[2]), .B0 (n_154), .B1 (B[6]),
       .Y (n_212));
  AOI22XL g9488__3680(.A0 (n_153), .A1 (A[35]), .B0 (n_121), .B1
       (A[43]), .Y (n_211));
  AOI22XL g9489__1617(.A0 (n_152), .A1 (B[59]), .B0 (n_157), .B1
       (B[63]), .Y (n_210));
  AOI22XL g9490__2802(.A0 (n_158), .A1 (B[51]), .B0 (n_149), .B1
       (B[55]), .Y (n_209));
  AOI22XL g9491__1705(.A0 (n_171), .A1 (A[15]), .B0 (n_151), .B1
       (A[31]), .Y (n_208));
  AOI22XL g9492__5122(.A0 (n_145), .A1 (B[27]), .B0 (n_159), .B1
       (B[31]), .Y (n_207));
  AOI22XL g9493__8246(.A0 (n_160), .A1 (B[19]), .B0 (n_146), .B1
       (B[23]), .Y (n_206));
  AOI22XL g9494__7098(.A0 (n_167), .A1 (A[7]), .B0 (n_120), .B1
       (A[23]), .Y (n_205));
  AOI21XL g9497__5115(.A0 (A[5]), .A1 (n_167), .B0 (n_178), .Y (n_202));
  AOI22XL g9498__7482(.A0 (n_150), .A1 (A[19]), .B0 (n_144), .B1
       (A[27]), .Y (n_201));
  AOI22XL g9499__4733(.A0 (n_150), .A1 (A[16]), .B0 (n_144), .B1
       (A[24]), .Y (n_200));
  AOI22XL g9502__9945(.A0 (n_150), .A1 (A[17]), .B0 (n_144), .B1
       (A[25]), .Y (n_197));
  AO22XL g9503__2883(.A0 (A[48]), .A1 (n_169), .B0 (A[56]), .B1
       (n_173), .Y (n_196));
  AOI22XL g9504__2346(.A0 (n_152), .A1 (B[56]), .B0 (n_157), .B1
       (B[60]), .Y (n_195));
  AOI21X1 g9505__1666(.A0 (A[21]), .A1 (n_120), .B0 (n_175), .Y
       (n_194));
  AOI22XL g9506__7410(.A0 (n_158), .A1 (B[48]), .B0 (n_149), .B1
       (B[52]), .Y (n_193));
  AOI22XL g9507__6417(.A0 (n_164), .A1 (A[1]), .B0 (n_151), .B1
       (A[29]), .Y (n_192));
  AOI22XL g9508__5477(.A0 (n_167), .A1 (A[4]), .B0 (n_171), .B1
       (A[12]), .Y (n_191));
  AOI22XL g9509__2398(.A0 (n_145), .A1 (B[24]), .B0 (n_159), .B1
       (B[28]), .Y (n_190));
  AOI22XL g9510__5107(.A0 (n_160), .A1 (B[16]), .B0 (n_146), .B1
       (B[20]), .Y (n_189));
  AOI22XL g9511__6260(.A0 (n_119), .A1 (A[38]), .B0 (n_143), .B1
       (A[46]), .Y (n_188));
  AOI22XL g9512__4319(.A0 (n_164), .A1 (A[0]), .B0 (n_166), .B1 (A[8]),
       .Y (n_187));
  AOI22XL g9513__8428(.A0 (n_164), .A1 (A[2]), .B0 (n_166), .B1
       (A[10]), .Y (n_186));
  AOI22XL g9514__5526(.A0 (n_164), .A1 (A[3]), .B0 (n_166), .B1
       (A[11]), .Y (n_185));
  NOR2BX1 g9515__6783(.AN (A[57]), .B (n_172), .Y (n_184));
  NAND2XL g9516__3680(.A (A[61]), .B (n_122), .Y (n_183));
  NOR2BXL g9521__8246(.AN (A[13]), .B (n_118), .Y (n_178));
  NOR2BXL g9524__1881(.AN (A[9]), .B (n_165), .Y (n_175));
  INVX1 g9526(.A (n_172), .Y (n_173));
  INVX1 g9527(.A (n_118), .Y (n_171));
  INVX1 g9528(.A (n_165), .Y (n_166));
  INVX1 g9529(.A (n_161), .Y (n_162));
  NAND2BX1 g9533__7482(.AN (n_142), .B (n_135), .Y (n_172));
  NOR2XL g9535__4733(.A (n_134), .B (n_136), .Y (n_170));
  NOR2XL g9536__6161(.A (n_142), .B (n_117), .Y (n_169));
  NOR2XL g9537__9315(.A (n_288), .B (n_136), .Y (n_168));
  NOR2XL g9538__9945(.A (n_116), .B (n_137), .Y (n_167));
  NAND2XL g9539__2883(.A (n_141), .B (n_135), .Y (n_165));
  NOR2XL g9540__2346(.A (n_116), .B (n_117), .Y (n_164));
  NOR2XL g9541__1666(.A (n_134), .B (n_117), .Y (n_163));
  NAND2BX1 g9542__7410(.AN (n_142), .B (n_138), .Y (n_161));
  NOR2XL g9543__6417(.A (n_134), .B (n_137), .Y (n_160));
  NOR2XL g9544__5477(.A (n_288), .B (n_137), .Y (n_159));
  NOR2XL g9545__2398(.A (n_289), .B (n_134), .Y (n_158));
  NOR2XL g9546__5107(.A (n_288), .B (n_289), .Y (n_157));
  NOR2XL g9547__6260(.A (n_142), .B (n_289), .Y (n_122));
  NOR2XL g9548__4319(.A (n_288), .B (n_117), .Y (n_156));
  NOR2XL g9552__8428(.A (n_140), .B (n_136), .Y (n_121));
  NOR2XL g9553__5526(.A (n_129), .B (n_117), .Y (n_155));
  NOR2XL g9554__6783(.A (n_133), .B (n_117), .Y (n_154));
  NOR2XL g9555__3680(.A (n_140), .B (n_117), .Y (n_153));
  NOR2XL g9556__1617(.A (n_289), .B (n_129), .Y (n_152));
  NOR2XL g9557__2802(.A (n_289), .B (n_132), .Y (n_151));
  NOR2XL g9558__1705(.A (n_132), .B (n_117), .Y (n_150));
  NOR2XL g9559__5122(.A (n_289), .B (n_133), .Y (n_149));
  NOR2XL g9560__8246(.A (n_133), .B (n_136), .Y (n_148));
  NOR2XL g9561__7098(.A (n_129), .B (n_136), .Y (n_147));
  NOR2XL g9562__6131(.A (n_133), .B (n_137), .Y (n_146));
  NOR2XL g9563__1881(.A (n_129), .B (n_137), .Y (n_145));
  NOR2XL g9566__5115(.A (n_132), .B (n_136), .Y (n_144));
  NOR2XL g9567__7482(.A (n_289), .B (n_140), .Y (n_143));
  CLKINVX1 g9568(.A (n_116), .Y (n_141));
  CLKINVX1 g9569(.A (n_139), .Y (n_140));
  CLKINVX1 g9570(.A (n_138), .Y (n_137));
  CLKINVX1 g9571(.A (n_136), .Y (n_135));
  NAND2XL g9572__4733(.A (gi[1]), .B (gi[0]), .Y (n_142));
  NOR2BX1 g9574__6161(.AN (gi[1]), .B (gi[0]), .Y (n_139));
  NOR2BX1 g9575__9315(.AN (gk[0]), .B (gk[1]), .Y (n_138));
  NAND2XL g9576__9945(.A (n_123), .B (gk[1]), .Y (n_136));
  CLKINVX1 g9578(.A (n_131), .Y (n_132));
  NAND2XL g9580__2883(.A (n_125), .B (n_4), .Y (n_134));
  NAND2XL g9581__2346(.A (gj[0]), .B (n_4), .Y (n_133));
  NOR2XL g9582__1666(.A (gi[1]), .B (n_10), .Y (n_131));
  NAND2XL g9584__6417(.A (gj[1]), .B (n_125), .Y (n_129));
  INVX1 g9586(.A (A[53]), .Y (n_127));
  CLKINVX1 g9590(.A (gj[0]), .Y (n_125));
  CLKINVX1 g9592(.A (gk[0]), .Y (n_123));
  AND2X1 g2__2398(.A (n_131), .B (n_138), .Y (n_120));
  AND2X1 g9593__5107(.A (n_139), .B (n_138), .Y (n_119));
  NAND2BX1 g9594__6260(.AN (n_289), .B (n_141), .Y (n_118));
  NAND2BX1 g9595__4319(.AN (gk[1]), .B (n_123), .Y (n_117));
  NAND2BXL g9596__8428(.AN (gi[1]), .B (n_10), .Y (n_116));
  SDFFQX2 \C_reg[0] (.CK (clk), .D (acc[7]), .SI (C[0]), .SE (n_94), .Q
       (C[0]));
  SDFFQX2 \C_reg[1] (.CK (clk), .D (acc[6]), .SI (C[1]), .SE (n_94), .Q
       (C[1]));
  SDFFQX2 \C_reg[2] (.CK (clk), .D (acc[5]), .SI (C[2]), .SE (n_94), .Q
       (C[2]));
  SDFFQX2 \C_reg[3] (.CK (clk), .D (acc[4]), .SI (C[3]), .SE (n_94), .Q
       (C[3]));
  SDFFQX2 \C_reg[4] (.CK (clk), .D (acc[3]), .SI (C[4]), .SE (n_94), .Q
       (C[4]));
  SDFFQX2 \C_reg[5] (.CK (clk), .D (acc[2]), .SI (C[5]), .SE (n_94), .Q
       (C[5]));
  SDFFQX2 \C_reg[6] (.CK (clk), .D (acc[1]), .SI (C[6]), .SE (n_94), .Q
       (C[6]));
  SDFFQX2 \C_reg[7] (.CK (clk), .D (acc[0]), .SI (C[7]), .SE (n_94), .Q
       (C[7]));
  SDFFQX2 \C_reg[8] (.CK (clk), .D (acc[7]), .SI (C[8]), .SE (n_91), .Q
       (C[8]));
  SDFFQX2 \C_reg[9] (.CK (clk), .D (acc[6]), .SI (C[9]), .SE (n_91), .Q
       (C[9]));
  SDFFQX2 \C_reg[10] (.CK (clk), .D (acc[5]), .SI (C[10]), .SE (n_91),
       .Q (C[10]));
  SDFFQX2 \C_reg[11] (.CK (clk), .D (acc[4]), .SI (C[11]), .SE (n_91),
       .Q (C[11]));
  SDFFQX2 \C_reg[12] (.CK (clk), .D (acc[3]), .SI (C[12]), .SE (n_91),
       .Q (C[12]));
  SDFFQX2 \C_reg[13] (.CK (clk), .D (acc[2]), .SI (C[13]), .SE (n_91),
       .Q (C[13]));
  SDFFQX2 \C_reg[14] (.CK (clk), .D (acc[1]), .SI (C[14]), .SE (n_91),
       .Q (C[14]));
  SDFFQX2 \C_reg[15] (.CK (clk), .D (acc[0]), .SI (C[15]), .SE (n_91),
       .Q (C[15]));
  SDFFQX2 \C_reg[16] (.CK (clk), .D (acc[7]), .SI (C[16]), .SE (n_92),
       .Q (C[16]));
  SDFFQX2 \C_reg[17] (.CK (clk), .D (acc[6]), .SI (C[17]), .SE (n_92),
       .Q (C[17]));
  SDFFQX2 \C_reg[18] (.CK (clk), .D (acc[5]), .SI (C[18]), .SE (n_92),
       .Q (C[18]));
  SDFFQX2 \C_reg[19] (.CK (clk), .D (acc[4]), .SI (C[19]), .SE (n_92),
       .Q (C[19]));
  SDFFQX2 \C_reg[20] (.CK (clk), .D (acc[3]), .SI (C[20]), .SE (n_92),
       .Q (C[20]));
  SDFFQX2 \C_reg[21] (.CK (clk), .D (acc[2]), .SI (C[21]), .SE (n_92),
       .Q (C[21]));
  SDFFQX2 \C_reg[22] (.CK (clk), .D (acc[1]), .SI (C[22]), .SE (n_92),
       .Q (C[22]));
  SDFFQX2 \C_reg[23] (.CK (clk), .D (acc[0]), .SI (C[23]), .SE (n_92),
       .Q (C[23]));
  SDFFQX2 \C_reg[24] (.CK (clk), .D (acc[7]), .SI (C[24]), .SE (n_93),
       .Q (C[24]));
  SDFFQX2 \C_reg[25] (.CK (clk), .D (acc[6]), .SI (C[25]), .SE (n_93),
       .Q (C[25]));
  SDFFQX2 \C_reg[26] (.CK (clk), .D (acc[5]), .SI (C[26]), .SE (n_93),
       .Q (C[26]));
  SDFFQX2 \C_reg[27] (.CK (clk), .D (acc[4]), .SI (C[27]), .SE (n_93),
       .Q (C[27]));
  SDFFQX2 \C_reg[28] (.CK (clk), .D (acc[3]), .SI (C[28]), .SE (n_93),
       .Q (C[28]));
  SDFFQX2 \C_reg[29] (.CK (clk), .D (acc[2]), .SI (C[29]), .SE (n_93),
       .Q (C[29]));
  SDFFQX2 \C_reg[30] (.CK (clk), .D (acc[1]), .SI (C[30]), .SE (n_93),
       .Q (C[30]));
  SDFFQX2 \C_reg[31] (.CK (clk), .D (acc[0]), .SI (C[31]), .SE (n_93),
       .Q (C[31]));
  SDFFQX2 \C_reg[32] (.CK (clk), .D (C[32]), .SI (acc[7]), .SE (n_78),
       .Q (C[32]));
  SDFFQX2 \C_reg[33] (.CK (clk), .D (C[33]), .SI (acc[6]), .SE (n_78),
       .Q (C[33]));
  SDFFQX2 \C_reg[34] (.CK (clk), .D (C[34]), .SI (acc[5]), .SE (n_78),
       .Q (C[34]));
  SDFFQX2 \C_reg[35] (.CK (clk), .D (C[35]), .SI (acc[4]), .SE (n_78),
       .Q (C[35]));
  SDFFQX2 \C_reg[36] (.CK (clk), .D (C[36]), .SI (acc[3]), .SE (n_78),
       .Q (C[36]));
  SDFFQX2 \C_reg[37] (.CK (clk), .D (C[37]), .SI (acc[2]), .SE (n_78),
       .Q (C[37]));
  SDFFQX2 \C_reg[38] (.CK (clk), .D (C[38]), .SI (acc[1]), .SE (n_78),
       .Q (C[38]));
  SDFFQX2 \C_reg[39] (.CK (clk), .D (C[39]), .SI (acc[0]), .SE (n_78),
       .Q (C[39]));
  SDFFQX2 \C_reg[40] (.CK (clk), .D (C[40]), .SI (acc[7]), .SE (n_76),
       .Q (C[40]));
  SDFFQX2 \C_reg[41] (.CK (clk), .D (C[41]), .SI (acc[6]), .SE (n_76),
       .Q (C[41]));
  SDFFQX2 \C_reg[42] (.CK (clk), .D (C[42]), .SI (acc[5]), .SE (n_76),
       .Q (C[42]));
  SDFFQX2 \C_reg[43] (.CK (clk), .D (C[43]), .SI (acc[4]), .SE (n_76),
       .Q (C[43]));
  SDFFQX2 \C_reg[44] (.CK (clk), .D (C[44]), .SI (acc[3]), .SE (n_76),
       .Q (C[44]));
  SDFFQX2 \C_reg[45] (.CK (clk), .D (C[45]), .SI (acc[2]), .SE (n_76),
       .Q (C[45]));
  SDFFQX2 \C_reg[46] (.CK (clk), .D (C[46]), .SI (acc[1]), .SE (n_76),
       .Q (C[46]));
  SDFFQX2 \C_reg[47] (.CK (clk), .D (C[47]), .SI (acc[0]), .SE (n_76),
       .Q (C[47]));
  SDFFQX2 \C_reg[48] (.CK (clk), .D (C[48]), .SI (acc[7]), .SE (n_77),
       .Q (C[48]));
  SDFFQX2 \C_reg[49] (.CK (clk), .D (C[49]), .SI (acc[6]), .SE (n_77),
       .Q (C[49]));
  SDFFQX2 \C_reg[50] (.CK (clk), .D (C[50]), .SI (acc[5]), .SE (n_77),
       .Q (C[50]));
  SDFFQX2 \C_reg[51] (.CK (clk), .D (C[51]), .SI (acc[4]), .SE (n_77),
       .Q (C[51]));
  SDFFQX2 \C_reg[52] (.CK (clk), .D (C[52]), .SI (acc[3]), .SE (n_77),
       .Q (C[52]));
  SDFFQX2 \C_reg[53] (.CK (clk), .D (C[53]), .SI (acc[2]), .SE (n_77),
       .Q (C[53]));
  SDFFQX2 \C_reg[54] (.CK (clk), .D (C[54]), .SI (acc[1]), .SE (n_77),
       .Q (C[54]));
  SDFFQX2 \C_reg[55] (.CK (clk), .D (C[55]), .SI (acc[0]), .SE (n_77),
       .Q (C[55]));
  SDFFQX2 \C_reg[56] (.CK (clk), .D (C[56]), .SI (acc[7]), .SE (n_82),
       .Q (C[56]));
  SDFFQX2 \C_reg[57] (.CK (clk), .D (C[57]), .SI (acc[6]), .SE (n_82),
       .Q (C[57]));
  SDFFQX2 \C_reg[58] (.CK (clk), .D (C[58]), .SI (acc[5]), .SE (n_82),
       .Q (C[58]));
  SDFFQX2 \C_reg[59] (.CK (clk), .D (C[59]), .SI (acc[4]), .SE (n_82),
       .Q (C[59]));
  SDFFQX2 \C_reg[60] (.CK (clk), .D (C[60]), .SI (acc[3]), .SE (n_82),
       .Q (C[60]));
  SDFFQX2 \C_reg[61] (.CK (clk), .D (C[61]), .SI (acc[2]), .SE (n_82),
       .Q (C[61]));
  SDFFQX2 \C_reg[62] (.CK (clk), .D (C[62]), .SI (acc[1]), .SE (n_82),
       .Q (C[62]));
  SDFFQX2 \C_reg[63] (.CK (clk), .D (C[63]), .SI (acc[0]), .SE (n_82),
       .Q (C[63]));
  SDFFQX2 \C_reg[64] (.CK (clk), .D (C[64]), .SI (acc[7]), .SE (n_74),
       .Q (C[64]));
  SDFFQX2 \C_reg[65] (.CK (clk), .D (C[65]), .SI (acc[6]), .SE (n_74),
       .Q (C[65]));
  SDFFQX2 \C_reg[66] (.CK (clk), .D (C[66]), .SI (acc[5]), .SE (n_74),
       .Q (C[66]));
  SDFFQX2 \C_reg[67] (.CK (clk), .D (C[67]), .SI (acc[4]), .SE (n_74),
       .Q (C[67]));
  SDFFQX2 \C_reg[68] (.CK (clk), .D (C[68]), .SI (acc[3]), .SE (n_74),
       .Q (C[68]));
  SDFFQX2 \C_reg[69] (.CK (clk), .D (C[69]), .SI (acc[2]), .SE (n_74),
       .Q (C[69]));
  SDFFQX2 \C_reg[70] (.CK (clk), .D (C[70]), .SI (acc[1]), .SE (n_74),
       .Q (C[70]));
  SDFFQX2 \C_reg[71] (.CK (clk), .D (C[71]), .SI (acc[0]), .SE (n_74),
       .Q (C[71]));
  SDFFQX2 \C_reg[72] (.CK (clk), .D (C[72]), .SI (acc[7]), .SE (n_81),
       .Q (C[72]));
  SDFFQX2 \C_reg[73] (.CK (clk), .D (C[73]), .SI (acc[6]), .SE (n_81),
       .Q (C[73]));
  SDFFQX2 \C_reg[74] (.CK (clk), .D (C[74]), .SI (acc[5]), .SE (n_81),
       .Q (C[74]));
  SDFFQX2 \C_reg[75] (.CK (clk), .D (C[75]), .SI (acc[4]), .SE (n_81),
       .Q (C[75]));
  SDFFQX2 \C_reg[76] (.CK (clk), .D (C[76]), .SI (acc[3]), .SE (n_81),
       .Q (C[76]));
  SDFFQX2 \C_reg[77] (.CK (clk), .D (C[77]), .SI (acc[2]), .SE (n_81),
       .Q (C[77]));
  SDFFQX2 \C_reg[78] (.CK (clk), .D (C[78]), .SI (acc[1]), .SE (n_81),
       .Q (C[78]));
  SDFFQX2 \C_reg[79] (.CK (clk), .D (C[79]), .SI (acc[0]), .SE (n_81),
       .Q (C[79]));
  SDFFQX2 \C_reg[80] (.CK (clk), .D (C[80]), .SI (acc[7]), .SE (n_80),
       .Q (C[80]));
  SDFFQX2 \C_reg[81] (.CK (clk), .D (C[81]), .SI (acc[6]), .SE (n_80),
       .Q (C[81]));
  SDFFQX2 \C_reg[82] (.CK (clk), .D (C[82]), .SI (acc[5]), .SE (n_80),
       .Q (C[82]));
  SDFFQX2 \C_reg[83] (.CK (clk), .D (C[83]), .SI (acc[4]), .SE (n_80),
       .Q (C[83]));
  SDFFQX2 \C_reg[84] (.CK (clk), .D (C[84]), .SI (acc[3]), .SE (n_80),
       .Q (C[84]));
  SDFFQX2 \C_reg[85] (.CK (clk), .D (C[85]), .SI (acc[2]), .SE (n_80),
       .Q (C[85]));
  SDFFQX2 \C_reg[86] (.CK (clk), .D (C[86]), .SI (acc[1]), .SE (n_80),
       .Q (C[86]));
  SDFFQX2 \C_reg[87] (.CK (clk), .D (C[87]), .SI (acc[0]), .SE (n_80),
       .Q (C[87]));
  SDFFQX2 \C_reg[88] (.CK (clk), .D (C[88]), .SI (acc[7]), .SE (n_69),
       .Q (C[88]));
  SDFFQX2 \C_reg[89] (.CK (clk), .D (C[89]), .SI (acc[6]), .SE (n_69),
       .Q (C[89]));
  SDFFQX2 \C_reg[90] (.CK (clk), .D (C[90]), .SI (acc[5]), .SE (n_69),
       .Q (C[90]));
  SDFFQX2 \C_reg[91] (.CK (clk), .D (C[91]), .SI (acc[4]), .SE (n_69),
       .Q (C[91]));
  SDFFQX2 \C_reg[92] (.CK (clk), .D (C[92]), .SI (acc[3]), .SE (n_69),
       .Q (C[92]));
  SDFFQX2 \C_reg[93] (.CK (clk), .D (C[93]), .SI (acc[2]), .SE (n_69),
       .Q (C[93]));
  SDFFQX2 \C_reg[94] (.CK (clk), .D (C[94]), .SI (acc[1]), .SE (n_69),
       .Q (C[94]));
  SDFFQX2 \C_reg[95] (.CK (clk), .D (C[95]), .SI (acc[0]), .SE (n_69),
       .Q (C[95]));
  SDFFQX2 \C_reg[96] (.CK (clk), .D (C[96]), .SI (acc[7]), .SE (n_79),
       .Q (C[96]));
  SDFFQX2 \C_reg[97] (.CK (clk), .D (C[97]), .SI (acc[6]), .SE (n_79),
       .Q (C[97]));
  SDFFQX2 \C_reg[98] (.CK (clk), .D (C[98]), .SI (acc[5]), .SE (n_79),
       .Q (C[98]));
  SDFFQX2 \C_reg[99] (.CK (clk), .D (C[99]), .SI (acc[4]), .SE (n_79),
       .Q (C[99]));
  SDFFQX2 \C_reg[100] (.CK (clk), .D (C[100]), .SI (acc[3]), .SE
       (n_79), .Q (C[100]));
  SDFFQX2 \C_reg[101] (.CK (clk), .D (C[101]), .SI (acc[2]), .SE
       (n_79), .Q (C[101]));
  SDFFQX2 \C_reg[102] (.CK (clk), .D (C[102]), .SI (acc[1]), .SE
       (n_79), .Q (C[102]));
  SDFFQX2 \C_reg[103] (.CK (clk), .D (C[103]), .SI (acc[0]), .SE
       (n_79), .Q (C[103]));
  SDFFQX2 \C_reg[104] (.CK (clk), .D (C[104]), .SI (acc[7]), .SE
       (n_75), .Q (C[104]));
  SDFFQX2 \C_reg[105] (.CK (clk), .D (C[105]), .SI (acc[6]), .SE
       (n_75), .Q (C[105]));
  SDFFQX2 \C_reg[106] (.CK (clk), .D (C[106]), .SI (acc[5]), .SE
       (n_75), .Q (C[106]));
  SDFFQX2 \C_reg[107] (.CK (clk), .D (C[107]), .SI (acc[4]), .SE
       (n_75), .Q (C[107]));
  SDFFQX2 \C_reg[108] (.CK (clk), .D (C[108]), .SI (acc[3]), .SE
       (n_75), .Q (C[108]));
  SDFFQX2 \C_reg[109] (.CK (clk), .D (C[109]), .SI (acc[2]), .SE
       (n_75), .Q (C[109]));
  SDFFQX2 \C_reg[110] (.CK (clk), .D (C[110]), .SI (acc[1]), .SE
       (n_75), .Q (C[110]));
  SDFFQX2 \C_reg[111] (.CK (clk), .D (C[111]), .SI (acc[0]), .SE
       (n_75), .Q (C[111]));
  SDFFQX2 \C_reg[112] (.CK (clk), .D (C[112]), .SI (acc[7]), .SE
       (n_68), .Q (C[112]));
  SDFFQX2 \C_reg[113] (.CK (clk), .D (C[113]), .SI (acc[6]), .SE
       (n_68), .Q (C[113]));
  SDFFQX2 \C_reg[114] (.CK (clk), .D (C[114]), .SI (acc[5]), .SE
       (n_68), .Q (C[114]));
  SDFFQX2 \C_reg[115] (.CK (clk), .D (C[115]), .SI (acc[4]), .SE
       (n_68), .Q (C[115]));
  SDFFQX2 \C_reg[116] (.CK (clk), .D (C[116]), .SI (acc[3]), .SE
       (n_68), .Q (C[116]));
  SDFFQX2 \C_reg[117] (.CK (clk), .D (C[117]), .SI (acc[2]), .SE
       (n_68), .Q (C[117]));
  SDFFQX2 \C_reg[118] (.CK (clk), .D (C[118]), .SI (acc[1]), .SE
       (n_68), .Q (C[118]));
  SDFFQX2 \C_reg[119] (.CK (clk), .D (C[119]), .SI (acc[0]), .SE
       (n_68), .Q (C[119]));
  SDFFQX2 \C_reg[120] (.CK (clk), .D (C[120]), .SI (acc[7]), .SE
       (n_70), .Q (C[120]));
  SDFFQX2 \C_reg[121] (.CK (clk), .D (C[121]), .SI (acc[6]), .SE
       (n_70), .Q (C[121]));
  SDFFQX2 \C_reg[122] (.CK (clk), .D (C[122]), .SI (acc[5]), .SE
       (n_70), .Q (C[122]));
  SDFFQX2 \C_reg[123] (.CK (clk), .D (C[123]), .SI (acc[4]), .SE
       (n_70), .Q (C[123]));
  SDFFQX2 \C_reg[124] (.CK (clk), .D (C[124]), .SI (acc[3]), .SE
       (n_70), .Q (C[124]));
  SDFFQX2 \C_reg[125] (.CK (clk), .D (C[125]), .SI (acc[2]), .SE
       (n_70), .Q (C[125]));
  SDFFQX2 \C_reg[126] (.CK (clk), .D (C[126]), .SI (acc[1]), .SE
       (n_70), .Q (C[126]));
  SDFFQX2 \C_reg[127] (.CK (clk), .D (C[127]), .SI (acc[0]), .SE
       (n_70), .Q (C[127]));
  DFFRHQX1 \acc_reg[1] (.RN (n_9), .CK (clk), .D (n_109), .Q (acc[1]));
  DFFRHQX1 \acc_reg[2] (.RN (n_9), .CK (clk), .D (n_108), .Q (acc[2]));
  DFFRHQX1 \acc_reg[3] (.RN (n_9), .CK (clk), .D (n_107), .Q (acc[3]));
  DFFRHQX1 \acc_reg[4] (.RN (n_9), .CK (clk), .D (n_106), .Q (acc[4]));
  DFFRHQX1 \acc_reg[5] (.RN (n_9), .CK (clk), .D (n_105), .Q (acc[5]));
  DFFRHQX1 \acc_reg[6] (.RN (n_9), .CK (clk), .D (n_104), .Q (acc[6]));
  SDFFRHQX1 \gi_reg[0] (.RN (n_9), .CK (clk), .D (n_55), .SI (n_10),
       .SE (n_72), .Q (gi[0]));
  SDFFRHQX1 \gj_reg[0] (.RN (n_9), .CK (clk), .D (n_14), .SI (n_97),
       .SE (gj[0]), .Q (gj[0]));
  SDFFRHQX1 \gk_reg[0] (.RN (n_9), .CK (clk), .D (n_13), .SI (n_102),
       .SE (gk[0]), .Q (gk[0]));
  DFFRHQX1 \gk_reg[1] (.RN (n_9), .CK (clk), .D (n_112), .Q (gk[1]));
  AOI22XL g11884__5526(.A0 (n_114), .A1 (n_113), .B0 (n_89), .B1
       (PS[0]), .Y (n_115));
  NOR4X1 g11909__6783(.A (n_88), .B (n_86), .C (n_98), .D (n_101), .Y
       (n_114));
  NOR4X1 g11910__3680(.A (n_85), .B (n_84), .C (n_83), .D (n_99), .Y
       (n_113));
  OAI2BB1XL g11911__1617(.A0N (gk[1]), .A1N (n_102), .B0 (n_51), .Y
       (n_112));
  AO22XL g11985__2802(.A0 (acc[7]), .A1 (n_96), .B0 (n_13), .B1
       (n_275), .Y (n_111));
  AO22XL g11986__1705(.A0 (acc[0]), .A1 (n_96), .B0 (n_13), .B1
       (n_268), .Y (n_110));
  AO22XL g11987__5122(.A0 (acc[1]), .A1 (n_96), .B0 (n_13), .B1
       (n_269), .Y (n_109));
  AO22XL g11988__8246(.A0 (acc[2]), .A1 (n_96), .B0 (n_13), .B1
       (n_270), .Y (n_108));
  AO22XL g11989__7098(.A0 (acc[3]), .A1 (n_96), .B0 (n_13), .B1
       (n_271), .Y (n_107));
  AO22XL g11990__6131(.A0 (acc[4]), .A1 (n_96), .B0 (n_13), .B1
       (n_272), .Y (n_106));
  AO22XL g11991__1881(.A0 (acc[5]), .A1 (n_96), .B0 (n_13), .B1
       (n_273), .Y (n_105));
  AO22XL g11992__5115(.A0 (acc[6]), .A1 (n_96), .B0 (n_13), .B1
       (n_274), .Y (n_104));
  OAI2BB1XL g11993__7482(.A0N (gj[1]), .A1N (n_97), .B0 (n_65), .Y
       (n_103));
  NAND4XL g12039__4733(.A (n_46), .B (n_35), .C (n_34), .D (n_89), .Y
       (n_101));
  OAI21X1 g12040__6161(.A0 (n_289), .A1 (n_3), .B0 (n_95), .Y (n_102));
  OAI21X1 g12042__9315(.A0 (n_8), .A1 (n_24), .B0 (n_90), .Y (n_100));
  NAND4XL g12043__9945(.A (n_52), .B (n_53), .C (n_54), .D (n_67), .Y
       (n_99));
  NAND4XL g12044__2883(.A (n_37), .B (n_41), .C (n_36), .D (n_66), .Y
       (n_98));
  INVXL g12045(.A (n_96), .Y (n_95));
  NAND2XL g12046__2346(.A (gi[0]), .B (n_72), .Y (n_90));
  NAND2XL g12047__1666(.A (n_3), .B (n_73), .Y (n_97));
  OAI2BB1X1 g12048__7410(.A0N (PS[1]), .A1N (PS[0]), .B0 (n_73), .Y
       (n_96));
  NAND2XL g12049__6417(.A (n_23), .B (n_71), .Y (n_94));
  NAND2XL g12050__5477(.A (n_19), .B (n_71), .Y (n_93));
  NAND2XL g12051__2398(.A (n_17), .B (n_71), .Y (n_92));
  NAND2XL g12052__5107(.A (n_0), .B (n_71), .Y (n_91));
  NAND4XL g12053__6260(.A (n_33), .B (n_32), .C (n_31), .D (n_30), .Y
       (n_88));
  OAI32X1 g12054__4319(.A0 (n_21), .A1 (n_288), .A2 (n_15), .B0
       (n_289), .B1 (n_12), .Y (n_87));
  NAND4XL g12055__8428(.A (n_26), .B (n_29), .C (n_28), .D (n_27), .Y
       (n_86));
  NAND4XL g12056__5526(.A (n_47), .B (n_56), .C (n_49), .D (n_44), .Y
       (n_85));
  NAND4XL g12057__6783(.A (n_48), .B (n_43), .C (n_42), .D (n_45), .Y
       (n_84));
  NAND4XL g12058__3680(.A (n_40), .B (n_25), .C (n_39), .D (n_38), .Y
       (n_83));
  AOI211X1 g12059__1617(.A0 (n_289), .A1 (n_13), .B0 (n_50), .C0
       (n_14), .Y (n_89));
  NOR2XL g12060__2802(.A (n_60), .B (n_63), .Y (n_82));
  NOR2XL g12061__1705(.A (n_59), .B (n_61), .Y (n_81));
  NOR2XL g12062__5122(.A (n_59), .B (n_62), .Y (n_80));
  NOR2XL g12063__8246(.A (n_58), .B (n_64), .Y (n_79));
  NOR2XL g12064__7098(.A (n_60), .B (n_64), .Y (n_78));
  NOR2XL g12065__6131(.A (n_60), .B (n_62), .Y (n_77));
  NOR2XL g12066__1881(.A (n_60), .B (n_61), .Y (n_76));
  NOR2XL g12067__5115(.A (n_58), .B (n_61), .Y (n_75));
  NOR2XL g12068__7482(.A (n_59), .B (n_64), .Y (n_74));
  NOR4BX1 g12069__4733(.AN (n_11), .B (B[10]), .C (B[34]), .D (A[10]),
       .Y (n_67));
  NOR4BX1 g12070__6161(.AN (n_18), .B (B[43]), .C (B[45]), .D (B[51]),
       .Y (n_66));
  OAI21X1 g12071__9315(.A0 (n_0), .A1 (n_17), .B0 (n_14), .Y (n_65));
  NAND2XL g12072__9945(.A (n_19), .B (n_57), .Y (n_73));
  NOR3BX1 g12073__2883(.AN (n_21), .B (n_288), .C (n_15), .Y (n_72));
  NOR4X1 g12074__2346(.A (gi[0]), .B (gi[1]), .C (rst), .D (n_15), .Y
       (n_71));
  NOR2XL g12075__1666(.A (n_58), .B (n_63), .Y (n_70));
  NOR2XL g12076__7410(.A (n_59), .B (n_63), .Y (n_69));
  NOR2XL g12077__6417(.A (n_58), .B (n_62), .Y (n_68));
  INVX1 g12078(.A (n_57), .Y (n_58));
  NOR4X1 g12079__5477(.A (A[46]), .B (B[14]), .C (A[6]), .D (B[46]), .Y
       (n_56));
  NOR2XL g12080__2398(.A (n_10), .B (n_24), .Y (n_55));
  NOR4X1 g12081__5107(.A (A[50]), .B (A[58]), .C (A[62]), .D (B[18]),
       .Y (n_54));
  NOR4X1 g12082__6260(.A (B[26]), .B (B[50]), .C (A[42]), .D (B[58]),
       .Y (n_53));
  NOR4X1 g12083__4319(.A (A[2]), .B (A[18]), .C (A[26]), .D (B[42]), .Y
       (n_52));
  OAI21XL g12084__8428(.A0 (gk[1]), .A1 (gk[0]), .B0 (n_13), .Y (n_51));
  AOI2BB1XL g12085__5526(.A0N (B[25]), .A1N (B[57]), .B0 (PS[0]), .Y
       (n_50));
  NOR4X1 g12086__6783(.A (A[14]), .B (A[30]), .C (A[54]), .D (A[61]),
       .Y (n_49));
  NOR4X1 g12087__3680(.A (A[16]), .B (A[32]), .C (A[56]), .D (A[60]),
       .Y (n_48));
  NOR4X1 g12088__1617(.A (A[38]), .B (B[6]), .C (A[22]), .D (B[38]), .Y
       (n_47));
  NOR4X1 g12089__2802(.A (B[9]), .B (B[17]), .C (B[41]), .D (B[49]), .Y
       (n_46));
  NOR4X1 g12090__1705(.A (B[0]), .B (B[24]), .C (B[32]), .D (B[56]), .Y
       (n_45));
  NAND2XL g12091__5122(.A (n_23), .B (n_16), .Y (n_64));
  NAND2XL g12092__8246(.A (n_19), .B (n_16), .Y (n_63));
  NAND2XL g12093__7098(.A (n_17), .B (n_16), .Y (n_62));
  NAND2XL g12094__6131(.A (n_0), .B (n_16), .Y (n_61));
  NAND3X1 g12095__1881(.A (gi[0]), .B (n_8), .C (PS[1]), .Y (n_60));
  NAND3X1 g12096__5115(.A (gi[1]), .B (n_10), .C (PS[1]), .Y (n_59));
  NOR2XL g12097__7482(.A (n_21), .B (n_7), .Y (n_57));
  NOR4X1 g12098__4733(.A (B[22]), .B (B[30]), .C (B[54]), .D (B[62]),
       .Y (n_44));
  NOR4X1 g12099__6161(.A (A[48]), .B (B[16]), .C (A[8]), .D (B[48]), .Y
       (n_43));
  NOR4X1 g12100__9315(.A (A[40]), .B (B[8]), .C (A[24]), .D (B[40]), .Y
       (n_42));
  NOR4X1 g12101__9945(.A (B[21]), .B (B[27]), .C (A[1]), .D (B[61]), .Y
       (n_41));
  NOR4X1 g12102__2883(.A (A[12]), .B (A[20]), .C (A[28]), .D (A[36]),
       .Y (n_40));
  NOR4X1 g12103__2346(.A (A[44]), .B (B[12]), .C (A[4]), .D (B[44]), .Y
       (n_39));
  NOR4X1 g12104__1666(.A (B[4]), .B (B[28]), .C (B[36]), .D (B[60]), .Y
       (n_38));
  NOR4X1 g12105__7410(.A (A[3]), .B (B[35]), .C (B[37]), .D (B[53]), .Y
       (n_37));
  NOR4X1 g12106__6417(.A (B[5]), .B (B[11]), .C (B[13]), .D (B[19]), .Y
       (n_36));
  NOR4X1 g12107__5477(.A (A[17]), .B (A[41]), .C (A[49]), .D (A[57]),
       .Y (n_35));
  NOR4X1 g12108__2398(.A (A[33]), .B (B[1]), .C (A[25]), .D (B[33]), .Y
       (n_34));
  NOR4X1 g12109__5107(.A (A[19]), .B (A[21]), .C (A[27]), .D (A[29]),
       .Y (n_33));
  NOR4X1 g12110__6260(.A (A[35]), .B (A[37]), .C (A[43]), .D (A[45]),
       .Y (n_32));
  NOR4X1 g12111__4319(.A (A[5]), .B (A[9]), .C (A[11]), .D (A[13]), .Y
       (n_31));
  NOR4X1 g12112__8428(.A (A[51]), .B (A[53]), .C (A[59]), .D (B[3]), .Y
       (n_30));
  NOR4X1 g12113__5526(.A (B[7]), .B (B[23]), .C (B[39]), .D (B[55]), .Y
       (n_29));
  NOR4X1 g12114__6783(.A (A[23]), .B (A[39]), .C (A[55]), .D (A[63]),
       .Y (n_28));
  NOR4X1 g12115__3680(.A (A[15]), .B (B[31]), .C (A[31]), .D (B[63]),
       .Y (n_27));
  NOR4X1 g12116__1617(.A (A[47]), .B (B[15]), .C (A[7]), .D (B[47]), .Y
       (n_26));
  NOR4X1 g12117__2802(.A (A[52]), .B (B[20]), .C (A[0]), .D (B[52]), .Y
       (n_25));
  INVX1 g12118(.A (n_288), .Y (n_19));
  NOR2XL g12119__1705(.A (B[29]), .B (B[59]), .Y (n_18));
  NOR2XL g12120__5122(.A (PS[0]), .B (PS[1]), .Y (n_24));
  NOR2XL g12121__8246(.A (gj[0]), .B (gj[1]), .Y (n_23));
  NAND2XL g12123__6131(.A (gi[0]), .B (gi[1]), .Y (n_21));
  CLKINVX1 g12125(.A (n_15), .Y (n_14));
  INVXL g12126(.A (n_13), .Y (n_12));
  NOR2XL g12127__5115(.A (A[34]), .B (B[2]), .Y (n_11));
  NOR2XL g12128__7482(.A (gj[0]), .B (n_4), .Y (n_17));
  NOR2XL g12130__4733(.A (rst), .B (PS[0]), .Y (n_16));
  NAND2XL g12131__6161(.A (PS[1]), .B (n_3), .Y (n_15));
  NOR2XL g12132__9315(.A (PS[1]), .B (n_3), .Y (n_13));
  CLKINVX1 g12135(.A (gi[0]), .Y (n_10));
  INVXL g12196(.A (rst), .Y (n_9));
  DFFRX1 \PS_reg[0] (.RN (n_9), .CK (clk), .D (n_115), .Q (PS[0]), .QN
       (n_3));
  DFFRX1 \PS_reg[1] (.RN (n_9), .CK (clk), .D (n_87), .Q (PS[1]), .QN
       (n_7));
  DFFRX1 \acc_reg[0] (.RN (n_9), .CK (clk), .D (n_110), .Q (acc[0]),
       .QN (WALLACE_CSA_DUMMY_OP_groupi_n_1));
  DFFRX1 \gi_reg[1] (.RN (n_9), .CK (clk), .D (n_100), .Q (gi[1]), .QN
       (n_8));
  DFFRX1 \gj_reg[1] (.RN (n_9), .CK (clk), .D (n_103), .Q (gj[1]), .QN
       (n_4));
  NOR2BX1 g9597__9945(.AN (gj[0]), .B (gj[1]), .Y (n_0));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g473__2883(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_79), .Y (n_275));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g474__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_79));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g475__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_75), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .S (n_274));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_g476(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_74), .Y (n_273));
  INVX1 WALLACE_CSA_DUMMY_OP_groupi_g477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_75));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g478__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_62), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_74));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_g479(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_71), .Y (n_272));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g480__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_63), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_67), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_71));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_g481(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .Y (n_271));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g482__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_55), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_59), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_67), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_68));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g483__2398(.A0 (acc[7]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_57), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_61), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_66));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g484__5107(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_65));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g485__6260(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_60), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_64));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g486__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_62), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_63));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g487__8428(.A (acc[7]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_57), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_61));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g488__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_60));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g489__6783(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_59));
  MXI2XL WALLACE_CSA_DUMMY_OP_groupi_g490__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .S0
       (WALLACE_CSA_DUMMY_OP_groupi_n_52), .Y (n_270));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g491__1617(.A (acc[6]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_57), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_56));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g492__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_55));
  CLKINVX1 WALLACE_CSA_DUMMY_OP_groupi_g493(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_53));
  NOR2BX1 WALLACE_CSA_DUMMY_OP_groupi_g494__1705(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_52));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g495__5122(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_48), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_51));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g496__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_50));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g497__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_49));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g498__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_48));
  NOR2BX1 WALLACE_CSA_DUMMY_OP_groupi_g499__1881(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_47));
  NAND2BXL WALLACE_CSA_DUMMY_OP_groupi_g500__5115(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_46));
  OAI21XL WALLACE_CSA_DUMMY_OP_groupi_g501__7482(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .Y (n_269));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g502__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_44));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g503__6161(.A (acc[5]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_2), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_42));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g504__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_3), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_39));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g505__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_38));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g506__2883(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_37));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g507__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_10), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_11), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_4), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_36));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g508__1666(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_34));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g509__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_33));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g510__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_32));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g511__5477(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .Y (n_268));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g512__2398(.A0 (acc[4]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_30));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g513__5107(.A0 (acc[1]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_29));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g514__6260(.A0 (acc[3]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_28));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g515__4319(.A0 (acc[2]), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_27));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g516__8428(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .B (acc[2]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_26));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g517__5526(.A (acc[2]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_25));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g518__6783(.A (acc[1]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_24));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g519__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_23));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g520__1617(.A (acc[4]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_22));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g521__2802(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .B (acc[4]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_21));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g522__1705(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .B (acc[3]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_20));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g523__5122(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .B (acc[1]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_19));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g524__8246(.A (acc[3]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_18));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g525__7098(.A (n_291), .B
       (n_290), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_17));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g526__6131(.A (n_291), .B
       (n_283), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_16));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g527__1881(.A (n_281), .B (n_285),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_15));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g528__5115(.A (n_281), .B
       (n_283), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_14));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g529__7482(.A (n_279), .B
       (n_283), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_13));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g530__4733(.A (n_280), .B
       (n_282), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_12));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g531__6161(.A (n_280), .B
       (n_283), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_11));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g532__9315(.A (n_279), .B
       (n_290), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_10));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g533__9945(.A (n_291), .B
       (n_282), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_9));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g534__2883(.A (n_279), .B
       (n_282), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_8));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g535__2346(.A (n_281), .B (n_290),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_5));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g536__1666(.A (n_285), .B
       (n_279), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_7));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g537__7410(.A (n_281), .B
       (n_282), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_4));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g538__6417(.A (n_285), .B
       (n_291), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_6));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g539__5477(.A (n_280), .B
       (n_290), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_3));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g540__2398(.A (n_280), .B (n_285),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_2));
  NAND2XL g12124__12248(.A (gj[0]), .B (gj[1]), .Y (n_288));
  NAND2XL g12122__12249(.A (gk[0]), .B (gk[1]), .Y (n_289));
  NAND3BX1 g2(.AN (n_253), .B (n_249), .C (n_294), .Y (n_290));
  NAND3BX1 g12250(.AN (n_257), .B (n_292), .C (n_293), .Y (n_291));
  AOI221X1 g12251(.A0 (B[11]), .A1 (n_155), .B0 (B[15]), .B1 (n_156),
       .C0 (n_296), .Y (n_292));
  AOI221X1 g12252(.A0 (B[47]), .A1 (n_168), .B0 (B[43]), .B1 (n_147),
       .C0 (n_297), .Y (n_293));
  AOI221X1 g12253(.A0 (A[45]), .A1 (n_143), .B0 (A[37]), .B1 (n_119),
       .C0 (n_295), .Y (n_294));
  AO22XL g12254(.A0 (A[33]), .A1 (n_153), .B0 (A[41]), .B1 (n_121), .Y
       (n_295));
  AO22XL g12255(.A0 (B[35]), .A1 (n_170), .B0 (B[39]), .B1 (n_148), .Y
       (n_296));
  AO22XL g12256(.A0 (B[3]), .A1 (n_163), .B0 (B[7]), .B1 (n_154), .Y
       (n_297));
  DFFRHQX1 \acc_reg[7] (.RN (n_9), .CK (clk), .D (n_111), .Q (acc[7]));
endmodule

